### PR TITLE
Fixes #143 where the build tool crashes if the confirm button is clic…

### LINKED ISSUE #143: Builder tool crashes when the confirm button is clicked there is no hut.
### Minecolonies version
0.4.805 and up (confirmed on the test server and the 1.10.2 branch).
### Expected behavior
The window should close and a message stating the hut is missing should appear in chat.
[crash-2016-09-19_11.39.16-client.txt](https://github.com/Minecolonies/minecolonies/files/480762/crash-2016-09-19_11.39.16-client.txt)

### Actual behaviour
Client crashes
### Steps to reproduce the problem
remove huts from inventory
use the tool
make sure you are looking at huts
click confirm.
Watch the crash.

### PR DESCRIPTION
**Pull request by DarVillous**
Closes #143 build tool crashes when confirm is clicked while viewing huts without a hut in the inventory

# Changes proposed in this pull request:
-added a check to the confirm click to validate that there is an active schematic and either the mode is for decorations or the selected hut is in the inventory 
- If the check fails a chat message is sent to the client informing them the hut is not in their inventory.
- Removed the unused default block pos

Review please @Minecolonies/maintainers

the auto format template kept breaking the spacing on line 127.

### CODE REVIEW

File: src/main/java/com/minecolonies/client/gui/WindowBuildTool.java [hunk 1]
```diff
@@ -448,8 +447,20 @@ private void updateLevelButton()
      */
     private void confirmClicked(Button button)
     {
-        MineColonies.getNetwork().sendToServer(new BuildToolPlaceMessage(hutDec.get(hutDecIndex),
-                                                                          getStyles().get(styleIndex), this.pos, rotation, Settings.instance.isInHutMode()));
+        InventoryPlayer inventory = this.mc.thePlayer.inventory;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: MINOR Local variable 'inventory' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowBuildTool.java [hunk 2]
```diff
@@ -448,8 +447,20 @@ private void updateLevelButton()
...
+        if (null != Settings.instance.getActiveSchematic() &&
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: MINOR '&&' should be on a new line. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AOperator_Wrap)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 2 issues
* MINOR 2 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/client/gui/WindowBuildTool.java (hunk 2 above)
Comment (DarVillous) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: Changed.

File: src/main/java/com/minecolonies/client/gui/WindowBuildTool.java (hunk 1 above)
Comment (DarVillous) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: Would declaring this as final be valid?  The code would be client side so it should not be an issue for SMP; but does the players inventory object ever change in the event of death or other mods?

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 1 issue
* MINOR 1 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/client/gui/WindowBuildTool.java (hunk 1 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: The inventory for sure won't be assigned anymore in this method. The object of the player may change but this change will never reach the method.

Comment (DarVillous) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: Ok.  Changed.

File: src/main/resources/assets/minecolonies/lang/en_US.lang [hunk 3]
```diff
@@ -177,4 +177,5 @@ com.minecolonies.gui.workerHuts.farmerHut.East=East
 com.minecolonies.gui.workerHuts.farmerHut.West=West
 com.minecolonies.gui.workerHuts.farmerHut.unused=unused
 com.minecolonies.gui.scarecrow.user=Field used by: %s
-com.minecolonies.gui.scarecrow.user.noone=no-one
\ No newline at end of file
+com.minecolonies.gui.scarecrow.user.noone=no-one
+com.minecolonies.gui.buildtool.nohutininventory=The hut was not found in your inventory.
```
Comment (DarVillous) [inline src/main/resources/assets/minecolonies/lang/en_US.lang]: changed.

File: src/main/java/com/minecolonies/client/gui/WindowBuildTool.java [hunk 4]
```diff
@@ -448,8 +447,20 @@ private void updateLevelButton()
      */
     private void confirmClicked(Button button)
     {
-        MineColonies.getNetwork().sendToServer(new BuildToolPlaceMessage(hutDec.get(hutDecIndex),
-                                                                          getStyles().get(styleIndex), this.pos, rotation, Settings.instance.isInHutMode()));
+        final InventoryPlayer inventory = this.mc.thePlayer.inventory;
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: We probably should do this verification and send the message from the server side.

File: src/main/java/com/minecolonies/client/gui/WindowBuildTool.java [hunk 5]
```diff
@@ -115,13 +115,16 @@
      */
     private static final String HUT_PREFIX = ":blockHut";
 
-    private static final BlockPos DEFAULT_POS = new BlockPos(0, 0, 0);
-
     private static final int POSSIBLE_ROTATIONS = 4;
     private static final int ROTATE_RIGHT       = 1;
     private static final int ROTATE_LEFT        = 3;
 
     /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 1 issue
* MINOR 1 minor

Watch the comments in this conversation to review them.

**Comment by Raycoms** [comment]
:shipit: for me

File: src/main/java/com/minecolonies/client/gui/WindowBuildTool.java (hunk 4 above)
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: To elaborate, I think that these checks should be done in the handleHut method inside of BuildToolPlaceMessage. Interestingly it looks like there already is some checks there, so those should have prevented the crash. (Maybe they should be improved)

Also sending the message to the player can happen in the same handleHut method.

Comment (DarVillous) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: Wouldn't we want to avoid the round trip of network traffic in SMP and server side processing?  (I know it is not much processing)

Comment (cltnschlosser) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: Well we already do the check on the server (still not sure if its working), The only added network traffic would be sending the chat message. Technically we would be saving client side processing (a trivial amount)

Comment (DarVillous) [inline src/main/java/com/minecolonies/client/gui/WindowBuildTool.java]: I've pushed a new version that removes the inventory check from the client side and uses a more accurate method to prevent the crash.  

I have also added the chat message to the server.  However, I have also left the chat message on the client side.  

When this crash is prevented on the client side the server code will never run and there would be no feedback to the player if we removed it.  From the players point of view, the crash is because they do not have any huts in their inventory so I did not change the message.

File: src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java [hunk 6]
```diff
@@ -39,6 +40,12 @@
 
     private boolean isHut;
 
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 2 issues
* MINOR 2 minor

Watch the comments in this conversation to review them.

**Comment by cltnschlosser** [comment]
Can someone verify that this does indeed prevent the crash? It looks good to me, but I'm worried that if it was crashing then something is wrong with our server side check.

**Comment by DarVillous** [comment]
this crash is not related the server side colonyid crash and is client side; it occurs before the call is made to the server.

**Comment by Kostronor** [comment]
:shipit:

**Comment by Raycoms** [comment]
:shipit:
