### PR TITLE
Fixes some permissions bugs and adds logger

### LINKED ISSUE #133: After amount of colonies on the server, no new colonies may be placed
### Minecolonies version
Newest 1.8.9
### Expected behavior
Place townhall in clean area.
### Actual behaviour
"Too close to existing townhall"
### Steps to reproduce the problem
Try to place a townhall on our server.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #133 
# Changes proposed in this pull request:
- Fixes a crash if the colony returns owner null (happens sometimes when porting colonies)
- Fixes bug where colonies couldn't be placed anymore.
- Adds a logger to observe server behaviour on colony placement.

Review please @Minecolonies/maintainers

### CODE REVIEW

**Comment by Kostronor** [comment]
LGTM

**Comment by Raycoms** [comment]
@Kostronor Please take a look at this again.

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 1]
```diff
@@ -368,7 +368,7 @@ public World getWorld()
     }
 
     @Override
-    public float getDistanceSquared(@NotNull BlockPos pos)
+    public long getDistanceSquared(@NotNull BlockPos pos)
     {
         //  Perform a 2D distance calculation, so pass center.posY as the Y
         return BlockPosUtil.getDistanceSquared(center, new BlockPos(pos.getX(), center.getY(), pos.getZ()));
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/Colony.java]: This distance isn't 2D like the comment says, we should be doing a 2D calculation though. Also why are we making a new BlockPos, from an existing BlockPos? They are immutable, we should just pass in pos.

File: src/main/java/com/minecolonies/colony/ColonyView.java [hunk 2]
```diff
@@ -448,7 +454,7 @@ public boolean isCoordInColony(@NotNull World w, @NotNull BlockPos pos)
     }
 
     @Override
-    public float getDistanceSquared(@NotNull BlockPos pos)
+    public long getDistanceSquared(@NotNull BlockPos pos)
     {
         //  Perform a 2D distance calculation, so pass center.posY as the Y
         return BlockPosUtil.getDistanceSquared(center, new BlockPos(pos.getX(), center.getY(), pos.getZ()));
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/ColonyView.java]: All above comments apply here as well

**Comment by cltnschlosser** [comment]
@Raycoms You need to update the unit tests now that the method returns a long and not a float

File: src/main/java/com/minecolonies/util/BlockPosUtil.java [hunk 3]
```diff
@@ -142,11 +142,11 @@ public static boolean isClose(@NotNull BlockPos coordinate, @NotNull EntityCitiz
      * @param block2 position two.
      * @return squared distance.
      */
-    public static int getDistanceSquared(@NotNull BlockPos block1, @NotNull BlockPos block2)
+    public static long getDistanceSquared(@NotNull BlockPos block1, @NotNull BlockPos block2)
     {
-        int i = block1.getX() - block2.getX();
-        int i1 = block1.getY() - block2.getY();
-        int i2 = block1.getZ() - block2.getZ();
+        long i = block1.getX() - block2.getX();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/BlockPosUtil.java]: CRITICAL Cast one of the operands of this substraction operation to a "long". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2184)

File: src/main/java/com/minecolonies/util/BlockPosUtil.java [hunk 4]
```diff
@@ -142,11 +142,11 @@ public static boolean isClose(@NotNull BlockPos coordinate, @NotNull EntityCitiz
...
+        long i1 = block1.getY() - block2.getY();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/BlockPosUtil.java]: CRITICAL Cast one of the operands of this substraction operation to a "long". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2184)

File: src/main/java/com/minecolonies/util/BlockPosUtil.java [hunk 5]
```diff
@@ -142,11 +142,11 @@ public static boolean isClose(@NotNull BlockPos coordinate, @NotNull EntityCitiz
...
+        long i2 = block1.getZ() - block2.getZ();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/BlockPosUtil.java]: CRITICAL Cast one of the operands of this substraction operation to a "long". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2184)

File: src/main/java/com/minecolonies/util/Log.java [hunk 6]
```diff
@@ -12,16 +10,5 @@
...
-     * Generates a logger for a specific class
-     *
-     * @param clazz Class to generate logger for
-     * @return Created {@link Logger}
-     */
-    public static Logger generateLoggerForClass(Class<?> clazz)
-    {
-        return LogManager.getLogger(Constants.MOD_ID + "::" + clazz.getSimpleName());
-    }
+    public static Logger logger = null;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/Log.java]: CRITICAL Make this "public static logger" field final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1444)
MAJOR Make logger a static final constant or non-public and provide accessors if needed. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/blockout/PaneParams.java [hunk 7]
```diff
@@ -252,7 +252,7 @@ private static int parseScalableIntegerRegexMatch(Matcher m, int def, int scale)
         }
         catch (NumberFormatException | IndexOutOfBoundsException | IllegalStateException ex)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/blockout/PaneParams.java]: CRITICAL Either log or rethrow this exception. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/com/blockout/PaneParams.java [hunk 8]
```diff
@@ -252,7 +252,7 @@ private static int parseScalableIntegerRegexMatch(Matcher m, int def, int scale)
...
         {
-            Log.logger.warn(ex);
+            ex.printStackTrace();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/blockout/PaneParams.java]: CRITICAL Use a logger to log this exception. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1148)

File: src/main/java/com/blockout/controls/Image.java [hunk 9]
```diff
@@ -97,7 +97,7 @@ private void loadMapDimensions()
             }
             catch (IOException e)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/blockout/controls/Image.java]: CRITICAL Either log or rethrow this exception. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1166)

File: src/main/java/com/blockout/controls/Image.java [hunk 10]
```diff
@@ -97,7 +97,7 @@ private void loadMapDimensions()
...
             {
-                Log.logger.error(e);
+                e.printStackTrace();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/blockout/controls/Image.java]: CRITICAL Use a logger to log this exception. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1148)

File: src/main/java/com/minecolonies/event/EventHandler.java [hunk 11]
```diff
@@ -207,7 +208,9 @@ private static boolean canPlayerPlaceTownHallHere(@NotNull World world, @NotNull
         {
             if (closestColony.hasTownHall() || !closestColony.getPermissions().isColonyMember(player))
             {
-                //  Placing in a colony which already has a town hall
+                Log.logger.info("Can't place at: " + pos.getX() + "." + pos.getY() + "." + pos.getZ() + ". Because of townhall of: " + closestColony.getName() + " at " +
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/event/EventHandler.java]: MINOR '+' should be on a new line. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AOperator_Wrap)

File: src/main/java/com/minecolonies/event/EventHandler.java [hunk 12]
```diff
@@ -224,7 +227,9 @@ private static boolean canPlayerPlaceTownHallHere(@NotNull World world, @NotNull
 
         if (closestColony.getDistanceSquared(pos) <= MathUtils.square(ColonyManager.getMinimumDistanceBetweenTownHalls()))
         {
-            //  Placing too close to an existing colony
+            Log.logger.info("Can't place at: " + pos.getX() + "." + pos.getY() + "." + pos.getZ() + ". Because of townhall of: " + closestColony.getName() + " at " +
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/event/EventHandler.java]: MINOR '+' should be on a new line. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AOperator_Wrap)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 14 issues
* CRITICAL 8 critical
* MAJOR 2 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [Colony.java#L388](https://github.com/Minecolonies/minecolonies/blob/5bb23d2ccebb3904ddcb3df9437767aff2a24e89/src/main/java/com/minecolonies/colony/Colony.java#L388): Add the "@Override" annotation above this method signature [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)
1. MINOR [PaneParams.java#L3](https://github.com/Minecolonies/minecolonies/blob/5bb23d2ccebb3904ddcb3df9437767aff2a24e89/src/main/java/com/blockout/PaneParams.java#L3): Remove this unused import 'com.minecolonies.util.Log'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [Image.java#L5](https://github.com/Minecolonies/minecolonies/blob/5bb23d2ccebb3904ddcb3df9437767aff2a24e89/src/main/java/com/blockout/controls/Image.java#L5): Remove this unused import 'com.minecolonies.util.Log'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/util/BlockPosUtil.java [hunk 13]
```diff
@@ -142,15 +142,29 @@ public static boolean isClose(@NotNull BlockPos coordinate, @NotNull EntityCitiz
...
     /**
+     * 2D Squared distance between two BlockPos.
+     *
+     * @param block1 position one.
+     * @param block2 position two.
+     * @return 2D squared distance.
+     */
+    public static long getDistanceSquared2D(@NotNull BlockPos block1, @NotNull BlockPos block2)
+    {
+        long i = (long) block1.getX() - block2.getX();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/BlockPosUtil.java]: MINOR Local variable 'i' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/BlockPosUtil.java [hunk 14]
```diff
@@ -142,15 +142,29 @@ public static boolean isClose(@NotNull BlockPos coordinate, @NotNull EntityCitiz
...
+        long i2 = (long) block1.getZ() - block2.getZ();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/BlockPosUtil.java]: MINOR Local variable 'i2' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 13 issues
* CRITICAL 5 critical
* MAJOR 2 major
* MINOR 6 minor

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [Colony.java#L388](https://github.com/Minecolonies/minecolonies/blob/f98dcb3fafd4a8e87f4905b6f07f04220ceff43f/src/main/java/com/minecolonies/colony/Colony.java#L388): Add the "@Override" annotation above this method signature [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)
1. MINOR [PaneParams.java#L3](https://github.com/Minecolonies/minecolonies/blob/f98dcb3fafd4a8e87f4905b6f07f04220ceff43f/src/main/java/com/blockout/PaneParams.java#L3): Remove this unused import 'com.minecolonies.util.Log'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [Image.java#L5](https://github.com/Minecolonies/minecolonies/blob/f98dcb3fafd4a8e87f4905b6f07f04220ceff43f/src/main/java/com/blockout/controls/Image.java#L5): Remove this unused import 'com.minecolonies.util.Log'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/MineColonies.java [hunk 15]
```diff
@@ -18,12 +19,16 @@
...
 import net.minecraftforge.fml.relauncher.Side;
+import org.apache.logging.log4j.LogManager;
+import org.apache.logging.log4j.Logger;
 import org.jetbrains.annotations.NotNull;
 
 @Mod(modid = Constants.MOD_ID, name = Constants.MOD_NAME, version = Constants.VERSION,
   dependencies = Constants.FORGE_VERSION, acceptedMinecraftVersions = Constants.MC_VERSION)
 public class MineColonies
 {
+    private static Logger logger = LogManager.getLogger(Constants.MOD_ID);
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/MineColonies.java]: This isn't going to fix our issue, the unit tests fail when LogManager is loaded.

File: src/main/java/com/minecolonies/util/BlockPosUtil.java [hunk 16]
```diff
@@ -144,10 +152,22 @@ public static boolean isClose(@NotNull BlockPos coordinate, @NotNull EntityCitiz
      */
     public static long getDistanceSquared(@NotNull BlockPos block1, @NotNull BlockPos block2)
     {
-        long i = (long) block1.getX() - block2.getX();
-        long i1 = (long) block1.getY() - block2.getY();
-        long i2 = (long) block1.getZ() - block2.getZ();
-        return i * i + i1 * i1 + i2 * i2;
+        final long xDiff = Math.abs((long) block1.getX() - block2.getX());
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/util/BlockPosUtil.java]: Math.abs is a waste

File: src/main/java/com/minecolonies/util/BlockPosUtil.java [hunk 17]
```diff
@@ -23,8 +23,16 @@
...
 {
+    /**
+     * Min distance to availate two positions as close.
+     */
     private static final double CLOSE_DISTANCE = 4.84;
 
+    /**
+     * Max distance two points should have divided by 3 because of 3dim positions.
+     */
+    private static final long MAX_SQRT = 3_000_000_000L / 3;
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/util/BlockPosUtil.java]: Worlds can be much bigger than this now, I thing its 60_000_000 x 60_000_000 now

File: src/main/java/com/minecolonies/util/BlockPosUtil.java [hunk 18]
```diff
@@ -144,10 +152,22 @@ public static boolean isClose(@NotNull BlockPos coordinate, @NotNull EntityCitiz
...
     {
-        long i = (long) block1.getX() - block2.getX();
-        long i1 = (long) block1.getY() - block2.getY();
-        long i2 = (long) block1.getZ() - block2.getZ();
-        return i * i + i1 * i1 + i2 * i2;
+        final long xDiff = Math.abs((long) block1.getX() - block2.getX());
+        final long yDiff = Math.abs((long) block1.getY() - block2.getY());
+        final long zDiff = Math.abs((long) block1.getZ() - block2.getZ());
+
+        if (xDiff > MAX_SQRT || yDiff > MAX_SQRT || zDiff > MAX_SQRT)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/util/BlockPosUtil.java]: This whole check is unnecessary. I did some simple math, even if minecraft worlds were 10 times bigger than they are currently a long would still work for us.

File: src/main/java/com/minecolonies/util/BlockPosUtil.java [hunk 19]
```diff
@@ -159,9 +179,21 @@ public static long getDistanceSquared(@NotNull BlockPos block1, @NotNull BlockPo
      */
     public static long getDistanceSquared2D(@NotNull BlockPos block1, @NotNull BlockPos block2)
     {
-        long i = (long) block1.getX() - block2.getX();
-        long i2 = (long) block1.getZ() - block2.getZ();
-        return i * i + i2 * i2;
+        final long xDiff = Math.abs((long) block1.getX() - block2.getX());
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/util/BlockPosUtil.java]: Above comments apply as well.

File: src/test/java/com/minecolonies/util/DistanceSquaredTest.java [hunk 20]
```diff
@@ -0,0 +1,57 @@
...
+
+    /**
+     * Nunber of iterations in testCase.
+     */
+    private static final int NOTestCases = 10000;
+
+    @Test
+    public void test2DTwoPositions()
+    {
+        for (int i = 0; i < NOTestCases; i++)
```
Comment (cltnschlosser) [inline src/test/java/com/minecolonies/util/DistanceSquaredTest.java]: We should just test normal values and extremes, using 10,000 random values is a bad test.

File: src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java [hunk 21]
```diff
@@ -58,7 +58,7 @@ protected PathEntity search()
     {
         if (Configurations.pathfindingDebugVerbosity > DEBUG_VERBOSITY_NONE)
         {
-            Log.logger.info(String.format("Pathfinding from [%d,%d,%d] away from [%d,%d,%d]", start.getX(), start.getY(), start.getZ(), avoid.getX(), avoid.getY(), avoid.getZ()));
+            Log.getLogger().info(String.format("Pathfinding from [%d,%d,%d] away from [%d,%d,%d]", start.getX(), start.getY(), start.getZ(), avoid.getX(), avoid.getY(), avoid.getZ()));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java]: MINOR Split this 184 characters long line (which is greater than 180 authorized). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/event/EventHandler.java [hunk 22]
```diff
@@ -207,7 +208,9 @@ private static boolean canPlayerPlaceTownHallHere(@NotNull World world, @NotNull
         {
             if (closestColony.hasTownHall() || !closestColony.getPermissions().isColonyMember(player))
             {
-                //  Placing in a colony which already has a town hall
+                Log.getLogger().info("Can't place at: " + pos.getX() + "." + pos.getY() + "." + pos.getZ() + ". Because of townhall of: " + closestColony.getName() + " at " +
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/event/EventHandler.java]: MINOR '+' should be on a new line. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AOperator_Wrap)

File: src/main/java/com/minecolonies/event/EventHandler.java [hunk 23]
```diff
@@ -224,7 +227,9 @@ private static boolean canPlayerPlaceTownHallHere(@NotNull World world, @NotNull
 
         if (closestColony.getDistanceSquared(pos) <= MathUtils.square(ColonyManager.getMinimumDistanceBetweenTownHalls()))
         {
-            //  Placing too close to an existing colony
+            Log.getLogger().info("Can't place at: " + pos.getX() + "." + pos.getY() + "." + pos.getZ() + ". Because of townhall of: " + closestColony.getName() + " at " +
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/event/EventHandler.java]: MINOR '+' should be on a new line. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AOperator_Wrap)

File: src/test/java/com/minecolonies/util/DistanceSquaredTest.java [hunk 24]
```diff
@@ -0,0 +1,73 @@
...
+            BlockPos posB = new BlockPos(-MAX_POSITION+i, 0, -MAX_POSITION+i);
+
+            long distance = BlockPosUtil.getDistanceSquared(posA, posB);
+
+            assertThat("2Dim distance between " + posA + " and " + posB, distance, greaterThanOrEqualTo(0L));
+        }
+    }
+
+    @Test
+    public void test3DTwoPositions()
```
Comment (MinecoloniesSonar) [inline src/test/java/com/minecolonies/util/DistanceSquaredTest.java]: MINOR Rename this method name to match the regular expression: '^test[A-Z][a-zA-Z0-9]*$' [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS3578)

File: src/test/java/com/minecolonies/util/DistanceSquaredTest.java [hunk 25]
```diff
@@ -0,0 +1,73 @@
...
+public class DistanceSquaredTest
+{
+
+    /**
+     * Max x/z position in vanilla minecraft.
+     */
+    private static final int MAX_POSITION =  30_000_000;
+
+    @Test
+    public void test2DTwoPositions()
```
Comment (MinecoloniesSonar) [inline src/test/java/com/minecolonies/util/DistanceSquaredTest.java]: MINOR Rename this method name to match the regular expression: '^test[A-Z][a-zA-Z0-9]*$' [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS3578)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 10 issues
* CRITICAL 4 critical
* MAJOR 1 major
* MINOR 5 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [Colony.java#L388](https://github.com/Minecolonies/minecolonies/blob/c80d76523e80105d9087d16760a0fce4788a1c91/src/main/java/com/minecolonies/colony/Colony.java#L388): Add the "@Override" annotation above this method signature [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)

File: src/test/java/com/minecolonies/util/DistanceSquaredTest.java (hunk 24 above)
Comment (Kostronor) [inline src/test/java/com/minecolonies/util/DistanceSquaredTest.java]: I suggest `testDistance3DTwoPositions`

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 26]
```diff
@@ -38,7 +37,7 @@
     /**
      * The position it faces.
      */
-    public static final PropertyDirection FACING = PropertyDirection.create("FACING", Plane.HORIZONTAL);
+    public static final PropertyDirection FACING = PropertyDirection.create("FACING", EnumFacing.Plane.HORIZONTAL);
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: I don't see why this is necessary when we statically import EnumFacing in L31

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 27]
```diff
@@ -368,10 +368,10 @@ public World getWorld()
     }
 
     @Override
-    public float getDistanceSquared(@NotNull BlockPos pos)
+    public long getDistanceSquared(@NotNull BlockPos pos)
     {
         //  Perform a 2D distance calculation, so pass center.posY as the Y
-        return BlockPosUtil.getDistanceSquared(center, new BlockPos(pos.getX(), center.getY(), pos.getZ()));
+        return BlockPosUtil.getDistanceSquared2D(center, pos);
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/colony/Colony.java]: Why do we still use 2D distance for the general distance? Would it not make more sense to change all uses of this to 2D and make this 3d?

File: src/main/java/com/minecolonies/colony/ColonyView.java [hunk 28]
```diff
@@ -448,10 +454,10 @@ public boolean isCoordInColony(@NotNull World w, @NotNull BlockPos pos)
     }
 
     @Override
-    public float getDistanceSquared(@NotNull BlockPos pos)
+    public long getDistanceSquared(@NotNull BlockPos pos)
     {
         //  Perform a 2D distance calculation, so pass center.posY as the Y
-        return BlockPosUtil.getDistanceSquared(center, new BlockPos(pos.getX(), center.getY(), pos.getZ()));
+        return BlockPosUtil.getDistanceSquared2D(center, pos);
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/colony/ColonyView.java]: Same question as in Colony.

File: src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java [hunk 29]
```diff
@@ -58,7 +58,8 @@ protected PathEntity search()
     {
         if (Configurations.pathfindingDebugVerbosity > DEBUG_VERBOSITY_NONE)
         {
-            Log.logger.info(String.format("Pathfinding from [%d,%d,%d] away from [%d,%d,%d]", start.getX(), start.getY(), start.getZ(), avoid.getX(), avoid.getY(), avoid.getZ()));
+            Log.getLogger().info(String.format("Pathfinding from [%d,%d,%d] away from [%d,%d,%d]"
+                    , start.getX(), start.getY(), start.getZ(), avoid.getX(), avoid.getY(), avoid.getZ()));
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java]: The comma should be on last line imo.

**Comment by Kostronor** [comment]
:shipit: @cltnschlosser

File: src/main/java/com/minecolonies/achievements/ModAchievements.java [hunk 30]
```diff
@@ -67,9 +67,8 @@
     public static final Achievement achievementBuildingColonist   = new MineColoniesAchievement("upgrade.colonist.first",
                                                                                                  0,
                                                                                                  2,
-                                                                                                 ModBlocks
-                                                                                                   .blockHutCitizen,
-                                                                                                 achievementGetSupply).registerStat();
+                                                                                                 ModBlocks.blockHutCitizen,
+                                                                                                 achievementBuildingTownhall).registerStat();
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/achievements/ModAchievements.java]: Is achievement building townhall actually building it? or just placing it?

File: src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java [hunk 31]
```diff
@@ -58,7 +58,8 @@ protected PathEntity search()
     {
         if (Configurations.pathfindingDebugVerbosity > DEBUG_VERBOSITY_NONE)
         {
-            Log.getLogger().info(String.format("Pathfinding from [%d,%d,%d] away from [%d,%d,%d]", start.getX(), start.getY(), start.getZ(), avoid.getX(), avoid.getY(), avoid.getZ()));
+            Log.getLogger().info(String.format("Pathfinding from [%d,%d,%d] away from [%d,%d,%d]"
+                    , start.getX(), start.getY(), start.getZ(), avoid.getX(), avoid.getY(), avoid.getZ()));
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java]: I'd put the comma on the previous line.

File: src/main/java/com/blockout/PaneParams.java [hunk 32]
```diff
@@ -1,5 +1,6 @@
 package com.blockout;
 
+import com.minecolonies.util.Log;
```
Comment (cltnschlosser) [inline src/main/java/com/blockout/PaneParams.java]: I'm not a fan of us using minecolonies classes inside of blockout. Blockout should have its own logger.

File: src/main/java/com/minecolonies/achievements/ModAchievements.java (hunk 30 above)
Comment (Kostronor) [inline src/main/java/com/minecolonies/achievements/ModAchievements.java]: Just placing it. This marks the start of a colony, even when you don't build the building.

We could add achievements for completing the townhall like we to for all buildings, and I think they would be really cool! What do you think?

Pinging @Raycoms

File: src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java (hunk 31 above)
Comment (Kostronor) [inline src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java]: Damn I forgot one, good catch!

File: src/main/java/com/blockout/PaneParams.java (hunk 32 above)
Comment (Kostronor) [inline src/main/java/com/blockout/PaneParams.java]: Agreed!

File: src/test/java/com/minecolonies/util/DistanceSquaredTest.java [hunk 33]
```diff
@@ -0,0 +1,71 @@
...
+     * Max x/z position in vanilla minecraft.
+     */
+    private static final int MAX_POSITION =  30_000_000;
+
+    @Test
+    public void testDistance2DTwoPositions()
+    {
+        for (int i = -400; i < 400; i+=20)
+        {
+            BlockPos posA = new BlockPos(i^2, 0, i*2);
```
Comment (cltnschlosser) [inline src/test/java/com/minecolonies/util/DistanceSquaredTest.java]: Whats the point of XORing with 2 and 3? Also I don't think we need to use for loops, pick a normal value, a couple extremes and explicitly write them out. Maybe 5 points max?

Comment (Kostronor) [inline src/test/java/com/minecolonies/util/DistanceSquaredTest.java]: I think @Raycoms meant Math.pow there

Comment (cltnschlosser) [inline src/test/java/com/minecolonies/util/DistanceSquaredTest.java]: 5 distances. Honestly if you tested the max minecraft distance and verified that the result was equal to what you expect, that should be fine.

File: src/main/java/com/minecolonies/achievements/ModAchievements.java (hunk 30 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/achievements/ModAchievements.java]: Yeah we may add that later, but other pr please.

File: src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java (hunk 31 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/entity/pathfinding/PathJobMoveAwayFromLocation.java]: Can'T find that one incode.

File: src/main/java/com/blockout/PaneParams.java (hunk 32 above)
Comment (Raycoms) [inline src/main/java/com/blockout/PaneParams.java]: I'll  "copy" the logger of minecolonies to blockout and will use "blockout" as mod id.
After midday meal =D

Comment (Kostronor) [inline src/main/java/com/blockout/PaneParams.java]: I changed the logger

**Comment by Kostronor** [comment]
@cltnschlosser Can you re-review the changes?

File: src/main/java/com/blockout/Log.java [hunk 34]
```diff
@@ -0,0 +1,29 @@
+package com.blockout;
+
+import com.minecolonies.lib.Constants;
+import org.apache.logging.log4j.LogManager;
+import org.apache.logging.log4j.Logger;
+
+/**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/blockout/Log.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/blockout/Log.java [hunk 35]
```diff
@@ -0,0 +1,29 @@
...
+ * Logging utility class
+ */
+public class Log
```
Comment (MinecoloniesSonar) [inline src/main/java/com/blockout/Log.java]: MAJOR Add a private constructor to hide the implicit public one. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1118)

File: src/main/java/com/blockout/Log.java [hunk 36]
```diff
@@ -0,0 +1,29 @@
...
+{
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/blockout/Log.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/blockout/Log.java [hunk 37]
```diff
@@ -0,0 +1,29 @@
...
+     * Mod logger
+     */
+    private static Logger logger = null;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/blockout/Log.java]: MINOR Make the "logger" logger private static final. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1312)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 4 issues
* MAJOR 1 major
* MINOR 3 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/blockout/Log.java [hunk 38]
```diff
@@ -0,0 +1,39 @@
+package com.blockout;
+
+import com.minecolonies.lib.Constants;
+import org.apache.logging.log4j.LogManager;
+import org.apache.logging.log4j.Logger;
+
+/**
+ * Logging utility class.
+ */
+public class Log
```
Comment (MinecoloniesSonar) [inline src/main/java/com/blockout/Log.java]: MAJOR Make this class "final" or add a public constructor. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2974)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 2 issues
* MAJOR 2 major

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [Log.java#L10](https://github.com/Minecolonies/minecolonies/blob/7df5258e07fefe9b37223de74544788112626a9b/src/main/java/com/minecolonies/util/Log.java#L10): Make this class "final" or add a public constructor. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2974)

File: src/test/java/com/minecolonies/test/AbstractTest.java [hunk 39]
```diff
@@ -0,0 +1,40 @@
...
+
+import static org.mockito.Matchers.anyObject;
+import static org.mockito.Matchers.anyString;
+import static org.powermock.api.mockito.PowerMockito.*;
+
+/**
+ * Abstract test class to abstract away some common uses functionality in Tests
+ */
+@PrepareForTest({ColonyManager.class, LanguageHandler.class, Log.class})
+@PowerMockIgnore("javax.management.*")
```
Comment (cltnschlosser) [inline src/test/java/com/minecolonies/test/AbstractTest.java]: I didn't know this was a thing, we should just ignore the Log class, and then everything can go back to normal (the way we had it). Also I feel like the ColonyManger and LanguageHandler stuff doesn't need to be here, LanguageHandler could be I guess.

File: src/main/java/com/blockout/Log.java [hunk 40]
```diff
@@ -0,0 +1,29 @@
+package com.blockout;
+
+import com.minecolonies.lib.Constants;
```
Comment (cltnschlosser) [inline src/main/java/com/blockout/Log.java]: This logger still depends on minecolonies...

File: src/test/java/com/minecolonies/test/AbstractTest.java (hunk 39 above)
Comment (Kostronor) [inline src/test/java/com/minecolonies/test/AbstractTest.java]: Ignoring logging feels wrong imo and in case of us debugging tests later, enabled logging is a good thing imo.

And PowerMocking all classes that don't work means reducing the thoughts needed for writing tests. With the overall goal to just write stuff that somehow works later on, even if mc is not really testable.

File: src/main/java/com/blockout/Log.java (hunk 40 above)
Comment (Kostronor) [inline src/main/java/com/blockout/Log.java]: Yeah, true that. I could inline the constant, but we should prepoend our blockout loggings with Minecolonies so that people reading the mod go to us and not to lunatics

Comment (Kostronor) [inline src/main/java/com/blockout/Log.java]: Removed the import

Comment (Raycoms) [inline src/main/java/com/blockout/Log.java]: BlockOut is actually made by us =D

Comment (Kostronor) [inline src/main/java/com/blockout/Log.java]: Yeah but we shouldn't add extra deps between them so we can compile blockout without minecolonies if we want

Comment (Raycoms) [inline src/main/java/com/blockout/Log.java]: I agree, but they won't go to lunatics anyway for blockOut I wanted to say.

File: src/main/java/com/blockout/Log.java [hunk 41]
```diff
@@ -0,0 +1,38 @@
...
+    /**
+     * Getter for the blockout Logger.
+     *
+     * @return the logger.
+     */
+    public static Logger getLogger()
+    {
+        if (logger == null)
+        {
+            Log.logger = LogManager.getLogger("Mineclonies:blockout");
```
Comment (cltnschlosser) [inline src/main/java/com/blockout/Log.java]: Typo, but otherwise LGTM

Comment (Kostronor) [inline src/main/java/com/blockout/Log.java]: Done
