### PR TITLE
bug fix

### LINKED ISSUE #241: Hut's Contents
### Minecolonies version

4.61
### Expected behavior

To drop the contents in the hut when it is broken
### Actual behaviour

When the hut is broken the contents are forever gone
### Steps to reproduce the problem

Destroy a hut that has items inside

### PR DESCRIPTION
**Pull request by MarioFernandes73**
Closes #241

# Changes proposed in this pull request:
- Fixed the bug which involved dropping the items that a blockHut contained (if any) when it was destroyed

Review please

### CODE REVIEW

File: src/main/java/com/minecolonies/colony/buildings/AbstractBuilding.java [hunk 1]
```diff
@@ -503,6 +506,18 @@ public final void destroy()
      */
     public void onDestroyed()
     {
+
+        final TileEntityColonyBuilding tileEntity = this.getTileEntity();
+        final World world = colony.getWorld();
+        final Block block = world.getBlockState(this.location).getBlock();
+
+        if (tileEntity instanceof IInventory)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/AbstractBuilding.java]: MAJOR Remove this useless "instanceof" operator; it will always return "true". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1850)

File: src/main/java/com/minecolonies/colony/buildings/AbstractBuilding.java [hunk 2]
```diff
@@ -503,6 +506,18 @@ public final void destroy()
      */
     public void onDestroyed()
     {
+
+        final TileEntityColonyBuilding tileEntity = this.getTileEntity();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/AbstractBuilding.java]: MAJOR Rename "tileEntity" which hides the field declared at line 125. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AHiddenFieldCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 2 issues
* MAJOR 2 major

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/colony/buildings/AbstractBuilding.java [hunk 3]
```diff
@@ -503,6 +506,14 @@ public final void destroy()
      */
     public void onDestroyed()
     {
+
+        final TileEntityColonyBuilding tileEntityNew = this.getTileEntity();
+        final World world = colony.getWorld();
+        final Block block = world.getBlockState(this.location).getBlock();
+
+        InventoryHelper.dropInventoryItems(world, this.location, (IInventory) tileEntityNew);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/AbstractBuilding.java]: MAJOR Remove this useless "instanceof" operator; it will always return "true". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1850)

File: src/main/java/com/minecolonies/colony/buildings/AbstractBuilding.java [hunk 4]
```diff
@@ -503,6 +506,14 @@ public final void destroy()
      */
     public void onDestroyed()
     {
+
+        final TileEntityColonyBuilding tileEntityNew = this.getTileEntity();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/AbstractBuilding.java]: MAJOR Rename "tileEntity" which hides the field declared at line 125. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AHiddenFieldCheck)

**Comment by Kostronor** [comment]
:shipit: @Raycoms

**Comment by Raycoms** [comment]
:shipit:
