### PR TITLE
Minecol 20 farmer

### LINKED ISSUE #14: New Worker: Farmer
Get the farmer to work normally.

### LINKED ISSUE #76: Miner does not build shafts on SMP
### Minecolonies version 
0.3.472

### Expected behavior
He should build shafts.
### Actual behaviour
image
He builds tunnels but no shafts
### Steps to reproduce the problem
Try it on the main server

### LINKED ISSUE #86: Server Crash [Unknown]
### Minecolonies version
v472
### Crashlog

```
[21:40:04] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
at net.minecraftforge.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:132) ~[ByteBufUtils.class:?]
at com.minecolonies.colony.workorders.AbstractWorkOrder.serializeViewNetworkD
ata(AbstractWorkOrder.java:313) ~[AbstractWorkOrder.class:?]
at com.minecolonies.network.messages.ColonyViewWorkOrderMessage.(ColonyViewWorkOrderMessage.java:42) ~[ColonyViewWorkOrderMessage.class:?]
at com.minecolonies.colony.Colony.lambda$sendWorkOrderPackets$9(Colony.java:560) ~[Colony.class:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_92]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_92]
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548) ~[?:1.8.0_92]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_92]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_92]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_92]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_92]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_92]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_92]
at com.minecolonies.colony.Colony.sendWorkOrderPackets(Colony.java:560) ~[Colony.class:?]
at com.minecolonies.colony.Colony.updateSubscribers(Colony.java:485) ~[Colony.class:?]
at com.minecolonies.colony.Colony.onServerTick(Colony.java:359) ~[Colony.class:?]
at com.minecolonies.colony.ColonyManager.onServerTick(ColonyManager.java:385) ~[ColonyManager.class:?]
at com.minecolonies.event.FMLEventHandler.onServerTick(FMLEventHandler.java:22) ~[FMLEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_45_FMLEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:253) ~[FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:649) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

@Minecolonies/developers Anyone has an idea what causes this?

### LINKED ISSUE #97: Miner gets stuck in loop with nearby lava
### Minecolonies version
0.3.472 (SMP)

### Expected behavior
Not sure what the intended behaviour would be, a simple suggestion would be blocking off the lava with cobblestone so he can continue working on shafts.

### Actual behaviour
The Miner mines to the lava (pool) and automatically places cobblestone near the lava and him. This process is repeated until he retreats to the townhall before night. Also see the video sample below.

### [Video](https://www.youtube.com/watch?v=-gQb9pjSPBI)
Notes: The wood he is standing in did not cause, or seems to be affecting the behaviour. He placed it during the time I wanted to record it.

### Steps to reproduce the problem
Wait until the miner "finds" nearby lava while digging shafts or materials.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #14 
Closes #76 
Closes #86 
Closes #97 

# Changes proposed in this pull request:
- Adds a farmer worker which works for all seeds but melons and pumpkins.
- Fixes some builder bug with stairs of different materials.
- Adds the field block and rendering
- Adds a new farmer building.

Review please @Minecolonies/maintainers

### CODE REVIEW

File: src/main/java/com/minecolonies/colony/Field.java [hunk 1]
```diff
@@ -0,0 +1,467 @@
...
+        {
+            playerIn.inventory.addItemStackToInventory(inventory.getStackInSlot(0));
+            inventory.setInventorySlotContents(0, null);
+        }
+        else if(inventory.getStackInSlot(0) == null)
+        {
+            int playerIndex = slotIndex < 28 ? (slotIndex + 8) : (slotIndex - 28);
+            if(playerIn.inventory.getStackInSlot(playerIndex) != null)
+            {
+                ItemStack stack = playerIn.inventory.getStackInSlot(playerIndex).splitStack(1);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Local variable 'stack' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 2]
```diff
@@ -0,0 +1,467 @@
...
+     */
+    public enum FieldStage
+    {
+        EMPTY,
+        HOED,
+        PLANTED
+    }
+
+
+     /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Block comment has incorrect indentation level 5, expected is 4, indentation should be the same level as line 136. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 3]
```diff
@@ -0,0 +1,467 @@
...
+    /**
+     * Sets if there are any crops planted.
+     * @param fieldStage true after planting, false after harvesting.
+     */
+    public void setFieldStage(FieldStage fieldStage)
+    {
+        this.fieldStage = fieldStage;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 4]
```diff
@@ -0,0 +1,467 @@
...
+        HOED,
+        PLANTED
+    }
+
+
+     /**
+     * Private constructor to create field from NBT.
+     * @param colony the colony the field belongs to.
+     */
+    private Field(Colony colony)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR It is a good practice to call super() in a constructor [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ACallSuperInConstructor)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 5]
```diff
@@ -0,0 +1,467 @@
...
+    /**
+     * Checks if the field needs work (planting, hoeing)
+     * @return true if so.
+     */
+    public boolean needsWork()
+    {
+        return this.needsWork;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 6]
```diff
@@ -0,0 +1,467 @@
...
+     * The colony of the field.
+     */
+    private final Colony colony;
+
+    /**
+     * Has the field be taken by any worker?
+     */
+    private boolean taken = false;
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 7]
```diff
@@ -0,0 +1,467 @@
...
+    }
+
+    /**
+     * Creates an instance of our field container, this may be serve to open the GUI.
+     * @param inventory the field inventory.
+     * @param playerInventory the player inventory.
+     * @param world the world.
+     * @param location the position of the field.
+     */
+    public Field(InventoryField inventory, InventoryPlayer playerInventory, World world, BlockPos location)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR It is a good practice to call super() in a constructor [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ACallSuperInConstructor)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 8]
```diff
@@ -0,0 +1,467 @@
...
+    {
+        this.colony = ColonyManager.getColony(world,location);
+        this.location = location;
+
+        this.inventory = inventory;
+
+        addSlotToContainer(new Slot(inventory, 0, 80, 34));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)
MINOR Assign this magic number 80 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
MINOR Assign this magic number 34 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 9]
```diff
@@ -0,0 +1,467 @@
...
+     * @param world the world object.
+     * @param position the position.
+     * @return true if it is.
+     */
+    public boolean isNoPartOfField(World world, BlockPos position)
+    {
+        return world.isAirBlock(position) || world.getBlockState(position.up()).getBlock().getMaterial().isSolid();
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 10]
```diff
@@ -0,0 +1,467 @@
...
+     * Has the field been planted?
+     */
+    private FieldStage fieldStage = FieldStage.EMPTY;
+
+    /**
+     * The set seed type for the field.
+     */
+    private ItemSeeds seed;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this unused "seed" private field. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1068)
MAJOR Remove the "seed" field and declare it as a local variable in the relevant methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1450)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 11]
```diff
@@ -0,0 +1,467 @@
...
+        this.location = location;
+
+        this.inventory = inventory;
+
+        addSlotToContainer(new Slot(inventory, 0, 80, 34));
+
+        //Ddd player inventory slots
+        // Note: The slot numbers are within the player inventory and may be the same as the field inventory.
+        int i;
+        for (i = 0; i < 3; ++i)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 12]
```diff
@@ -0,0 +1,467 @@
...
+    /**
+     * Getter for MAX_RANGE.
+     * @return the max range.
+     */
+    public int getMaxRange()
+    {
+        return MAX_RANGE;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 13]
```diff
@@ -0,0 +1,467 @@
...
+        this.inventory = inventory;
+
+        addSlotToContainer(new Slot(inventory, 0, 80, 34));
+
+        //Ddd player inventory slots
+        // Note: The slot numbers are within the player inventory and may be the same as the field inventory.
+        int i;
+        for (i = 0; i < 3; ++i)
+        {
+            for (int j = 0; j < 9; ++j)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Assign this magic number 9 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 14]
```diff
@@ -0,0 +1,467 @@
...
+            {
+                addSlotToContainer(new Slot(playerInventory, j+i*9+9,
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)
MINOR Assign this magic number 9 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
MINOR Assign this magic number 9 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 15]
```diff
@@ -0,0 +1,467 @@
...
+                                            8+j*18, 84+i*18));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Assign this magic number 8 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
MINOR Assign this magic number 18 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
MINOR Assign this magic number 84 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
MINOR Assign this magic number 18 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 16]
```diff
@@ -0,0 +1,467 @@
...
+     *
+     * @return          {@link BlockPos} of the current object
+     */
+    public BlockPos getID()
+    {
+        // Location doubles as ID
+        return this.location;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 17]
```diff
@@ -0,0 +1,467 @@
...
+        return MAX_RANGE;
+    }
+
+    /**
+     * Getter of the seed of the field
+     * @return the ItemSeed
+     */
+    public Item getSeed()
+    {
+        //todo update seed @farmer
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 18]
```diff
@@ -0,0 +1,467 @@
...
+        if(inventory.getStackInSlot(0) == null || !(inventory.getStackInSlot(0).getItem()  instanceof IPlantable))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR No need to check for null before an instanceof [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ASimplifyConditional)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 19]
```diff
@@ -0,0 +1,467 @@
...
+        widthMinusZ = compound.getInteger(TAG_WIDTH_MINUS);
+        inventory = new InventoryField("Scarecrow", true);
+        inventory.readFromNBT(compound);
+    }
+
+    /**
+     * Has the field been taken?
+     * @return true if the field is not free to use, false after releasing it.
+     */
+    public boolean isTaken() {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 20]
```diff
@@ -0,0 +1,467 @@
...
+        for (i = 0; i < 3; ++i)
+        {
+            for (int j = 0; j < 9; ++j)
+            {
+                addSlotToContainer(new Slot(playerInventory, j+i*9+9,
+                                            8+j*18, 84+i*18));
+            }
+        }
+
+        for (i = 0; i < 9; ++i)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Assign this magic number 9 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 21]
```diff
@@ -0,0 +1,467 @@
...
+        {
+            addSlotToContainer(new Slot(playerInventory, i, 8 + i * 18,
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)
MINOR Assign this magic number 8 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
MINOR Assign this magic number 18 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 22]
```diff
@@ -0,0 +1,467 @@
...
+                                        142));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Assign this magic number 142 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 23]
```diff
@@ -0,0 +1,467 @@
...
+        }
+        calculateSize(world,location.down());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "calculateSize" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 24]
```diff
@@ -0,0 +1,467 @@
...
+     */
+    public boolean isTaken() {
+        return this.taken;
+    }
+
+    /**
+     * Sets the field taken.
+     * @param taken is field free or not
+     */
+    public void setTaken(boolean taken) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 25]
```diff
@@ -0,0 +1,467 @@
...
+     * Returns the colony of the field
+     *
+     * @return          {@link com.minecolonies.colony.Colony} of the current object
+     */
+    public Colony getColony()
+    {
+        return this.colony;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 26]
```diff
@@ -0,0 +1,467 @@
...
+     * Create and load a Field given it's saved NBTTagCompound
+     *
+     * @param colony    The owning colony
+     * @param compound  The saved data
+     * @return          {@link com.minecolonies.colony.Field} created from the compound.
+     */
+    public static Field createFromNBT(Colony colony, NBTTagCompound compound)
+    {
+        Field field = new Field(colony);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 27]
```diff
@@ -0,0 +1,467 @@
...
+    public ItemStack transferStackInSlot(EntityPlayer playerIn, int slotIndex)
+    {
+        if (slotIndex == 0)
+        {
+            playerIn.inventory.addItemStackToInventory(inventory.getStackInSlot(0));
+            inventory.setInventorySlotContents(0, null);
+        }
+        else if(inventory.getStackInSlot(0) == null)
+        {
+            int playerIndex = slotIndex < 28 ? (slotIndex + 8) : (slotIndex - 28);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Assign this magic number 28 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
MINOR Assign this magic number 8 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
MINOR Assign this magic number 28 to a well-named constant, and use the constant instead. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
MINOR Local variable 'playerIndex' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/GuiHandler.java [hunk 28]
```diff
@@ -0,0 +1,34 @@
...
+/**
+ * Class which handles the GUI inventory.
+ */
+@SideOnly(Side.CLIENT)
+public class GuiHandler implements IGuiHandler
+{
+    @Override
+    public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z)
+    {
+        BlockPos            pos        = new BlockPos(x,y,z);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiHandler.java]: MINOR Local variable 'pos' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/GuiHandler.java [hunk 29]
```diff
@@ -0,0 +1,34 @@
...
+        ScarecrowTileEntity tileEntity = (ScarecrowTileEntity) world.getTileEntity(pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiHandler.java]: MINOR Local variable 'tileEntity' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 30]
```diff
@@ -0,0 +1,507 @@
...
+        addSlotToContainer(new Slot(inventory, 0, X_OFFSET, Y_OFFSET));
+
+        //Ddd player inventory slots
+        // Note: The slot numbers are within the player inventory and may be the same as the field inventory.
+        int i;
+        for (i = 0; i < PLAYER_INVENTORY_ROWS; ++i)
+        {
+            for (int j = 0; j < PLAYER_INVENTORY_COLUMNS; ++j)
+            {
+                addSlotToContainer(new Slot(playerInventory, j + i * PLAYER_INVENTORY_COLUMNS + PLAYER_INVENTORY_COLUMNS,
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 31]
```diff
@@ -0,0 +1,507 @@
...
+        return MAX_RANGE;
+    }
+
+    /**
+     * Getter of the seed of the field
+     * @return the ItemSeed
+     */
+    public Item getSeed()
+    {
+        if(inventory.getStackInSlot(0) == null || !(inventory.getStackInSlot(0).getItem()  instanceof IPlantable))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR No need to check for null before an instanceof [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ASimplifyConditional)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 32]
```diff
@@ -0,0 +1,507 @@
...
+     */
+    public Field(InventoryField inventory, InventoryPlayer playerInventory, World world, BlockPos location)
+    {
+        super();
+        this.colony = ColonyManager.getColony(world,location);
+        this.location = location;
+
+        this.inventory = inventory;
+
+        addSlotToContainer(new Slot(inventory, 0, X_OFFSET, Y_OFFSET));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 33]
```diff
@@ -0,0 +1,507 @@
...
+            for (int j = 0; j < PLAYER_INVENTORY_COLUMNS; ++j)
+            {
+                addSlotToContainer(new Slot(playerInventory, j + i * PLAYER_INVENTORY_COLUMNS + PLAYER_INVENTORY_COLUMNS,
+                                            PLAYER_INVENTORY_INITIAL_X_OFFSET+j*PLAYER_INVENTORY_OFFSET_EACH, PLAYER_INVENTORY_INITIAL_Y_OFFSET+i*PLAYER_INVENTORY_OFFSET_EACH));
+            }
+        }
+
+        for (i = 0; i < PLAYER_INVENTORY_COLUMNS; ++i)
+        {
+            addSlotToContainer(new Slot(playerInventory, i, PLAYER_INVENTORY_INITIAL_X_OFFSET + i * PLAYER_INVENTORY_OFFSET_EACH,
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 34]
```diff
@@ -0,0 +1,507 @@
...
+                                        PLAYER_INVENTORY_HOTBAR_OFFSET));
+        }
+        calculateSize(world,location.down());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "calculateSize" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 35]
```diff
@@ -0,0 +1,507 @@
...
+    public ItemStack transferStackInSlot(EntityPlayer playerIn, int slotIndex)
+    {
+        if (slotIndex == 0)
+        {
+            playerIn.inventory.addItemStackToInventory(inventory.getStackInSlot(0));
+            inventory.setInventorySlotContents(0, null);
+        }
+        else if(inventory.getStackInSlot(0) == null)
+        {
+            int playerIndex = slotIndex < MAX_INVENTORY_INDEX ? (slotIndex + INVENTORY_BAR_SIZE) : (slotIndex - MAX_INVENTORY_INDEX);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Local variable 'playerIndex' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/GuiHandler.java [hunk 36]
```diff
@@ -0,0 +1,34 @@
...
+        return new Field(tileEntity.inventoryField, player.inventory, world, pos);
+    }
+
+    @Override
+    public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z)
+    {
+        BlockPos            pos        = new BlockPos(x,y,z);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiHandler.java]: MINOR Local variable 'pos' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/GuiHandler.java [hunk 37]
```diff
@@ -0,0 +1,34 @@
...
+        ScarecrowTileEntity tileEntity = (ScarecrowTileEntity) world.getTileEntity(pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiHandler.java]: MINOR Local variable 'tileEntity' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 38]
```diff
@@ -4,131 +4,260 @@
...
-                carrot = 0,
-                melon = 0,
-                pumpkin = 0;
+        if(!farmerFields.isEmpty())
+        {
+            ArrayList<Field> tempFields = new ArrayList<>(farmerFields);
 
+            for(Field field: tempFields)
+            {
+                ScarecrowTileEntity scarecrow = (ScarecrowTileEntity) world.getTileEntity(field.getID());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'scarecrow' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 39]
```diff
@@ -4,131 +4,260 @@
...
-    private static final    String  TAG_FARMER  = "farmer";
+    /**
+     * NBTTag to store the currentField.
+     */
+    private static final String TAG_CURRENT_FIELD = "currentField";
+
+    /**
+     * The list of the fields the farmer manages.
+     */
+    private ArrayList<Field> farmerFields = new ArrayList<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MAJOR Private field 'farmerFields' could be made final; it is only initialized in the declaration or constructor. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AImmutableField)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 40]
```diff
@@ -4,131 +4,260 @@
...
+            field.calculateSize(getColony().getWorld(), field.getLocation().down());
         }
+    }
 
-        public com.blockout.views.Window getWindow()
+    @Override
+    public void onDestroyed()
+    {
+        super.onDestroyed();
+        for(Field field: farmerFields)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 41]
```diff
@@ -4,131 +4,260 @@
...
-            potato = buf.readInt();
-            carrot = buf.readInt();
-            melon = buf.readInt();
-            pumpkin = buf.readInt();
+    //we have to update our field from the colony!
+    @Override
+    public void readFromNBT(NBTTagCompound compound)
+    {
+        super.readFromNBT(compound);
+        NBTTagList fieldTagList = compound.getTagList(TAG_FIELDS, Constants.NBT.TAG_COMPOUND);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'fieldTagList' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 42]
```diff
@@ -4,131 +4,260 @@
...
     {
-        super.serializeToView(buf);
-
-        buf.writeInt(wheat);
-        buf.writeInt(potato);
-        buf.writeInt(carrot);
-        buf.writeInt(melon);
-        buf.writeInt(pumpkin);
+        super.writeToNBT(compound);
+        NBTTagList fieldTagList = new NBTTagList();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'fieldTagList' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 43]
```diff
@@ -4,131 +4,260 @@
...
+        for (Field f : farmerFields)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'f' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 44]
```diff
@@ -4,131 +4,260 @@
...
-            pumpkin = buf.readInt();
+    //we have to update our field from the colony!
+    @Override
+    public void readFromNBT(NBTTagCompound compound)
+    {
+        super.readFromNBT(compound);
+        NBTTagList fieldTagList = compound.getTagList(TAG_FIELDS, Constants.NBT.TAG_COMPOUND);
+        for (int i = 0; i < fieldTagList.tagCount(); ++i)
+        {
+            NBTTagCompound fieldCompound = fieldTagList.getCompoundTagAt(i);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'fieldCompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 45]
```diff
@@ -4,131 +4,260 @@
...
-        buf.writeInt(wheat);
-        buf.writeInt(potato);
-        buf.writeInt(carrot);
-        buf.writeInt(melon);
-        buf.writeInt(pumpkin);
+        super.writeToNBT(compound);
+        NBTTagList fieldTagList = new NBTTagList();
+        for (Field f : farmerFields)
+        {
+            NBTTagCompound fieldCompound = new NBTTagCompound();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'fieldCompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 46]
```diff
@@ -4,131 +4,260 @@
...
+        }
+    }
 
-        public View(ColonyView c, BlockPos l)
+    /**
+     * Resets the fields to need work again.
+     */
+    public void resetFields()
+    {
+        for(Field field: farmerFields)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 47]
```diff
@@ -4,131 +4,260 @@
...
+    //we have to update our field from the colony!
+    @Override
+    public void readFromNBT(NBTTagCompound compound)
+    {
+        super.readFromNBT(compound);
+        NBTTagList fieldTagList = compound.getTagList(TAG_FIELDS, Constants.NBT.TAG_COMPOUND);
+        for (int i = 0; i < fieldTagList.tagCount(); ++i)
+        {
+            NBTTagCompound fieldCompound = fieldTagList.getCompoundTagAt(i);
+            Field f = Field.createFromNBT(getColony(), fieldCompound);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'f' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 48]
```diff
@@ -4,131 +4,260 @@
...
-        public int wheat = 100,
-                potato = 0,
-                carrot = 0,
-                melon = 0,
-                pumpkin = 0;
+        if(!farmerFields.isEmpty())
+        {
+            ArrayList<Field> tempFields = new ArrayList<>(farmerFields);
 
+            for(Field field: tempFields)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 49]
```diff
@@ -13,6 +25,30 @@ protected BlockHutFarmer()
...
+    {
+        /*
+        Only work on server side
+        */
+        if(worldIn.isRemote)
+        {
+            return;
+        }
+
+        TileEntity tileEntity = worldIn.getTileEntity(pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Local variable 'tileEntity' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 50]
```diff
@@ -13,6 +25,30 @@ protected BlockHutFarmer()
...
+        if(placer instanceof EntityPlayer && tileEntity instanceof TileEntityColonyBuilding)
+        {
+            TileEntityColonyBuilding hut = (TileEntityColonyBuilding) tileEntity;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Local variable 'hut' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 51]
```diff
@@ -13,6 +25,30 @@ protected BlockHutFarmer()
...
+            Colony colony = ColonyManager.getColony(worldIn, hut.getPosition());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/entity/ai/util/AIState.java [hunk 52]
```diff
@@ -160,4 +162,27 @@
...
+     * Check if the fields need any work
+     */
+    FARMER_CHECK_FIELDS,
+
+    /**
+     * Hoe the field.
+     */
+    FARMER_HOE,
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/util/AIState.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/entity/ai/util/AIState.java [hunk 53]
```diff
@@ -160,4 +162,27 @@
      */
     BUILDER_COMPLETE_BUILD,
 
+    /*
+###FARMER###
+    */
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/util/AIState.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/entity/EntityCitizen.java [hunk 54]
```diff
@@ -4,8 +4,10 @@
 import com.minecolonies.client.render.RenderBipedCitizen;
 import com.minecolonies.colony.*;
 import com.minecolonies.colony.buildings.AbstractBuildingWorker;
+import com.minecolonies.colony.buildings.BuildingFarmer;
 import com.minecolonies.colony.buildings.BuildingHome;
 import com.minecolonies.colony.jobs.AbstractJob;
+import com.minecolonies.colony.jobs.JobFarmer;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/EntityCitizen.java]: MINOR Remove this unused import 'com.minecolonies.colony.jobs.JobFarmer'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 55]
```diff
@@ -0,0 +1,177 @@
...
+    }
+
+    /**
+     * Used to retrieve variables.
+     * @param compound with the give tag.
+     */
+    @Override
+    public void readFromNBT(NBTTagCompound compound)
+    {
+        NBTTagList nbttaglist = compound.getTagList(TAG_ITEMS, Constants.NBT.TAG_COMPOUND);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MINOR Local variable 'nbttaglist' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 56]
```diff
@@ -0,0 +1,177 @@
...
+    @Override
+    public void writeToNBT(NBTTagCompound compound)
+    {
+        NBTTagList nbttaglist = new NBTTagList();
+
+        for (int i = 0; i < this.stackResult.length; ++i)
+        {
+            if (this.stackResult[i] != null)
+            {
+                NBTTagCompound nbttagcompound = new NBTTagCompound();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MINOR Local variable 'nbttagcompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 57]
```diff
@@ -0,0 +1,177 @@
...
+    {
+        return 0;
+    }
+
+    /**
+     * Getter for the stack in the inventory. Since there is only one slot return always that one.
+     * @param index the slot.
+     * @return the itemStack in it.
+     */
+    public ItemStack getStackInSlot(int index)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MAJOR Add the "@Override" annotation above this method signature [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 58]
```diff
@@ -0,0 +1,177 @@
...
+     */
+    @Override
+    public void readFromNBT(NBTTagCompound compound)
+    {
+        NBTTagList nbttaglist = compound.getTagList(TAG_ITEMS, Constants.NBT.TAG_COMPOUND);
+        this.stackResult = new ItemStack[this.getSizeInventory()];
+
+        for (int i = 0; i < nbttaglist.tagCount(); ++i)
+        {
+            NBTTagCompound nbttagcompound = nbttaglist.getCompoundTagAt(i);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MINOR Local variable 'nbttagcompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 59]
```diff
@@ -0,0 +1,177 @@
...
+            int            j              = nbttagcompound.getByte(TAG_SLOT) & Byte.MAX_VALUE;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MINOR Local variable 'j' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 60]
```diff
@@ -0,0 +1,177 @@
...
+    }
+
+    /**
+     * Used to store variables.
+     * @param compound with the given tag.
+     */
+    @Override
+    public void writeToNBT(NBTTagCompound compound)
+    {
+        NBTTagList nbttaglist = new NBTTagList();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MINOR Local variable 'nbttaglist' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 61]
```diff
@@ -0,0 +1,91 @@
...
+    public enum ScareCrowType
+    {
+        PUMPKINHEAD,
+        NORMAL
+    }
+
+    /**
+     * Empty public constructor.
+     */
+    public ScarecrowTileEntity()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MINOR It is a good practice to call super() in a constructor [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ACallSuperInConstructor)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 62]
```diff
@@ -0,0 +1,91 @@
...
+
+    /**
+     * Random generator.
+     */
+    private final Random random = new Random();
+
+    /**
+     * The type of the scarecrow.
+     */
+    private ScareCrowType TYPE;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MINOR Rename this field "TYPE" to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00116)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 63]
```diff
@@ -0,0 +1,91 @@
...
+    /**
+     * NBTTag to store the type.
+     */
+    private static final String TAG_TYPE = "type";
+
+    /**
+     * The name of the inventory which shows up when opened.
+     */
+    private static final String INVENTORY_NAME = "Scarecrow";
+    //todo change to .lang term
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 64]
```diff
@@ -0,0 +1,91 @@
...
+
+    /**
+     * The inventory connected with the scarecrow.
+     */
+    public InventoryField inventoryField;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MAJOR Make inventoryField a static final constant or non-public and provide accessors if needed. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

File: src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java [hunk 65]
```diff
@@ -0,0 +1,104 @@
...
+        //Restore the transformation, so other renderer's are not messed up.
+        GlStateManager.popMatrix();
+    }
+
+    /**
+     * Returns the ResourceLocation of the scarecrow texture.
+     * @param tileEntity the tileEntity of the scarecrow.
+     * @return the location.
+     */
+    private ResourceLocation getResourceLocation(ScarecrowTileEntity tileEntity)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java]: MINOR Make "getResourceLocation" a "static" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2325)

File: src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java [hunk 66]
```diff
@@ -0,0 +1,104 @@
...
+    /**
+     * Rotate it on the following z offset.
+     */
+    private static final double ZROTATIONOFFSET = 2.845;
+
+
+    /**
+     * The public constructor for the renderer.
+     */
+    public TileEntityScarecrowRenderer() {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR It is a good practice to call super() in a constructor [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ACallSuperInConstructor)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 67]
```diff
@@ -770,11 +801,40 @@ public boolean hasTownHall()
...
+            if(!field.isTaken())
+            {
+                field.setTaken(true);
+                return field;
+            }
+        }
+        return null;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 68]
```diff
@@ -770,11 +801,40 @@ public boolean hasTownHall()
         return townHall != null;
     }
 
+
     /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 69]
```diff
@@ -820,7 +880,31 @@ private void addBuilding(AbstractBuilding building)
...
+    /**
+     * Creates a field from a tile entity and adds it to the colony.
+     * @param inventoryField the inventory of the field.
+     * @param inventoryPlayer the inventory of the player.
+     * @param pos Position where the field has been placed.
+     * @param world the world of the field.
+     */
+    public void addNewField(InventoryField inventoryField, InventoryPlayer inventoryPlayer, BlockPos pos, World world)
+    {
+        Field field = new Field(inventoryField, inventoryPlayer, world, pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 70]
```diff
@@ -160,6 +163,19 @@ private void readFromNBT(NBTTagCompound compound)
             }
         }
 
+        //todo update fields from tileEntity.
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 71]
```diff
@@ -160,6 +163,19 @@ private void readFromNBT(NBTTagCompound compound)
...
+        // Fields
+        NBTTagList fieldTagList = compound.getTagList(TAG_FIELDS, NBT.TAG_COMPOUND);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'fieldTagList' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 72]
```diff
@@ -820,7 +880,31 @@ private void addBuilding(AbstractBuilding building)
...
+     * @param world the world of the field.
+     */
+    public void addNewField(InventoryField inventoryField, InventoryPlayer inventoryPlayer, BlockPos pos, World world)
+    {
+        Field field = new Field(inventoryField, inventoryPlayer, world, pos);
+        addField(field);
+        ColonyManager.markDirty();
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 73]
```diff
@@ -160,6 +163,19 @@ private void readFromNBT(NBTTagCompound compound)
             }
         }
 
+        //todo update fields from tileEntity.
+        // Fields
+        NBTTagList fieldTagList = compound.getTagList(TAG_FIELDS, NBT.TAG_COMPOUND);
+        for (int i = 0; i < fieldTagList.tagCount(); ++i)
+        {
+            NBTTagCompound      fieldCompound = fieldTagList.getCompoundTagAt(i);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'fieldCompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 74]
```diff
@@ -160,6 +163,19 @@ private void readFromNBT(NBTTagCompound compound)
...
+            Field               f             = Field.createFromNBT(this, fieldCompound);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'f' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 75]
```diff
@@ -655,6 +681,12 @@ private void cleanUpBuildings(TickEvent.WorldTickEvent event)
         {
             removedBuildings.forEach(AbstractBuilding::destroy);
         }
+
+        List<BlockPos> removedFields = fields.keySet().stream().filter(loc -> world.getTileEntity(loc) == null).collect(Collectors.toList());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'removedFields' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 76]
```diff
@@ -655,6 +681,12 @@ private void cleanUpBuildings(TickEvent.WorldTickEvent event)
...
+        for(BlockPos field: removedFields)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 77]
```diff
@@ -770,11 +801,40 @@ public boolean hasTownHall()
...
+        return fields.get(fieldId);
+    }
+
+    /**
+     * Returns a field which has not been taken yet.
+     * @return a field if there is one available, else null.
+     */
+    public Field getFreeField()
+    {
+        for(Field field: fields.values())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 78]
```diff
@@ -195,6 +211,16 @@ protected void writeToNBT(NBTTagCompound compound)
         }
         compound.setTag(TAG_BUILDINGS, buildingTagList);
 
+        // Fields
+        NBTTagList fieldTagList = new NBTTagList();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'fieldTagList' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 79]
```diff
@@ -195,6 +211,16 @@ protected void writeToNBT(NBTTagCompound compound)
...
+        for (Field f : fields.values())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'f' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 80]
```diff
@@ -195,6 +211,16 @@ protected void writeToNBT(NBTTagCompound compound)
...
+        {
+            NBTTagCompound fieldCompound = new NBTTagCompound();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'fieldCompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 81]
```diff
@@ -55,8 +57,9 @@
     //private int autoHostile = 0;//Off
 
     //  Buildings
-    private BuildingTownHall townHall;
-    private Map<BlockPos, AbstractBuilding> buildings = new HashMap<>();
+    private BuildingTownHall                                townHall;
+    private                 Map<BlockPos, AbstractBuilding>         buildings                       = new HashMap<>();
+    private                 Map<BlockPos, Field>            fields                          = new HashMap<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Private field 'fields' could be made final; it is only initialized in the declaration or constructor. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AImmutableField)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java [hunk 82]
```diff
@@ -1,647 +1,560 @@
...
+        return PREPARING;
     }
 
-    private boolean hasSeed()
+    /**
+     * Prepares the farmer for farming and
+     * requests the tools and checks if the farmer has sufficient fields.
+     * @return the next AIState
+     */
+    private AIState prepareForFarming()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java]: MAJOR Reduce the number of returns of this method 7, down to the maximum allowed 5. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1142)
MAJOR The Cyclomatic Complexity of this method "prepareForFarming" is 22 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java [hunk 83]
```diff
@@ -1,647 +1,560 @@
...
-    private int delay = 0;
-
-    //TODO Check for duplicates
-    public EntityAIWorkFarmer(JobFarmer job)
-    {
-        super(job);
-    }
-    //TODO Planting randomly depending on option in Hut, each level, one more crop type
-    //TODO Adding Language Strings in files
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java [hunk 84]
```diff
@@ -1,647 +1,560 @@
...
-                    }
-                }
+                getOwnBuilding().addFarmerFields(newField);
             }
-            job.setStage(Stage.WORKING);
         }
     }
 
-    private static boolean isStackTool(ItemStack stack)
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java [hunk 85]
```diff
@@ -1,647 +1,560 @@
...
 import com.minecolonies.colony.jobs.JobFarmer;
+import com.minecolonies.entity.EntityCitizen;
 import com.minecolonies.entity.ai.basic.AbstractEntityAIInteract;
-import com.minecolonies.util.BlockPosUtil;
+import com.minecolonies.entity.ai.util.AIState;
+import com.minecolonies.entity.ai.util.AITarget;
+import com.minecolonies.util.BlockUtils;
 import com.minecolonies.util.InventoryUtils;
-import net.minecraft.block.Block;
+import net.minecraft.block.BlockCarrot;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java]: MINOR Remove this unused import 'net.minecraft.block.BlockCarrot'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 86]
```diff
@@ -55,8 +57,9 @@
     //private int autoHostile = 0;//Off
 
     //  Buildings
-    private BuildingTownHall townHall;
-    private Map<BlockPos, AbstractBuilding> buildings = new HashMap<>();
+    private BuildingTownHall                                townHall;
+    private                 Map<BlockPos, AbstractBuilding>         buildings                       = new HashMap<>();
+    final private                 Map<BlockPos, Field>            fields                          = new HashMap<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Reorder the modifiers to comply with the Java Language Specification. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AModifiersOrderCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 87]
```diff
@@ -0,0 +1,239 @@
...
+    {
+        super.onBlockDestroyedByPlayer(worldIn, pos, state);
+        //Only work on server side.
+        if(worldIn.isRemote)
+        {
+            return;
+        }
+
+
+        Colony colony = ColonyManager.getColony(worldIn, pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 88]
```diff
@@ -0,0 +1,239 @@
...
+        initBlock();
+    }
+
+    /**
+     * Getter of the description of the blockHut.
+     * @return the name as a String.
+     */
+    public String getName()
+    {
+        return "blockHutField";
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MAJOR Remove this method and declare a constant for this value. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS3400)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 89]
```diff
@@ -0,0 +1,239 @@
...
+            return;
+        }
+
+        if(placer instanceof EntityPlayer)
+        {
+            Colony colony = ColonyManager.getColony(worldIn, pos);
+
+            if (colony != null)
+            {
+                InventoryField inventoryField = new InventoryField(LanguageHandler.getString("com.minecolonies.gui.inventory.scarecrow"), true);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Local variable 'inventoryField' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 90]
```diff
@@ -0,0 +1,239 @@
...
+        return true;
+    }
+
+    // =======================================================================
+    // ======================= Rendering & IBlockState =======================
+    // =======================================================================
+    @Override
+    public IBlockState onBlockPlaced(World worldIn, BlockPos pos, EnumFacing facing, float hitX, float hitY, float hitZ, int meta, EntityLivingBase placer)
+    {
+        EnumFacing enumFacing = (placer == null) ? EnumFacing.NORTH : EnumFacing.fromAngle(placer.rotationYaw);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Local variable 'enumFacing' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 91]
```diff
@@ -0,0 +1,239 @@
...
+        return -1;
+    }
+
+    @Override
+    public boolean onBlockActivated(World worldIn, BlockPos pos, IBlockState state, EntityPlayer playerIn, EnumFacing side, float hitX, float hitY, float hitZ)
+    {
+        //If the world is server, open the inventory of the field.
+        if(!worldIn.isRemote)
+        {
+            Colony colony = ColonyManager.getColony(worldIn, pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 92]
```diff
@@ -0,0 +1,239 @@
...
+    {
+        //Only work on server side.
+        if(worldIn.isRemote)
+        {
+            return;
+        }
+
+        if(placer instanceof EntityPlayer)
+        {
+            Colony colony = ColonyManager.getColony(worldIn, pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/network/messages/OpenInventoryMessage.java [hunk 93]
```diff
@@ -96,15 +156,27 @@ public IMessage onMessage(OpenInventoryMessage message, MessageContext ctx)
             case INVENTORY_CITIZEN:
                 InventoryCitizen citizenInventory = ((EntityCitizen) player.worldObj.getEntityByID(message.entityID)).getInventoryCitizen();
                 if(!StringUtils.isNullOrEmpty(message.name))
-                    citizenInventory.setCustomName(message.name);   //SetInventoryName
+                {
+                    citizenInventory.setCustomName(message.name);
+                }
                 player.displayGUIChest(citizenInventory);
                 break;
             case INVENTORY_CHEST:
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/OpenInventoryMessage.java]: MAJOR Reduce this switch case number of lines from 7 to at most 5, for example by extracting code into methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1151)

File: src/main/java/com/minecolonies/network/messages/OpenInventoryMessage.java [hunk 94]
```diff
@@ -96,15 +156,27 @@ public IMessage onMessage(OpenInventoryMessage message, MessageContext ctx)
             case INVENTORY_CITIZEN:
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/OpenInventoryMessage.java]: MAJOR Reduce this switch case number of lines from 7 to at most 5, for example by extracting code into methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1151)

File: src/main/java/com/minecolonies/network/messages/OpenInventoryMessage.java [hunk 95]
```diff
@@ -96,15 +156,27 @@ public IMessage onMessage(OpenInventoryMessage message, MessageContext ctx)
...
             case INVENTORY_CHEST:
                 TileEntityChest chest = (TileEntityChest) BlockPosUtil.getTileEntity(player.worldObj, message.tePos);
                 if(!StringUtils.isNullOrEmpty(message.name))
-                    chest.setCustomName(message.name);              //SetInventoryName
+                {
+                    chest.setCustomName(message.name);
+                }
                 player.displayGUIChest(chest);
                 break;
+            case INVENTORY_FIELD:
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/OpenInventoryMessage.java]: MAJOR Reduce this switch case number of lines from 7 to at most 5, for example by extracting code into methods. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1151)

File: src/main/java/com/minecolonies/network/messages/OpenInventoryMessage.java [hunk 96]
```diff
@@ -96,15 +156,27 @@ public IMessage onMessage(OpenInventoryMessage message, MessageContext ctx)
...
+                InventoryField inventoryField = ColonyManager.getColony(colonyId).getField(message.tePos).getInventoryField();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/OpenInventoryMessage.java]: MINOR Local variable 'inventoryField' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/BlockUtils.java [hunk 97]
```diff
@@ -179,7 +179,7 @@ else if(blockState.getBlock() instanceof BlockDaylightDetector)
         }
         else if (blockState.getBlock() instanceof BlockDoor)
         {
-            return ((BlockDoor) blockState.getBlock()).getItem();
+            //return ((BlockDoor) blockState.getBlock()).getItem();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/BlockUtils.java]: MAJOR This block of commented-out lines of code should be removed. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/com/minecolonies/util/BlockUtils.java [hunk 98]
```diff
@@ -243,7 +243,7 @@ else if (blockState.getBlock() instanceof BlockSkull)
         }
         else if (blockState.getBlock() instanceof BlockStem)
         {
-            return ((BlockStem) blockState.getBlock()).getSeedItem();
+            //return ((BlockStem) blockState.getBlock()).getSeedItem();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/BlockUtils.java]: MAJOR This block of commented-out lines of code should be removed. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

File: src/main/java/com/minecolonies/proxy/ClientProxy.java [hunk 99]
```diff
@@ -93,6 +98,7 @@ public void registerRenderer()
     	Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(ModBlocks.blockHutTownHall), 0, new ModelResourceLocation(ModBlocks.blockHutTownHall.getRegistryName(), "inventory"));
     	Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(ModBlocks.blockHutWarehouse), 0, new ModelResourceLocation(ModBlocks.blockHutWarehouse.getRegistryName(), "inventory"));
     	Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(ModBlocks.blockSubstitution), 0, new ModelResourceLocation(ModBlocks.blockSubstitution.getRegistryName(), "inventory"));
+        Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(ModBlocks.blockHutField), 0, new ModelResourceLocation(ModBlocks.blockHutField.getRegistryName(), "inventory"));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/proxy/ClientProxy.java]: MINOR Split this 213 characters long line (which is greater than 180 authorized). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/proxy/ClientProxy.java [hunk 100]
```diff
@@ -6,11 +6,14 @@
 import com.minecolonies.client.render.EmptyTileEntitySpecialRenderer;
 import com.minecolonies.client.render.RenderBipedCitizen;
 import com.minecolonies.client.render.RenderFishHook;
+import com.minecolonies.client.render.TileEntityScarecrowRenderer;
+import com.minecolonies.colony.CitizenData;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/proxy/ClientProxy.java]: MINOR Remove this unused import 'com.minecolonies.colony.CitizenData'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/proxy/ClientProxy.java [hunk 101]
```diff
@@ -20,6 +23,7 @@
 import net.minecraft.client.resources.model.ModelResourceLocation;
 import net.minecraft.item.Item;
 import net.minecraft.util.BlockPos;
+import net.minecraftforge.client.ForgeHooksClient;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/proxy/ClientProxy.java]: MINOR Remove this unused import 'net.minecraftforge.client.ForgeHooksClient'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/network/messages/FarmerCropTypeMessage.java [hunk 102]
```diff
@@ -85,11 +79,7 @@ public IMessage onMessage(FarmerCropTypeMessage message, MessageContext ctx)
                 BuildingFarmer building = colony.getBuilding(message.buildingId, BuildingFarmer.class);
                 if (building != null)
                 {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/FarmerCropTypeMessage.java]: MAJOR Either remove or fill this block of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00108)

File: src/main/java/com/minecolonies/util/SchematicWrapper.java [hunk 103]
```diff
@@ -8,9 +8,11 @@
 import com.schematica.world.storage.Schematic;
 import net.minecraft.block.Block;
 import net.minecraft.block.BlockDoor;
+import net.minecraft.block.BlockPlanks;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/SchematicWrapper.java]: MINOR Remove this unused import 'net.minecraft.block.BlockPlanks'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/util/SchematicWrapper.java [hunk 104]
```diff
@@ -8,9 +8,11 @@
...
 import net.minecraft.block.BlockStairs;
 import net.minecraft.block.state.IBlockState;
 import net.minecraft.client.Minecraft;
+import net.minecraft.client.renderer.block.model.ModelBlockDefinition;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/SchematicWrapper.java]: MINOR Remove this unused import 'net.minecraft.client.renderer.block.model.ModelBlockDefinition'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 105]
```diff
@@ -264,7 +81,6 @@ private void nextClicked(Button ignored)
     public void onButtonClicked(Button button)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Remove this method to simply inherit it. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1185)

File: src/main/java/com/minecolonies/inventory/GuiField.java [hunk 106]
```diff
@@ -0,0 +1,53 @@
...
+    private static final ResourceLocation TEXTURE = new ResourceLocation(Constants.MOD_ID, "textures/gui/scarecrow.png");
+
+    /**
+     * Constructor of the GUI.
+     * @param parInventoryPlayer the player inventory.
+     * @param fieldInventory the field inventory.
+     * @param world the world the field is in.
+     * @param location the location the field is at.
+     */
+    protected GuiField(InventoryPlayer parInventoryPlayer, IInventory fieldInventory, World world, BlockPos location)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiField.java]: MINOR It is a good practice to call super() in a constructor [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ACallSuperInConstructor)

File: src/main/java/com/minecolonies/inventory/GuiField.java [hunk 107]
```diff
@@ -0,0 +1,53 @@
...
+     * @param partialTicks the ticks delivered.
+     * @param mouseX the mouseX position.
+     * @param mouseY the mouseY position.
+     */
+    @Override
+    protected void drawGuiContainerBackgroundLayer(float partialTicks, int mouseX, int mouseY)
+    {
+        GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
+        mc.getTextureManager().bindTexture(TEXTURE);
+        int marginHorizontal = (width - xSize) / 2;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiField.java]: MINOR Local variable 'marginHorizontal' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/GuiField.java [hunk 108]
```diff
@@ -0,0 +1,53 @@
...
+        int marginVertical   = (height - ySize) / 2;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiField.java]: MINOR Local variable 'marginVertical' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/entity/pathfinding/AbstractPathJob.java [hunk 109]
```diff
@@ -895,7 +913,8 @@ protected boolean isWalkableSurface(Block block, BlockPos pos)
         return block.getMaterial().isSolid() &&
                 !(block instanceof BlockFence) &&
                 !(block instanceof BlockFenceGate) &&
-                !(block instanceof BlockWall);
+                !(block instanceof BlockWall) &&
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/pathfinding/AbstractPathJob.java]: MINOR '&&' should be on a new line. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AOperator_Wrap)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 34 issues
* MAJOR 14 major
* MINOR 20 minor

Watch the comments in this conversation to review them.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 33 issues
* MAJOR 14 major
* MINOR 19 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java (hunk 82 above)
Comment (Kostronor) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java]: I agree with sonar, this can be split up into small logically distinct parts

File: src/main/java/com/minecolonies/colony/Field.java [hunk 110]
```diff
@@ -0,0 +1,541 @@
...
+
+        for (i = 0; i < PLAYER_INVENTORY_COLUMNS; i++)
+        {
+            addSlotToContainer(new Slot(
+                    playerInventory, i,
+                    PLAYER_INVENTORY_INITIAL_X_OFFSET + i * PLAYER_INVENTORY_OFFSET_EACH,
+                    PLAYER_INVENTORY_HOTBAR_OFFSET
+            ));
+        }
+        calculateSize(world, location.down());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "calculateSize" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 111]
```diff
@@ -0,0 +1,541 @@
...
+        return MAX_RANGE;
+    }
+
+    /**
+     * Adds an item slot to this container
+     * <p>
+     * Overridden to protect it from getting changed.
+     */
+    @Override
+    protected final Slot addSlotToContainer(final Slot slotIn)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MINOR Remove this method to simply inherit it. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1185)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 112]
```diff
@@ -0,0 +1,100 @@
...
+     */
+    private ScareCrowType  type;
+
+    /**
+     * Empty public constructor.
+     */
+    public ScarecrowTileEntity()
+    {
+        super();
+        setInventoryField(new InventoryField(LanguageHandler.getString("com.minecolonies.gui.inventory.scarecrow"), true));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MAJOR Remove this call from a constructor to the overridable "setInventoryField" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java [hunk 113]
```diff
@@ -1,647 +1,568 @@
...
-    private              List<BlockPos> plowedLand        = new ArrayList<>();
-    private              List<BlockPos> crops             = new ArrayList<>();
-    private              List<BlockPos> crops2            = new ArrayList<>();
-    private BlockPos currentFarmLand;
-    private int    harvestCounter = 0;
-    private String needItem       = "";
-    private int delay = 0;
-
-    //TODO Check for duplicates
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java [hunk 114]
```diff
@@ -1,647 +1,568 @@
...
 
     /**
-     * @return String for seeds renderer if farmer has seeds, otherwise empty string
+     * Prepares the farmer for farming.
+     * Also requests the tools and checks if the farmer has sufficient fields.
+     *
+     * @return the next AIState
      */
-    private String getRenderMetaSeeds()
+    private AIState prepareForFarming()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java]: MAJOR Reduce the number of returns of this method 7, down to the maximum allowed 5. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1142)
MAJOR The Cyclomatic Complexity of this method "prepareForFarming" is 22 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 29 issues
* MAJOR 11 major
* MINOR 18 minor

Watch the comments in this conversation to review them.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 19 issues
* MAJOR 7 major
* MINOR 12 minor

Watch the comments in this conversation to review them.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 15 issues
* MAJOR 7 major
* MINOR 8 minor

Watch the comments in this conversation to review them.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 14 issues
* MAJOR 6 major
* MINOR 8 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/inventory/GuiField.java [hunk 115]
```diff
@@ -0,0 +1,55 @@
...
+
+    /**
+     * Constructor of the GUI.
+     *
+     * @param parInventoryPlayer the player inventory.
+     * @param fieldInventory     the field inventory.
+     * @param world              the world the field is in.
+     * @param location           the location the field is at.
+     */
+    protected GuiField(InventoryPlayer parInventoryPlayer, IInventory fieldInventory, World world, BlockPos location)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiField.java]: MINOR It is a good practice to call super() in a constructor [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ACallSuperInConstructor)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 5 issues
* MAJOR 4 major
* MINOR 1 minor

Watch the comments in this conversation to review them.

**Comment by Kostronor** [comment]
Fixed some formatting @cltnschlosser @Raycoms but there is still an issue with a lot of duplicated code that could be removed with inheritance or using Utils classes

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 116]
```diff
@@ -0,0 +1,123 @@
...
+     */
+    public ScarecrowTileEntity()
+    {
+        super();
+        World world = getWorld();
+        this.inventoryField = new InventoryField(LanguageHandler.getString("com.minecolonies.gui.inventory.scarecrow"), true);
+
+        if(world != null)
+        {
+            Colony colony = ColonyManager.getColony(world, pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 117]
```diff
@@ -0,0 +1,123 @@
...
+
+            if (colony != null && colony.getField(pos) == null)
+            {
+                Entity entity = EntityUtils.getEntityFromUUID(world, colony.getPermissions().getOwner());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MINOR Local variable 'entity' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 118]
```diff
@@ -0,0 +1,123 @@
...
+
+import com.minecolonies.colony.Colony;
+import com.minecolonies.colony.ColonyManager;
+import com.minecolonies.inventory.InventoryField;
+import com.minecolonies.util.EntityUtils;
+import com.minecolonies.util.LanguageHandler;
+import net.minecraft.entity.Entity;
+import net.minecraft.entity.player.EntityPlayer;
+import net.minecraft.nbt.NBTTagCompound;
+import net.minecraft.tileentity.TileEntity;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MINOR Remove this unused import 'net.minecraft.tileentity.TileEntity'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 119]
```diff
@@ -0,0 +1,123 @@
...
+     */
+    private ScareCrowType  type;
+
+    /**
+     * Creates an instance of the tileEntity.
+     */
+    public ScarecrowTileEntity()
+    {
+        super();
+        World world = getWorld();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MAJOR Remove this call from a constructor to the overridable "getWorld" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)
MINOR Local variable 'world' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 120]
```diff
@@ -0,0 +1,224 @@
...
+import net.minecraft.util.EnumFacing;
+import net.minecraft.util.EnumWorldBlockLayer;
+import net.minecraft.world.IBlockAccess;
+import net.minecraft.world.World;
+import net.minecraft.world.WorldServer;
+import net.minecraftforge.fml.common.registry.GameRegistry;
+import net.minecraftforge.fml.relauncher.Side;
+import net.minecraftforge.fml.relauncher.SideOnly;
+
+import java.util.Random;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Remove this unused import 'java.util.Random'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 121]
```diff
@@ -0,0 +1,224 @@
...
+import com.minecolonies.tileentities.ScarecrowTileEntity;
+import com.minecolonies.util.EntityUtils;
+import com.minecolonies.util.LanguageHandler;
+import net.minecraft.block.BlockContainer;
+import net.minecraft.block.ITileEntityProvider;
+import net.minecraft.block.material.Material;
+import net.minecraft.block.properties.PropertyDirection;
+import net.minecraft.block.state.BlockState;
+import net.minecraft.block.state.IBlockState;
+import net.minecraft.entity.Entity;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Remove this unused import 'net.minecraft.entity.Entity'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 122]
```diff
@@ -0,0 +1,224 @@
+package com.minecolonies.blocks;
+
+import com.minecolonies.MineColonies;
+import com.minecolonies.colony.Colony;
+import com.minecolonies.colony.ColonyManager;
+import com.minecolonies.creativetab.ModCreativeTabs;
+import com.minecolonies.inventory.InventoryField;
+import com.minecolonies.lib.Constants;
+import com.minecolonies.tileentities.ScarecrowTileEntity;
+import com.minecolonies.util.EntityUtils;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Remove this unused import 'com.minecolonies.util.EntityUtils'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 123]
```diff
@@ -0,0 +1,224 @@
...
+import net.minecraft.entity.EntityLivingBase;
+import net.minecraft.entity.player.EntityPlayer;
+import net.minecraft.item.ItemStack;
+import net.minecraft.tileentity.TileEntity;
+import net.minecraft.util.BlockPos;
+import net.minecraft.util.EnumFacing;
+import net.minecraft.util.EnumWorldBlockLayer;
+import net.minecraft.world.IBlockAccess;
+import net.minecraft.world.World;
+import net.minecraft.world.WorldServer;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Remove this unused import 'net.minecraft.world.WorldServer'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutField.java [hunk 124]
```diff
@@ -0,0 +1,224 @@
...
+import com.minecolonies.colony.Colony;
+import com.minecolonies.colony.ColonyManager;
+import com.minecolonies.creativetab.ModCreativeTabs;
+import com.minecolonies.inventory.InventoryField;
+import com.minecolonies.lib.Constants;
+import com.minecolonies.tileentities.ScarecrowTileEntity;
+import com.minecolonies.util.EntityUtils;
+import com.minecolonies.util.LanguageHandler;
+import net.minecraft.block.BlockContainer;
+import net.minecraft.block.ITileEntityProvider;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutField.java]: MINOR Remove this unused import 'net.minecraft.block.ITileEntityProvider'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 15 issues
* MAJOR 5 major
* MINOR 10 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 125]
```diff
@@ -0,0 +1,128 @@
...
+    {
+        super();
+        this.inventoryField = new InventoryField(LanguageHandler.getString("com.minecolonies.gui.inventory.scarecrow"), true);
+    }
+
+    @Override
+    public void onLoad()
+    {
+        super.onLoad();
+        World world = getWorld();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MINOR Local variable 'world' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 126]
```diff
@@ -0,0 +1,128 @@
...
+
+        if(world != null)
+        {
+            Colony colony = ColonyManager.getColony(world, pos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 13 issues
* MAJOR 4 major
* MINOR 9 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/inventory/GuiHandler.java [hunk 127]
```diff
@@ -0,0 +1,33 @@
+package com.minecolonies.inventory;
+
+import com.minecolonies.colony.Field;
+import com.minecolonies.tileentities.ScarecrowTileEntity;
+import net.minecraft.entity.player.EntityPlayer;
+import net.minecraft.util.BlockPos;
+import net.minecraft.world.World;
+import net.minecraftforge.fml.common.network.IGuiHandler;
+import net.minecraftforge.fml.relauncher.Side;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiHandler.java]: MINOR Remove this unused import 'net.minecraftforge.fml.relauncher.Side'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/inventory/GuiHandler.java [hunk 128]
```diff
@@ -0,0 +1,33 @@
...
+import net.minecraftforge.fml.relauncher.SideOnly;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiHandler.java]: MINOR Remove this unused import 'net.minecraftforge.fml.relauncher.SideOnly'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 15 issues
* MAJOR 4 major
* MINOR 11 minor

Watch the comments in this conversation to review them.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 13 issues
* MAJOR 2 major
* MINOR 11 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/colony/Field.java [hunk 129]
```diff
@@ -0,0 +1,533 @@
...
+                        j + i * PLAYER_INVENTORY_COLUMNS + PLAYER_INVENTORY_COLUMNS,
+                        PLAYER_INVENTORY_INITIAL_X_OFFSET + j * PLAYER_INVENTORY_OFFSET_EACH,
+                        PLAYER_INVENTORY_INITIAL_Y_OFFSET + i * PLAYER_INVENTORY_OFFSET_EACH
+                ));
+            }
+        }
+
+        for (i = 0; i < PLAYER_INVENTORY_COLUMNS; i++)
+        {
+            addSlotToContainer(new Slot(
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 130]
```diff
@@ -0,0 +1,533 @@
...
+        addSlotToContainer(new Slot(inventory, 0, X_OFFSET, Y_OFFSET));
+
+        //Ddd player inventory slots
+        // Note: The slot numbers are within the player inventory and may be the same as the field inventory.
+        int i;
+        for (i = 0; i < PLAYER_INVENTORY_ROWS; i++)
+        {
+            for (int j = 0; j < PLAYER_INVENTORY_COLUMNS; j++)
+            {
+                addSlotToContainer(new Slot(
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/colony/Field.java [hunk 131]
```diff
@@ -0,0 +1,533 @@
...
+     */
+    public Field(ScarecrowTileEntity scarecrowTileEntity, InventoryPlayer playerInventory, World world, BlockPos location)
+    {
+        super();
+        this.colony = ColonyManager.getColony(world, location);
+        this.location = location;
+
+        this.inventory = scarecrowTileEntity.getInventoryField();
+
+        addSlotToContainer(new Slot(inventory, 0, X_OFFSET, Y_OFFSET));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 132]
```diff
@@ -0,0 +1,182 @@
+package com.minecolonies.inventory;
+import net.minecraft.entity.player.EntityPlayer;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MINOR Remove this unused import 'net.minecraft.entity.player.EntityPlayer'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/inventory/GuiField.java [hunk 133]
```diff
@@ -0,0 +1,56 @@
+package com.minecolonies.inventory;
+
+import com.minecolonies.colony.Field;
+import com.minecolonies.lib.Constants;
+import com.minecolonies.tileentities.ScarecrowTileEntity;
+import net.minecraft.client.gui.inventory.GuiContainer;
+import net.minecraft.client.renderer.GlStateManager;
+import net.minecraft.entity.player.InventoryPlayer;
+import net.minecraft.inventory.IInventory;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiField.java]: MINOR Remove this unused import 'net.minecraft.inventory.IInventory'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 134]
```diff
@@ -10,11 +10,14 @@
 import com.minecolonies.colony.workorders.AbstractWorkOrder;
 import com.minecolonies.configuration.Configurations;
 import com.minecolonies.entity.EntityCitizen;
+import com.minecolonies.inventory.InventoryField;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Remove this unused import 'com.minecolonies.inventory.InventoryField'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 18 issues
* MAJOR 5 major
* MINOR 13 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/colony/Field.java [hunk 135]
```diff
@@ -0,0 +1,532 @@
...
+     * @param location        the position of the field.
+     */
+    public Field(ScarecrowTileEntity scarecrowTileEntity, InventoryPlayer playerInventory, World world, BlockPos location)
+    {
+        super();
+        this.colony = ColonyManager.getColony(world, location);
+        this.location = location;
+        this.inventory = scarecrowTileEntity.getInventoryField();
+
+        addSlotToContainer(new Slot(inventory, 0, X_OFFSET, Y_OFFSET));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 15 issues
* MAJOR 5 major
* MINOR 10 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/Field.java [hunk 136]
```diff
@@ -0,0 +1,567 @@
...
+        addSlotToContainer(new Slot(inventory, 0, X_OFFSET, Y_OFFSET));
+
+        //Ddd player inventory slots
+        // Note: The slot numbers are within the player inventory and may be the same as the field inventory.
+        int i;
+        for (i = 0; i < PLAYER_INVENTORY_ROWS; i++)
+        {
+            for (int j = 0; j < PLAYER_INVENTORY_COLUMNS; j++)
+            {
+                addSlotToContainer(new Slot(
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/Field.java [hunk 137]
```diff
@@ -0,0 +1,567 @@
...
+     * @param location        the position of the field.
+     */
+    public Field(ScarecrowTileEntity scarecrowTileEntity, InventoryPlayer playerInventory, World world, BlockPos location)
+    {
+        super();
+        this.colony = ColonyManager.getColony(world, location);
+        this.location = location;
+        this.inventory = scarecrowTileEntity.getInventoryField();
+
+        addSlotToContainer(new Slot(inventory, 0, X_OFFSET, Y_OFFSET));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/Field.java [hunk 138]
```diff
@@ -0,0 +1,567 @@
...
+                        j + i * PLAYER_INVENTORY_COLUMNS + PLAYER_INVENTORY_COLUMNS,
+                        PLAYER_INVENTORY_INITIAL_X_OFFSET + j * PLAYER_INVENTORY_OFFSET_EACH,
+                        PLAYER_INVENTORY_INITIAL_Y_OFFSET + i * PLAYER_INVENTORY_OFFSET_EACH
+                ));
+            }
+        }
+
+        for (i = 0; i < PLAYER_INVENTORY_COLUMNS; i++)
+        {
+            addSlotToContainer(new Slot(
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/Field.java]: MAJOR Remove this call from a constructor to the overridable "addSlotToContainer" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1699)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 139]
```diff
@@ -100,35 +410,58 @@ public View(ColonyView c, BlockPos l)
         @Override
         public void deserialize(ByteBuf buf)
         {
+            fields = new ArrayList<>();
             super.deserialize(buf);
+            assignFieldManually = buf.readBoolean();
+            int size = buf.readInt();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'size' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 140]
```diff
@@ -4,89 +4,399 @@
...
 
-        farmerCompound.setInteger(WHEAT_TAG,wheat);
-        farmerCompound.setInteger(POTATO_TAG,potato);
-        farmerCompound.setInteger(CARROT_TAG,carrot);
-        farmerCompound.setInteger(MELON_TAG,melon);
-        farmerCompound.setInteger(PUMPKIN_TAG, pumpkin);
+        int size = 0;
 
-        compound.setTag(TAG_FARMER, farmerCompound);
+        for(Field field: getColony().getFields().values())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 141]
```diff
@@ -4,89 +4,399 @@
...
+            }
+            else
+            {
+                size++;
+            }
+        }
+
+        buf.writeInt(size);
+
+        for(Field field: getColony().getFields().values())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 142]
```diff
@@ -4,89 +4,399 @@
...
+        }
+    }
+
+    /**
+     * Method called to assign a field to the farmer.
+     * @param position id of the field.
+     */
+    public void assignField(BlockPos position)
+    {
+        Field field = getColony().getField(position);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 143]
```diff
@@ -100,35 +410,58 @@ public View(ColonyView c, BlockPos l)
         @Override
         public void deserialize(ByteBuf buf)
         {
+            fields = new ArrayList<>();
             super.deserialize(buf);
+            assignFieldManually = buf.readBoolean();
+            int size = buf.readInt();
+            for(int i = 1; i <= size; i++)
+            {
+                FieldView fieldView = new FieldView();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'fieldView' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 144]
```diff
@@ -4,89 +4,399 @@
...
     }
 
+    /**
+     * Method called to free a field.
+     * @param position id of the field.
+     */
+    public void freeField(BlockPos position)
+    {
+        //Get the field with matching id, if none found return null.
+        Field tempField = farmerFields.stream().filter(field -> field.getID() == position).findFirst().orElse(null);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'tempField' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 145]
```diff
@@ -4,89 +4,399 @@
...
+        return assignManually;
+    }
 
     @Override
     public AbstractJob createJob(CitizenData citizen)
     {
-        return new JobFarmer(citizen); //TODO Implement Later
+        if(!farmerFields.isEmpty())
+        {
+            for(Field field: farmerFields)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 146]
```diff
@@ -4,89 +4,399 @@
...
+            {
+                Field colonyField = getColony().getField(field.getID());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'colonyField' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 147]
```diff
@@ -4,89 +4,399 @@
...
+
+        buf.writeInt(size);
+
+        for(Field field: getColony().getFields().values())
+        {
+            if(field.isTaken())
+            {
+                if(getWorker() == null || field.getOwner().equals(getWorker().getName()))
+                {
+                    FieldView fieldView = new FieldView(field);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'fieldView' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 148]
```diff
@@ -4,89 +4,399 @@
...
+                    fieldView.serializeViewNetworkData(buf);
+                }
+            }
+            else
+            {
+                FieldView fieldView = new FieldView(field);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'fieldView' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/network/messages/AssignmentModeMessage.java [hunk 149]
```diff
@@ -0,0 +1,76 @@
...
+     * Empty standard constructor.
+     */
+    public AssignmentModeMessage()
+    {
+        /**
+         * Intentionally left empty.
+         */
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/AssignmentModeMessage.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/network/messages/AssignmentModeMessage.java [hunk 150]
```diff
@@ -0,0 +1,76 @@
...
+    {
+        colonyId = buf.readInt();
+        buildingId = BlockPosUtil.readFromByteBuf(buf);
+        assignmentMode = buf.readBoolean();
+    }
+
+    @Override
+    public IMessage onMessage(AssignmentModeMessage message, MessageContext ctx)
+    {
+        Colony colony = ColonyManager.getColony(message.colonyId);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/AssignmentModeMessage.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/network/messages/AssignmentModeMessage.java [hunk 151]
```diff
@@ -0,0 +1,76 @@
...
+        if (colony != null)
+        {
+            BuildingFarmer building = colony.getBuilding(message.buildingId, BuildingFarmer.class);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/AssignmentModeMessage.java]: MINOR Local variable 'building' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 152]
```diff
@@ -0,0 +1,344 @@
...
+            if (this.stackResult[index].stackSize <= count)
+            {
+                ItemStack itemStack1 = this.stackResult[index];
+                this.stackResult[index] = null;
+                this.markDirty();
+                return itemStack1;
+            }
+            else
+            {
+                ItemStack itemstack = this.stackResult[index].splitStack(count);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MINOR Local variable 'itemstack' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 153]
```diff
@@ -0,0 +1,344 @@
...
+    @Override
+    public ItemStack getStackInSlot(int index)
+    {
+        return this.stackResult[0];
+    }
+
+    @Override
+    public ItemStack decrStackSize(int index, int count)
+    {
+        if (this.stackResult[index] != null)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MAJOR Avoid if (x != y) ..; else ..; [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AConfusingTernary)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 154]
```diff
@@ -0,0 +1,344 @@
...
+        else
+        {
+            return null;
+        }
+    }
+
+    @Override
+    public ItemStack removeStackFromSlot(final int index)
+    {
+        if (this.stackResult[index] != null)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MAJOR Avoid if (x != y) ..; else ..; [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AConfusingTernary)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 155]
```diff
@@ -0,0 +1,344 @@
...
+        {
+            ItemStack itemstack = this.stackResult[index];
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MINOR Local variable 'itemstack' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 156]
```diff
@@ -0,0 +1,344 @@
...
+            inventoryChanged = false;
+            return true;
+        }
+        return false;
+    }
+
+    @Override
+    public boolean isUseableByPlayer(final EntityPlayer entityPlayer)
+    {
+        return true;//colony.getPermissions().hasPermission(entityPlayer, Permissions.Action.ACCESS_HUTS);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MAJOR This block of commented-out lines of code should be removed. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
INFO Move this trailing comment on the previous empty line. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ATrailingCommentCheck)

File: src/main/java/com/minecolonies/inventory/InventoryField.java [hunk 157]
```diff
@@ -0,0 +1,344 @@
...
+    }
+
+    @Override
+    public ItemStack decrStackSize(int index, int count)
+    {
+        if (this.stackResult[index] != null)
+        {
+            if (this.stackResult[index].stackSize <= count)
+            {
+                ItemStack itemStack1 = this.stackResult[index];
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/InventoryField.java]: MINOR Local variable 'itemStack1' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java [hunk 158]
```diff
@@ -0,0 +1,88 @@
...
+        colonyId = buf.readInt();
+        buildingId = BlockPosUtil.readFromByteBuf(buf);
+        assign = buf.readBoolean();
+        field = BlockPosUtil.readFromByteBuf(buf);
+    }
+
+    @Override
+    public IMessage onMessage(AssignFieldMessage message, MessageContext ctx)
+    {
+        Colony colony = ColonyManager.getColony(message.colonyId);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java [hunk 159]
```diff
@@ -0,0 +1,88 @@
...
+        if (colony != null)
+        {
+            BuildingFarmer building = colony.getBuilding(message.buildingId, BuildingFarmer.class);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java]: MINOR Local variable 'building' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 160]
```diff
@@ -201,37 +190,122 @@ public String getBuildingName()
...
-            findPaneOfTypeByID(BUTTON_POTATO, ButtonVanilla.class).setLabel(Integer.toString(building.potato));
-            findPaneOfTypeByID(BUTTON_CARROT, ButtonVanilla.class).setLabel(Integer.toString(building.carrot));
-            findPaneOfTypeByID(BUTTON_MELON, ButtonVanilla.class).setLabel(Integer.toString(building.melon));
-            findPaneOfTypeByID(BUTTON_PUMPKIN, ButtonVanilla.class).setLabel(Integer.toString(building.pumpkin));
+            dist = LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.North");
+        }
 
+        if(field.getX() > building.getX())
+        {
+            dist += LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.East");
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MAJOR Prefer StringBuffer over += for concatenating strings [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AUseStringBufferForStringAppends)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 161]
```diff
@@ -201,37 +190,122 @@ public String getBuildingName()
...
         }
-        catch (RuntimeException exc)
+        else
         {
-            Log.logger.error("findPane error, report to mod authors", exc);
+            dist += LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.West");
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MAJOR Prefer StringBuffer over += for concatenating strings [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AUseStringBufferForStringAppends)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 162]
```diff
@@ -1,198 +1,187 @@
 package com.minecolonies.client.gui;
 
+import com.blockout.Pane;
 import com.blockout.controls.Button;
 import com.blockout.controls.ButtonVanilla;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Remove this unused import 'com.blockout.controls.ButtonVanilla'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 163]
```diff
@@ -201,37 +190,122 @@ public String getBuildingName()
...
+            @Override
+            public int getElementCount()
+            {
+                return fields.size();
+            }
+
+            @Override
+            public void updateElement(int index, Pane rowPane)
+            {
+                FieldView field = fields.get(index);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 164]
```diff
@@ -201,37 +190,122 @@ public String getBuildingName()
...
+                String distance = Integer.toString((int)Math.sqrt(BlockPosUtil.getDistanceSquared(field.getId(), building.getLocation())));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Local variable 'distance' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 165]
```diff
@@ -201,37 +190,122 @@ public String getBuildingName()
...
+                String direction = calcDirection(building.getLocation(), field.getId());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Local variable 'direction' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 166]
```diff
@@ -201,37 +190,122 @@ public String getBuildingName()
...
+                String owner = ("").equals(field.getOwner()) ? ("<" + LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.unused") + ">") : field.getOwner();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Local variable 'owner' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 167]
```diff
@@ -201,37 +190,122 @@ public String getBuildingName()
...
+            dist += LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.West");
         }
+
+        return dist;
     }
 
+    @Override
+    public void onUpdate()
+    {
+        String currentPage = findPaneOfTypeByID(VIEW_PAGES, SwitchView.class).getCurrentView().getID();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Local variable 'currentPage' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 168]
```diff
@@ -1,198 +1,187 @@
...
-     * @param ignored   Parameter is ignored, since some actions require a button.
-     *                  This method does not
+     * Fired when the assignment mode has been toggled.
+     * @param button clicked button.
      */
-    private void carrotClicked(Button ignored)
+    private void assignmentModeClicked(Button button)
     {
-        if (building.carrot >= MAX_AMOUNT)
+        if(button.getLabel().equals(LanguageHandler.format("com.minecolonies.gui.hiring.off")))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Define a constant instead of duplicating this literal "com.minecolonies.gui.hiring.off" 3 times. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1192)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 169]
```diff
@@ -1,198 +1,187 @@
...
 import com.blockout.views.SwitchView;
 import com.minecolonies.MineColonies;
 import com.minecolonies.colony.buildings.BuildingFarmer;
+import com.minecolonies.entity.ai.citizen.farmer.FieldView;
 import com.minecolonies.lib.Constants;
-import com.minecolonies.network.messages.FarmerCropTypeMessage;
-import com.minecolonies.util.Log;
+import com.minecolonies.network.messages.AssignFieldMessage;
+import com.minecolonies.network.messages.AssignmentModeMessage;
+import com.minecolonies.network.messages.MinerSetLevelMessage;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Remove this unused import 'com.minecolonies.network.messages.MinerSetLevelMessage'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 170]
```diff
@@ -4,89 +4,407 @@
...
 
-        NBTTagCompound farmerCompound = new NBTTagCompound();
+        int size = 0;
 
-        farmerCompound.setInteger(WHEAT_TAG,wheat);
-        farmerCompound.setInteger(POTATO_TAG,potato);
-        farmerCompound.setInteger(CARROT_TAG,carrot);
-        farmerCompound.setInteger(MELON_TAG,melon);
-        farmerCompound.setInteger(PUMPKIN_TAG, pumpkin);
+        for(Field field: getColony().getFields().values())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 171]
```diff
@@ -4,89 +4,407 @@
...
+        super.onDestroyed();
+        for(final Field field: farmerFields)
+        {
+            Field tempField = getColony().getField(field.getID());
+
+            if(tempField != null)
+            {
+                tempField.setTaken(false);
+                tempField.setOwner("");
+                ScarecrowTileEntity scarecrowTileEntity = (ScarecrowTileEntity) getColony().getWorld().getTileEntity(field.getID());
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'scarecrowTileEntity' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 172]
```diff
@@ -4,89 +4,407 @@
...
     }
 
+    /**
+     * Method called to free a field.
+     * @param position id of the field.
+     */
+    public void freeField(BlockPos position)
+    {
+        //Get the field with matching id, if none found return null.
+        Field tempField = farmerFields.stream().filter(field -> field.getID().equals(position)).findFirst().orElse(null);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'tempField' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 173]
```diff
@@ -100,35 +418,67 @@ public View(ColonyView c, BlockPos l)
...
+        public int getAmountOfFields()
+        {
+            return amountOfFields;
+        }
+
+        /**
+         * Reduces the amount of fields by i.
+         * @param i the number to reduce.
+         */
+        public void reduceAmountOfFields(final int i)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MAJOR Remove this unused method parameter "i". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 174]
```diff
@@ -4,89 +4,407 @@
...
+     */
+    public void freeField(BlockPos position)
+    {
+        //Get the field with matching id, if none found return null.
+        Field tempField = farmerFields.stream().filter(field -> field.getID().equals(position)).findFirst().orElse(null);
+
+        if(tempField != null)
+        {
+            farmerFields.remove(tempField);
+            Field field = getColony().getField(position);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java [hunk 175]
```diff
@@ -0,0 +1,146 @@
...
+        switch (facing)
+        {
+            case EAST:
+                GlStateManager.rotate(BASIC_ROTATION*ROTATE_EAST, 0, 1, 0);
+                break;
+            case SOUTH:
+                GlStateManager.rotate(BASIC_ROTATION*ROTATE_SOUTH, 0, 1, 0);
+                break;
+            case WEST:
+                GlStateManager.rotate(BASIC_ROTATION*ROTATE_WEST, 0, 1, 0);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java]: CRITICAL Cast one of the operands of this multiplication operation to a "float". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2184)

File: src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java [hunk 176]
```diff
@@ -0,0 +1,146 @@
...
+        GlStateManager.translate(posX+BLOCK_MIDDLE, posY+YOFFSET, posZ+BLOCK_MIDDLE);
+
+        this.bindTexture(getResourceLocation(te));
+
+        GlStateManager.rotate(ROTATION, XROTATIONOFFSET, YROTATIONOFFSET, ZROTATIONOFFSET);
+
+        switch (facing)
+        {
+            case EAST:
+                GlStateManager.rotate(BASIC_ROTATION*ROTATE_EAST, 0, 1, 0);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java]: CRITICAL Cast one of the operands of this multiplication operation to a "float". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2184)

File: src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java [hunk 177]
```diff
@@ -0,0 +1,146 @@
...
+    public TileEntityScarecrowRenderer()
+    {
+        super();
+        this.model = new ModelScarecrowBoth();
+    }
+    
+    @Override
+    public void renderTileEntityAt(ScarecrowTileEntity te, double posX, double posY, double posZ, float partialTicks, int destroyStage)
+    {
+        EnumFacing facing = getWorld().getBlockState(te.getPos()).getValue(BlockHutField.FACING);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java]: MINOR Local variable 'facing' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java [hunk 178]
```diff
@@ -0,0 +1,146 @@
...
+
+        GlStateManager.rotate(ROTATION, XROTATIONOFFSET, YROTATIONOFFSET, ZROTATIONOFFSET);
+
+        switch (facing)
+        {
+            case EAST:
+                GlStateManager.rotate(BASIC_ROTATION*ROTATE_EAST, 0, 1, 0);
+                break;
+            case SOUTH:
+                GlStateManager.rotate(BASIC_ROTATION*ROTATE_SOUTH, 0, 1, 0);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/render/TileEntityScarecrowRenderer.java]: CRITICAL Cast one of the operands of this multiplication operation to a "float". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2184)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 179]
```diff
@@ -0,0 +1,128 @@
...
+     */
+    private ScareCrowType  type;
+
+    /**
+     * Creates an instance of the tileEntity.
+     */
+    public ScarecrowTileEntity()
+    {
+        super();
+        this.inventoryField = new InventoryField(LanguageHandler.format("com.minecolonies.gui.scarecrow.user", LanguageHandler.format("com.minecolonies.gui.scarecrow.user.noone")));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MINOR Split this 181 characters long line (which is greater than 180 authorized). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 180]
```diff
@@ -23,6 +27,7 @@
 import net.minecraft.world.World;
 import net.minecraftforge.common.util.Constants.NBT;
 import net.minecraftforge.fml.common.gameevent.TickEvent;
+import org.apache.commons.codec.language.bm.Lang;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Remove this unused import 'org.apache.commons.codec.language.bm.Lang'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/FieldView.java [hunk 181]
```diff
@@ -0,0 +1,129 @@
+package com.minecolonies.entity.ai.citizen.farmer;
+
+import com.minecolonies.util.BlockPosUtil;
+import com.minecolonies.util.BlockUtils;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/FieldView.java]: MINOR Remove this unused import 'com.minecolonies.util.BlockUtils'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/FieldView.java [hunk 182]
```diff
@@ -0,0 +1,129 @@
...
+     *
+     * @param buf Byte buffer to deserialize.
+     * @return FieldView return an instance of the fieldView.
+     */
+    public FieldView deserialize(ByteBuf buf)
+    {
+        id = BlockPosUtil.readFromByteBuf(buf);
+        taken = buf.readBoolean();
+        owner = ByteBufUtils.readUTF8String(buf);
+        int itemId = buf.readInt();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/FieldView.java]: MINOR Local variable 'itemId' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/FieldView.java [hunk 183]
```diff
@@ -0,0 +1,129 @@
...
+     * Writes the fields data to a byte buf for transition.
+     *
+     * @param buf Buffer to write to.
+     */
+    public void serializeViewNetworkData(ByteBuf buf)
+    {
+        BlockPosUtil.writeToByteBuf(buf, id);
+        buf.writeBoolean(taken);
+        ByteBufUtils.writeUTF8String(buf, owner);
+        int itemId = item == null? 0 : Item.getIdFromItem(item);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/FieldView.java]: MINOR Local variable 'itemId' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 184]
```diff
@@ -201,37 +188,122 @@ public String getBuildingName()
...
 
     /**
-     * Updates the labels on the buttons
+     * Calculates the direction the field is from the building.
+     * @param building the building
+     * @param field the field.
+     * @return a string describing the direction.
      */
-    private void updateButtonLabels()
+    private String calcDirection(BlockPos building, BlockPos field)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Make "calcDirection" a "static" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2325)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 185]
```diff
@@ -1,198 +1,185 @@
...
-     *                  This method does not
+     * Fired when assign has been clicked in the field list.
+     * @param button clicked button.
      */
-    private void pumpkinClicked(Button ignored)
+    private void assignClicked(Button button)
     {
-        if (building.pumpkin >= MAX_AMOUNT)
+        int row = fieldList.getListElementIndexByPane(button);
+        FieldView field = fields.get(row);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Local variable 'field' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 186]
```diff
@@ -201,37 +188,122 @@ public String getBuildingName()
...
 
+        if(field.getX() > building.getX()+1)
+        {
+            dist += LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.East");
         }
-        catch (RuntimeException exc)
+        else if(field.getX() < building.getX()-1)
         {
-            Log.logger.error("findPane error, report to mod authors", exc);
+            dist += LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.West");
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MAJOR Prefer StringBuffer over += for concatenating strings [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AUseStringBufferForStringAppends)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 187]
```diff
@@ -201,37 +188,122 @@ public String getBuildingName()
...
+                return fields.size();
+            }
+
+            @Override
+            public void updateElement(int index, Pane rowPane)
+            {
+                FieldView field = fields.get(index);
+                String distance = Integer.toString((int)Math.sqrt(BlockPosUtil.getDistanceSquared(field.getId(), building.getLocation())));
+                String direction = calcDirection(building.getLocation(), field.getId());
+                String owner = field.getOwner().isEmpty() ? ("<" + LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.unused") + ">") : field.getOwner();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MINOR Local variable 'owner' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 188]
```diff
@@ -201,37 +188,122 @@ public String getBuildingName()
...
+        {
+            findPaneOfTypeByID(TAG_BUTTON_ASSIGNMENT_MODE, Button.class).setLabel(LanguageHandler.format("com.minecolonies.gui.hiring.off"));
+        }
+
         findPaneOfTypeByID(BUTTON_PREV_PAGE, Button.class).setEnabled(false);
         buttonPrevPage = findPaneOfTypeByID(BUTTON_PREV_PAGE, Button.class);
         buttonNextPage = findPaneOfTypeByID(BUTTON_NEXT_PAGE, Button.class);
+
+        fieldList = findPaneOfTypeByID(LIST_FIELDS, ScrollingList.class);
+        fieldList.setDataProvider(new ScrollingList.DataProvider()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MAJOR Reduce this anonymous class number of lines from 45 to at most 30, or make it a named class. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1188)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 189]
```diff
@@ -201,37 +188,122 @@ public String getBuildingName()
...
-            findPaneOfTypeByID(BUTTON_POTATO, ButtonVanilla.class).setLabel(Integer.toString(building.potato));
-            findPaneOfTypeByID(BUTTON_CARROT, ButtonVanilla.class).setLabel(Integer.toString(building.carrot));
-            findPaneOfTypeByID(BUTTON_MELON, ButtonVanilla.class).setLabel(Integer.toString(building.melon));
-            findPaneOfTypeByID(BUTTON_PUMPKIN, ButtonVanilla.class).setLabel(Integer.toString(building.pumpkin));
+            dist = LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.North");
+        }
 
+        if(field.getX() > building.getX()+1)
+        {
+            dist += LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.East");
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MAJOR Prefer StringBuffer over += for concatenating strings [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AUseStringBufferForStringAppends)

File: src/main/java/com/minecolonies/inventory/GuiField.java [hunk 190]
```diff
@@ -0,0 +1,83 @@
...
+     * The resource location of the GUI background.
+     */
+    private static final ResourceLocation TEXTURE = new ResourceLocation(Constants.MOD_ID, "textures/gui/scarecrow.png");
+
+    /**
+     * The X-OFFSET of the string in the GUI.
+     */
+    private static final int X_OFFSET = 8;
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiField.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/inventory/GuiField.java [hunk 191]
```diff
@@ -0,0 +1,83 @@
+package com.minecolonies.inventory;
+
+import com.minecolonies.colony.ColonyManager;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiField.java]: MINOR Remove this unused import 'com.minecolonies.colony.ColonyManager'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/inventory/GuiField.java [hunk 192]
```diff
@@ -0,0 +1,83 @@
...
+     * @param world              the world the field is in.
+     * @param location           the location the field is at.
+     */
+    protected GuiField(InventoryPlayer parInventoryPlayer, ScarecrowTileEntity tileEntity, World world, BlockPos location)
+    {
+        super(new Field(tileEntity, parInventoryPlayer, world, location));
+        this.tileEntity = tileEntity;
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiField.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/inventory/GuiField.java [hunk 193]
```diff
@@ -0,0 +1,83 @@
...
+     * Method called to draw the foreground of the GUI
+     * @param layer1 the first layer.
+     * @param layer2 the second layer.
+     */
+    protected void drawGuiContainerForegroundLayer(int layer1, int layer2)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/inventory/GuiField.java]: MAJOR Add the "@Override" annotation above this method signature [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 60 issues
* CRITICAL 3 critical
* MAJOR 12 major
* MINOR 45 minor

Watch the comments in this conversation to review them.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 42 issues
* CRITICAL 3 critical
* MAJOR 12 major
* MINOR 27 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 194]
```diff
@@ -0,0 +1,161 @@
...
+    {
+        super();
+        this.inventoryField = new InventoryField(name);
+    }
+
+    /**
+     * Getter of the name of the tileEntity.
+     * @return the string.
+     */
+    public String getName()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MAJOR Add the "@Override" annotation above this method signature [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)

File: src/main/java/com/minecolonies/client/gui/AbstractWindowSkeleton.java [hunk 195]
```diff
@@ -65,6 +65,7 @@ public void onButtonClicked(Button button)
      */
     public final void doNothing(Button ignored)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/AbstractWindowSkeleton.java]: MAJOR Remove this unused method parameter "ignored". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/client/gui/AbstractWindowSkeleton.java [hunk 196]
```diff
@@ -65,6 +65,7 @@ public void onButtonClicked(Button button)
...
     {
+       System.out.print("lalala");
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/AbstractWindowSkeleton.java]: MAJOR Replace this usage of System.out or System.err by a logger. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS106)

File: src/main/java/com/minecolonies/client/gui/AbstractWindowSkeleton.java [hunk 197]
```diff
@@ -65,6 +65,7 @@ public void onButtonClicked(Button button)
...
         //do nothing with that event
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/AbstractWindowSkeleton.java]: MINOR Comment has incorrect indentation level 8, expected is 7, indentation should be the same level as line 68. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 23 issues
* MAJOR 14 major
* MINOR 9 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java [hunk 198]
```diff
@@ -4,89 +4,411 @@
...
+                {
+                    farmerFields.remove(field);
+                    if (currentField != null && currentField.getID() == field.getID())
+                    {
+                        currentField = null;
+                    }
+                }
+                else
+                {
+                    scarecrow.setName(LanguageHandler.format("com.minecolonies.gui.scarecrow.user", getWorker().getName()));
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/buildings/BuildingFarmer.java]: MINOR Define a constant instead of duplicating this literal "com.minecolonies.gui.scarecrow.user" 3 times. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1192)

File: src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java [hunk 199]
```diff
@@ -0,0 +1,182 @@
...
+    {
+         this.name = name;
+    }
+
+    ///////////---- Following methods are used to update the tileEntity between client and server ----///////////
+
+    @Override
+    public Packet getDescriptionPacket()
+    {
+        NBTTagCompound tag = new NBTTagCompound();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/ScarecrowTileEntity.java]: MINOR Local variable 'tag' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 19 issues
* MAJOR 11 major
* MINOR 8 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java [hunk 200]
```diff
@@ -1,647 +1,561 @@
...
-                    }
-                    //TODO add block break effect
-                    world.setBlockToAir(crops.get(0));
-                    harvestCounter++;
+    /**
+     * Executes the harvesting of the field.
+     *
+     * @return the next state.
+     */
+    private AIState harvest()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/farmer/EntityAIWorkFarmer.java]: MAJOR Remove this unused private "harvest" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 23 issues
* MAJOR 19 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIBasic.java#L211](https://github.com/Minecolonies/minecolonies/blob/3459c07e3f8cf441dff214774e234bb845a721ea/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L211): Remove this unused private "initSafetyChecks" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [AbstractEntityAIBasic.java#L647](https://github.com/Minecolonies/minecolonies/blob/3459c07e3f8cf441dff214774e234bb845a721ea/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L647): Remove this unused private "dumpInventory" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L244](https://github.com/Minecolonies/minecolonies/blob/3459c07e3f8cf441dff214774e234bb845a721ea/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L244): Remove this unused private "startWorkingAtOwnBuilding" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L345](https://github.com/Minecolonies/minecolonies/blob/3459c07e3f8cf441dff214774e234bb845a721ea/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L345): Remove this unused private "clearStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L402](https://github.com/Minecolonies/minecolonies/blob/3459c07e3f8cf441dff214774e234bb845a721ea/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L402): Remove this unused private "requestMaterials" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L458](https://github.com/Minecolonies/minecolonies/blob/3459c07e3f8cf441dff214774e234bb845a721ea/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L458): Remove this unused private "structureStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L512](https://github.com/Minecolonies/minecolonies/blob/3459c07e3f8cf441dff214774e234bb845a721ea/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L512): Remove this unused private "decorationStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L770](https://github.com/Minecolonies/minecolonies/blob/3459c07e3f8cf441dff214774e234bb845a721ea/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L770): Remove this unused private "completeBuild" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java [hunk 201]
```diff
@@ -201,37 +177,129 @@ public String getBuildingName()
...
+                final String distance = Integer.toString((int)Math.sqrt(BlockPosUtil.getDistanceSquared(field.getId(), building.getLocation())));
+                final String direction = calcDirection(building.getLocation(), field.getId());
+                final String owner = field.getOwner().isEmpty() ? ("<" + LanguageHandler.format("com.minecolonies.gui.workerHuts.farmerHut.unused") + ">") : field.getOwner();
+
+                rowPane.findPaneOfTypeByID(TAG_WORKER, Label.class).setLabelText(owner);
+                rowPane.findPaneOfTypeByID(TAG_DISTANCE, Label.class).setLabelText(distance  + "m");
+
+                rowPane.findPaneOfTypeByID(TAG_DIRECTION, Label.class).setLabelText(direction);
+
+                if(!building.assignFieldManually())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: MAJOR Avoid if (x != y) ..; else ..; [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AConfusingTernary)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 24 issues
* MAJOR 20 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIBasic.java#L211](https://github.com/Minecolonies/minecolonies/blob/a221b03a9699ddbb1291a21dcb8936e804ff786d/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L211): Remove this unused private "initSafetyChecks" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [AbstractEntityAIBasic.java#L647](https://github.com/Minecolonies/minecolonies/blob/a221b03a9699ddbb1291a21dcb8936e804ff786d/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L647): Remove this unused private "dumpInventory" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L244](https://github.com/Minecolonies/minecolonies/blob/a221b03a9699ddbb1291a21dcb8936e804ff786d/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L244): Remove this unused private "startWorkingAtOwnBuilding" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L345](https://github.com/Minecolonies/minecolonies/blob/a221b03a9699ddbb1291a21dcb8936e804ff786d/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L345): Remove this unused private "clearStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L402](https://github.com/Minecolonies/minecolonies/blob/a221b03a9699ddbb1291a21dcb8936e804ff786d/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L402): Remove this unused private "requestMaterials" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L458](https://github.com/Minecolonies/minecolonies/blob/a221b03a9699ddbb1291a21dcb8936e804ff786d/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L458): Remove this unused private "structureStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L512](https://github.com/Minecolonies/minecolonies/blob/a221b03a9699ddbb1291a21dcb8936e804ff786d/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L512): Remove this unused private "decorationStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L770](https://github.com/Minecolonies/minecolonies/blob/a221b03a9699ddbb1291a21dcb8936e804ff786d/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L770): Remove this unused private "completeBuild" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 24 issues
* MAJOR 20 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIBasic.java#L211](https://github.com/Minecolonies/minecolonies/blob/3ba5c9eb73fdaabc905f4e81f2bd2c229cbf0589/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L211): Remove this unused private "initSafetyChecks" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [AbstractEntityAIBasic.java#L647](https://github.com/Minecolonies/minecolonies/blob/3ba5c9eb73fdaabc905f4e81f2bd2c229cbf0589/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L647): Remove this unused private "dumpInventory" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L244](https://github.com/Minecolonies/minecolonies/blob/3ba5c9eb73fdaabc905f4e81f2bd2c229cbf0589/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L244): Remove this unused private "startWorkingAtOwnBuilding" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L345](https://github.com/Minecolonies/minecolonies/blob/3ba5c9eb73fdaabc905f4e81f2bd2c229cbf0589/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L345): Remove this unused private "clearStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L402](https://github.com/Minecolonies/minecolonies/blob/3ba5c9eb73fdaabc905f4e81f2bd2c229cbf0589/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L402): Remove this unused private "requestMaterials" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L458](https://github.com/Minecolonies/minecolonies/blob/3ba5c9eb73fdaabc905f4e81f2bd2c229cbf0589/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L458): Remove this unused private "structureStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L512](https://github.com/Minecolonies/minecolonies/blob/3ba5c9eb73fdaabc905f4e81f2bd2c229cbf0589/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L512): Remove this unused private "decorationStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L770](https://github.com/Minecolonies/minecolonies/blob/3ba5c9eb73fdaabc905f4e81f2bd2c229cbf0589/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L770): Remove this unused private "completeBuild" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

File: src/main/java/com/minecolonies/util/BlockUtils.java [hunk 202]
```diff
@@ -112,6 +111,13 @@ public static boolean isWater(IBlockState iBlockState)
                || Objects.equals(iBlockState, Blocks.flowing_water.getDefaultState());
     }
 
+
+    public static boolean isBlockSeed(World world, BlockPos pos)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/BlockUtils.java]: MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 25 issues
* MAJOR 20 major
* MINOR 5 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIBasic.java#L211](https://github.com/Minecolonies/minecolonies/blob/69fd859289aee525d2551924f3260d76436ea757/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L211): Remove this unused private "initSafetyChecks" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [AbstractEntityAIBasic.java#L647](https://github.com/Minecolonies/minecolonies/blob/69fd859289aee525d2551924f3260d76436ea757/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L647): Remove this unused private "dumpInventory" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L244](https://github.com/Minecolonies/minecolonies/blob/69fd859289aee525d2551924f3260d76436ea757/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L244): Remove this unused private "startWorkingAtOwnBuilding" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L345](https://github.com/Minecolonies/minecolonies/blob/69fd859289aee525d2551924f3260d76436ea757/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L345): Remove this unused private "clearStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L402](https://github.com/Minecolonies/minecolonies/blob/69fd859289aee525d2551924f3260d76436ea757/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L402): Remove this unused private "requestMaterials" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L458](https://github.com/Minecolonies/minecolonies/blob/69fd859289aee525d2551924f3260d76436ea757/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L458): Remove this unused private "structureStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L512](https://github.com/Minecolonies/minecolonies/blob/69fd859289aee525d2551924f3260d76436ea757/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L512): Remove this unused private "decorationStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L770](https://github.com/Minecolonies/minecolonies/blob/69fd859289aee525d2551924f3260d76436ea757/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L770): Remove this unused private "completeBuild" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 24 issues
* MAJOR 20 major
* MINOR 4 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIBasic.java#L211](https://github.com/Minecolonies/minecolonies/blob/d11ab1fc0567b6e1b15eb327a0ff682261b1ccf6/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L211): Remove this unused private "initSafetyChecks" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [AbstractEntityAIBasic.java#L647](https://github.com/Minecolonies/minecolonies/blob/d11ab1fc0567b6e1b15eb327a0ff682261b1ccf6/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L647): Remove this unused private "dumpInventory" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L244](https://github.com/Minecolonies/minecolonies/blob/d11ab1fc0567b6e1b15eb327a0ff682261b1ccf6/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L244): Remove this unused private "startWorkingAtOwnBuilding" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L345](https://github.com/Minecolonies/minecolonies/blob/d11ab1fc0567b6e1b15eb327a0ff682261b1ccf6/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L345): Remove this unused private "clearStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L402](https://github.com/Minecolonies/minecolonies/blob/d11ab1fc0567b6e1b15eb327a0ff682261b1ccf6/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L402): Remove this unused private "requestMaterials" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L458](https://github.com/Minecolonies/minecolonies/blob/d11ab1fc0567b6e1b15eb327a0ff682261b1ccf6/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L458): Remove this unused private "structureStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L512](https://github.com/Minecolonies/minecolonies/blob/d11ab1fc0567b6e1b15eb327a0ff682261b1ccf6/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L512): Remove this unused private "decorationStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L770](https://github.com/Minecolonies/minecolonies/blob/d11ab1fc0567b6e1b15eb327a0ff682261b1ccf6/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L770): Remove this unused private "completeBuild" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 17 issues
* MAJOR 14 major
* MINOR 3 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIBasic.java#L211](https://github.com/Minecolonies/minecolonies/blob/2044cb419730133d698b53c0d5a4f217ca3ebf0f/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L211): Remove this unused private "initSafetyChecks" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [AbstractEntityAIBasic.java#L647](https://github.com/Minecolonies/minecolonies/blob/2044cb419730133d698b53c0d5a4f217ca3ebf0f/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L647): Remove this unused private "dumpInventory" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L244](https://github.com/Minecolonies/minecolonies/blob/2044cb419730133d698b53c0d5a4f217ca3ebf0f/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L244): Remove this unused private "startWorkingAtOwnBuilding" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L345](https://github.com/Minecolonies/minecolonies/blob/2044cb419730133d698b53c0d5a4f217ca3ebf0f/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L345): Remove this unused private "clearStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L402](https://github.com/Minecolonies/minecolonies/blob/2044cb419730133d698b53c0d5a4f217ca3ebf0f/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L402): Remove this unused private "requestMaterials" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L458](https://github.com/Minecolonies/minecolonies/blob/2044cb419730133d698b53c0d5a4f217ca3ebf0f/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L458): Remove this unused private "structureStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L512](https://github.com/Minecolonies/minecolonies/blob/2044cb419730133d698b53c0d5a4f217ca3ebf0f/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L512): Remove this unused private "decorationStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L770](https://github.com/Minecolonies/minecolonies/blob/2044cb419730133d698b53c0d5a4f217ca3ebf0f/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L770): Remove this unused private "completeBuild" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by Kostronor** [comment]
:shipit: @cltnschlosser

**Comment by Raycoms** [comment]
@Kostronor @cltnschlosser I think we are ready to go. Sorry for the "double stuff" in the inventories but it seems like we have to do this to guarantee consistency.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 17 issues
* MAJOR 14 major
* MINOR 3 minor

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIBasic.java#L211](https://github.com/Minecolonies/minecolonies/blob/7132a1e154f409b0dd8a7421c62da82800982b5e/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L211): Remove this unused private "initSafetyChecks" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [AbstractEntityAIBasic.java#L647](https://github.com/Minecolonies/minecolonies/blob/7132a1e154f409b0dd8a7421c62da82800982b5e/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L647): Remove this unused private "dumpInventory" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L244](https://github.com/Minecolonies/minecolonies/blob/7132a1e154f409b0dd8a7421c62da82800982b5e/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L244): Remove this unused private "startWorkingAtOwnBuilding" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L345](https://github.com/Minecolonies/minecolonies/blob/7132a1e154f409b0dd8a7421c62da82800982b5e/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L345): Remove this unused private "clearStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L402](https://github.com/Minecolonies/minecolonies/blob/7132a1e154f409b0dd8a7421c62da82800982b5e/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L402): Remove this unused private "requestMaterials" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L458](https://github.com/Minecolonies/minecolonies/blob/7132a1e154f409b0dd8a7421c62da82800982b5e/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L458): Remove this unused private "structureStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L512](https://github.com/Minecolonies/minecolonies/blob/7132a1e154f409b0dd8a7421c62da82800982b5e/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L512): Remove this unused private "decorationStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L770](https://github.com/Minecolonies/minecolonies/blob/7132a1e154f409b0dd8a7421c62da82800982b5e/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L770): Remove this unused private "completeBuild" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

File: src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java [hunk 203]
```diff
@@ -733,12 +724,9 @@ else if (direction == 4)
                 for (int y = 0; y <= 4; y++)
                 {
                     BlockPos curBlock = new BlockPos(mineNode.getX() + x, standingPosition.getY() + y, mineNode.getZ() + z);
-                    if (((Math.abs(x) >= 2) && (Math.abs(z) >= 2)) || (getBlock(curBlock) != Blocks.air) || (y < 1) || (y > 3))
+                    if ((((Math.abs(x) >= 2) && (Math.abs(z) >= 2)) || (getBlock(curBlock) != Blocks.air) || (y < 1) || (y > 3)) && !secureBlock(curBlock, standingPosition))
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java]: MAJOR Reduce the number of conditional operators (5) used in the expression (maximum allowed 4). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1067)

File: src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java [hunk 204]
```diff
@@ -99,7 +94,7 @@ private AIState startWorkingAtOwnBuilding()
 
     private AIState prepareForMining()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java]: MAJOR Remove this unused private "prepareForMining" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 25 issues
* MAJOR 22 major
* MINOR 3 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIBasic.java#L211](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L211): Remove this unused private "initSafetyChecks" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [AbstractEntityAIBasic.java#L647](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIBasic.java#L647): Remove this unused private "dumpInventory" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L244](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L244): Remove this unused private "startWorkingAtOwnBuilding" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L345](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L345): Remove this unused private "clearStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L402](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L402): Remove this unused private "requestMaterials" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L458](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L458): Remove this unused private "structureStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L512](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L512): Remove this unused private "decorationStep" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureBuilder.java#L770](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L770): Remove this unused private "completeBuild" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureMiner.java#L85](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java#L85): Remove this unused private "startWorkingAtOwnBuilding" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. MAJOR [EntityAIStructureMiner.java#L115](https://github.com/Minecolonies/minecolonies/blob/61cfbd16323e55bf8a7b282c0eb92b5b57581c78/src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java#L115): Remove this unused private "goToLadder" method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 10 issues
* MAJOR 7 major
* MINOR 3 minor

Watch the comments in this conversation to review them.

**Comment by Raycoms** [comment]
@cltnschlosser Can we pull this?

File: src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java [hunk 205]
```diff
@@ -725,6 +751,27 @@ else if (direction == 4)
...
 
+
+        //Check for liquids
+        for (int x = -NODE_DISTANCE / 2 - 1; x <= NODE_DISTANCE / 2 + 1; x++)
+        {
+            for (int z = -NODE_DISTANCE / 2 - 1; z <= NODE_DISTANCE / 2 + 1; z++)
+            {
+                for (int y = -1; y <= 5; y++)
+                {
+                    BlockPos curBlock = new BlockPos(mineNode.getX() + x, standingPosition.getY() + y, mineNode.getZ() + z);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java]: MINOR Local variable 'curBlock' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java [hunk 206]
```diff
@@ -725,6 +751,27 @@ else if (direction == 4)
...
+                    Block block = getBlock(curBlock);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/miner/EntityAIStructureMiner.java]: MINOR Local variable 'block' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIInteract.java [hunk 207]
```diff
@@ -79,9 +78,14 @@ protected final boolean mineBlock(@NotNull final BlockPos blockToMine, @NotNull
...
         Block curBlock = world.getBlockState(blockToMine).getBlock();
         if (curBlock == null
-            || curBlock.equals(Blocks.air)
-            || BlockUtils.shouldNeverBeMessedWith(curBlock))
+              || curBlock.equals(Blocks.air)
+              || (curBlock.getMaterial().isLiquid())
+              || BlockUtils.shouldNeverBeMessedWith(curBlock))
         {
+            if(curBlock != null
+                 && curBlock.getMaterial().isLiquid()){
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIInteract.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 15 issues
* MAJOR 8 major
* MINOR 7 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [AbstractEntityAIInteract.java#L77](https://github.com/Minecolonies/minecolonies/blob/bec1b22afe15872b1df9dc454a2fa1d2d0a05183/src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIInteract.java#L77): The Cyclomatic Complexity of this method "mineBlock" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 208]
```diff
@@ -13,6 +25,30 @@ protected BlockHutFarmer()
     }
 
     @Override
+    public void onBlockPlacedBy(World worldIn, BlockPos pos, IBlockState state, EntityLivingBase placer, ItemStack stack)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: Can this be inherited?

File: src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java (hunk 189 above)
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/client/gui/WindowHutFarmer.java]: Should probably have a space too

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java (hunk 208 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: You're right.

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 209]
```diff
@@ -423,6 +450,22 @@ public void onWorldTick(TickEvent.WorldTickEvent event)
     }
 
     /**
+     * Updates all subscribers of fields etc.
+     */
+    private void markFieldsDirty()
+    {
+        ColonyManager.markDirty();
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/Colony.java]: Do we want to do a full markDirty? or does this just queue the dirty things to sync?

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 210]
```diff
@@ -423,6 +450,22 @@ public void onWorldTick(TickEvent.WorldTickEvent event)
...
+
+        for (AbstractBuilding building : buildings.values())
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/Colony.java]: The mark dirty method should not be the one sending the packets. Thats should happen once per tick if dirty

File: src/main/java/com/minecolonies/colony/Colony.java (hunk 209 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/colony/Colony.java]: I think it only synchs the dirty things.

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 211]
```diff
@@ -1062,4 +1186,13 @@ public void onBuildingUpgradeComplete(AbstractBuilding building, int level)
     {
         return ServerUtils.getPlayersFromUUID(this.world, this.getPermissions().getMessagePlayers());
     }
+
+    /**
+     * Removes a field from the farmerFields list.
+     * @param pos the position-id.
+     */
+    public void removeField(final BlockPos pos)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/Colony.java]: Probably need a markDirty

File: src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java [hunk 212]
```diff
@@ -0,0 +1,88 @@
...
+    public void fromBytes(ByteBuf buf)
+    {
+        colonyId = buf.readInt();
+        buildingId = BlockPosUtil.readFromByteBuf(buf);
+        assign = buf.readBoolean();
+        field = BlockPosUtil.readFromByteBuf(buf);
+    }
+
+    @Override
+    public IMessage onMessage(AssignFieldMessage message, MessageContext ctx)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java]: Do permissions check. Always :)

File: src/main/resources/assets/minecolonies/lang/en_US.lang [hunk 213]
```diff
@@ -75,6 +75,23 @@ com.minecolonies.gui.hiring.off=Automatic
 com.minecolonies.gui.workerHuts.settings=Settings
 achievement.size.town=Town
 tile.minecolonies.blockHutTownHall.name=Town Hall
+tile.minecolonies.blockSubstitution.name=SchematicPlaceholder.
+
```
Comment (cltnschlosser) [inline src/main/resources/assets/minecolonies/lang/en_US.lang]: Can you add all these to POE?

File: src/main/java/com/minecolonies/colony/Colony.java (hunk 209 above)
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/Colony.java]: Check on that.

File: src/main/resources/assets/minecolonies/lang/en_US.lang (hunk 213 above)
Comment (Raycoms) [inline src/main/resources/assets/minecolonies/lang/en_US.lang]: I added all new farmer ones to POE already.

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 214]
```diff
@@ -544,6 +541,26 @@ public void updateSubscribers()
     }
 
     /**
+     * Sends packages to update the fields.
+     *
+     * @param oldSubscribers    the existing subscribers.
+     * @param hasNewSubscribers the new subscribers.
+     */
+    private void sendFieldPackets(Set<EntityPlayerMP> oldSubscribers, boolean hasNewSubscribers)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/Colony.java]: So is this covered by the sendBuildingPackets?

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 215]
```diff
@@ -532,8 +525,12 @@ public void updateSubscribers()
 
             //Buildings
             sendBuildingPackets(oldSubscribers, hasNewSubscribers);
+
+            //Fields
+            sendFieldPackets(oldSubscribers, hasNewSubscribers);
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/Colony.java]: I think this should need to be placed somewhere else as well. With an if (isDirty) check

File: src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java [hunk 216]
```diff
@@ -69,6 +70,12 @@ public IMessage onMessage(AssignFieldMessage message, MessageContext ctx)
         final Colony colony = ColonyManager.getColony(message.colonyId);
         if (colony != null)
         {
+            //Verify player has permission to do edit permissions
+            if(!colony.getPermissions().hasPermission(ctx.getServerHandler().playerEntity, Permissions.Action.SEND_MESSAGES))
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java]: That might be has permission to get citizens conversations. the OPEN_HUTS permission is usually a pretty good one.

Comment (cltnschlosser) [inline src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java]: Also you probably need to add a check to your other packet as well.

File: src/main/java/com/minecolonies/colony/Colony.java (hunk 214 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/colony/Colony.java]: Yeah I set it inside the buildingView.

File: src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java (hunk 216 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/network/messages/AssignFieldMessage.java]: Edited and added to other messages as well.

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 217]
```diff
@@ -544,6 +541,26 @@ public void updateSubscribers()
...
 
     /**
+     * Sends packages to update the fields.
+     *
+     * @param oldSubscribers    the existing subscribers.
+     * @param hasNewSubscribers the new subscribers.
+     */
+    private void sendFieldPackets(Set<EntityPlayerMP> oldSubscribers, boolean hasNewSubscribers)
+    {
+        if (isBuildingsDirty || hasNewSubscribers)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/Colony.java]: This should be isFieldsDirty not isBuildingsDirty. Then you're all good

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 218]
```diff
@@ -1,4 +1,16 @@
 package com.minecolonies.blocks;
+
+import com.minecolonies.colony.Colony;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'com.minecolonies.colony.Colony'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 219]
```diff
@@ -1,4 +1,16 @@
...
+import com.minecolonies.colony.ColonyManager;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'com.minecolonies.colony.ColonyManager'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 220]
```diff
@@ -1,4 +1,16 @@
...
+import com.minecolonies.tileentities.TileEntityColonyBuilding;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'com.minecolonies.tileentities.TileEntityColonyBuilding'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 221]
```diff
@@ -1,4 +1,16 @@
...
+import net.minecraft.block.state.IBlockState;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'net.minecraft.block.state.IBlockState'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 222]
```diff
@@ -1,4 +1,16 @@
...
+import net.minecraft.entity.EntityLivingBase;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'net.minecraft.entity.EntityLivingBase'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 223]
```diff
@@ -1,4 +1,16 @@
...
+import net.minecraft.entity.player.EntityPlayer;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'net.minecraft.entity.player.EntityPlayer'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 224]
```diff
@@ -1,4 +1,16 @@
...
+import net.minecraft.item.ItemStack;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'net.minecraft.item.ItemStack'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 225]
```diff
@@ -1,4 +1,16 @@
...
+import net.minecraft.tileentity.TileEntity;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'net.minecraft.tileentity.TileEntity'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 226]
```diff
@@ -1,4 +1,16 @@
...
+import net.minecraft.util.BlockPos;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'net.minecraft.util.BlockPos'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/blocks/BlockHutFarmer.java [hunk 227]
```diff
@@ -1,4 +1,16 @@
...
+import net.minecraft.world.World;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/blocks/BlockHutFarmer.java]: MINOR Remove this unused import 'net.minecraft.world.World'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIInteract.java [hunk 228]
```diff
@@ -85,6 +85,10 @@ protected final boolean mineBlock(@NotNull final BlockPos blockToMine, @NotNull
               || curBlock.equals(Blocks.air)
               || BlockUtils.shouldNeverBeMessedWith(curBlock))
         {
+            if(curBlock != null
+                 && curBlock.getMaterial().isLiquid()){
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/basic/AbstractEntityAIInteract.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 229]
```diff
@@ -501,6 +544,26 @@ public void updateSubscribers()
     }
 
     /**
+     * Sends packages to update the fields.
+     *
+     * @param oldSubscribers    the existing subscribers.
+     * @param hasNewSubscribers the new subscribers.
+     */
+    private void sendFieldPackets(Set<EntityPlayerMP> oldSubscribers, boolean hasNewSubscribers)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Remove this unused method parameter "oldSubscribers". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1172)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 230]
```diff
@@ -501,6 +544,26 @@ public void updateSubscribers()
...
+    {
+        if (isFieldsDirty && !isBuildingsDirty || hasNewSubscribers)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Add parentheses to make the operator precedence explicit. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS864)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 26 issues
* MAJOR 9 major
* MINOR 17 minor

Watch the comments in this conversation to review them.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 16 issues
* MAJOR 9 major
* MINOR 7 minor

Watch the comments in this conversation to review them.

**Comment by cltnschlosser** [comment]
👍

**Comment by Kostronor** [comment]
:shipit:

**Comment by cltnschlosser** [comment]
👍
