### PR TITLE
Hotfix/#110 crash

### LINKED ISSUE #110: Crash on Building placed
### Minecolonies version
v714
### Crashlog
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  BCModPlugin (zz-backpacks 1.8.9 - 3.1.0.jar)
  CoreMod (TickProfiler-1.8.9.jenkins.37.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.2.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 07/09/16 19:24
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at com.minecolonies.colony.Colony.cleanUpBuildings(Colony.java:765)
	at com.minecolonies.colony.Colony.onWorldTick(Colony.java:721)
	at com.minecolonies.colony.ColonyManager.lambda$onWorldTick$59(ColonyManager.java:500)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.minecolonies.colony.ColonyManager.onWorldTick(ColonyManager.java:500)
	at com.minecolonies.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:47)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_55_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:686)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 3.14.32-xxxx-std-ipv6-64-hz1000
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 143095768 bytes (136 MB) / 1175932928 bytes (1121 MB) up to 4151836672 bytes (3959 MB)
	JVM Flags: 20 total; -Xincgc -XX:+UseParNewGC -XX:MaxPermSize=256M -XX:NewRatio=2 -XX:CMSFullGCsBeforeCompaction=1 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=2048 -XX:+CMSParallelRemarkEnabled -XX:+DisableExplicitGC -Xnoclassgc -Xoss4M -Xss4M -XX:+UseFastAccessorMethods -XX:CMSInitiatingOccupancyFraction=90 -XX:UseSSE=4 -XX:+UseCMSCompactAtFullCollection -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -Xmx4096M -Xms512M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1855 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902.jar) 
	UCHIJAAAA	Forge{11.15.1.1855} [Minecraft Forge] (forge-1.8.9-11.15.1.1902.jar) 
	UCHIJAAAA	backpacks16840{3.1.0} [Backpacks!] (zz-backpacks 1.8.9 - 3.1.0.jar) 
	UCHIJAAAA	JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
	UCHIJAAAA	AppleCore{1.3.2} [AppleCore] (AppleCore-mc1.8.9-1.3.2.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	BaublesHud{2.2.1} [Baubles-Hud] (BaublesHud-2.2.1.jar) 
	UCHIJAAAA	BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
	UCHIJAAAA	Chameleon{1.8.9-1.1.5} [Chameleon] (Chameleon-1.8.9-1.1.5.jar) 
	UCHIJAAAA	k4lib{1.8.9-1.0.18} [K4Lib] (k4lib-1.8.9-1.0.18-universal.jar) 
	UCHIJAAAA	colorchat{1.8.8-1.0.2} [ColorChat] (colorchat-1.8.8-1.0.2-universal.jar) 
	UCHIJAAAA	EnjinMinecraftPlugin{2.4.9-1.8} [EnjinMinecraftPlugin] (EnjinMinecraftForgePlugin-1.8.9 (1).jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAA	hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
	UCHIJAAAA	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHIJAAAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAAAA	journeymap{1.8.9-5.2.4} [JourneyMap] (journeymap-1.8.9-5.2.4-unlimited.jar) 
	UCHIJAAAA	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHIJAAAA	minecolonies{1.8.9-0.4.714} [MineColonies] (minecolonies-universal-1.8.9-0.4.714.jar) 
	UCHIJAAAA	Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
	UCHIJAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.5.0.jar) 
	UCHIJAAAA	slackmc{0.6} [SlackMC] (SlackMC-1.8.9-0.7.jar) 
	UCHIJAAAA	StorageDrawers{1.8.9-2.7.0} [Storage Drawers] (StorageDrawers-1.8.9-2.7.0.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar) 
	UCHIJAAAA	TickProfiler{1.8.9.jenkins.37} [TickProfiler] (TickProfiler-1.8.9.jenkins.37.jar) 
	UCHIJAAAA	VeinMiner{0.34.1_1.8.9-9901a41} [Vein Miner] (VeinMiner-0.34.1-1.8.9r552+9901a41.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.34.1_1.8.9-9901a41} [Mod Support] (VeinMiner-0.34.1-1.8.9r552+9901a41.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar) 
	UCHIJAAAA	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	UCHIJAAAA	xprings{1.2.0} [Experience Rings] (xprings-1.2.0.jar) 
	UCHIJAAAA	denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.3.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
BCModPlugin (zz-backpacks 1.8.9 - 3.1.0.jar)
  brad16840.common.asm.ClassTransformer
CoreMod (TickProfiler-1.8.9.jenkins.37.jar)
  
AppleCore (AppleCore-mc1.8.9-1.3.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 4 / 999; [EntityPlayerMP['Kostronor'/269, l='world', x=76.22, y=72.00, z=252.08], EntityPlayerMP['SBOfficial'/39701, l='world', x=9.14, y=69.00, z=261.21], EntityPlayerMP['david08150815'/85073, l='world', x=6674.29, y=63.00, z=5043.66], EntityPlayerMP['Warrof'/109432, l='world', x=3976.56, y=53.00, z=4362.49]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #110

# Changes proposed in this pull request:
- Only iterate through copy of the colony.

Review please @Minecolonies/maintainers

### CODE REVIEW

File: src/main/java/com/minecolonies/colony/ColonyManager.java [hunk 1]
```diff
@@ -495,7 +495,9 @@ public static void onClientTick(@NotNull TickEvent.ClientTickEvent event)
     public static void onWorldTick(
                                     @NotNull TickEvent.WorldTickEvent event)
     {
-        colonies.values().stream()
+        Map<Integer, Colony> coloniesCopy = new HashMap<>(colonies);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/ColonyManager.java]: MINOR Local variable 'coloniesCopy' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 1 issue
* MINOR 1 minor

Watch the comments in this conversation to review them.

**Comment by Kostronor** [comment]
:shipit:
