### PR TITLE
Fix/#77lumberjackfixes

### LINKED ISSUE #75: Lumberjack does not recognize akazia if sideways
### Minecolonies version 
0.3.472

### Expected behavior
Find the tree and cut it down.

### Actual behaviour
Ignoring it.

### Steps to reproduce the problem
Have a tree like this:
```
OL
OL
LO
```

### LINKED ISSUE #98: lumberjack gets stuck when a tree spawns inside him :(
### Minecolonies version
0.3.472

### Expected behavior
lumberjack gets stuck when a tree spawns inside him, no idea if this has been fixed/reported (sorry if it has)

### Actual behaviour
gets stuck when a tree spawns inside him, see picture here: https://puu.sh/r0PCI/80ed26cfbd.png

### Steps to reproduce the problem

maybe have it notice when something spawns inside him, no idea. 

again, sorry if this has been reported, I didn't see any posts on this.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #98, 
Closes #75

# Changes proposed in this pull request:
- Fixes problem with tree recognition.
- Fixes problem with stuck in leafes
- Fixes problem with preplaced sapling
- Fixes problem with trying to reach out of reach saplings.

Review please @Minecolonies/maintainers

### CODE REVIEW

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 1]
```diff
@@ -193,13 +208,66 @@ public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
...
+        BlockPos basePos = baseAndTOp[0];
 
         //Make sure tree is on solid ground and tree is not build above cobblestone
         return world.getBlockState(basePos.down()).getMaterial().isSolid()
                  && world.getBlockState(basePos.down()).getBlock() != Blocks.COBBLESTONE
-                 && hasEnoughLeaves(world, pos);
+                 && hasEnoughLeaves(world, baseAndTOp[1]);
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 2]
```diff
@@ -193,13 +208,66 @@ public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
...
+        }
+
+        woodenBlocks.add(log);
+        for (int y = -1; y <= 1; y++)
+        {
+            for (int x = -1; x <= 1; x++)
+            {
+                for (int z = -1; z <= 1; z++)
+                {
+                    BlockPos temp = log.add(x, y, z);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: MINOR Local variable 'temp' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 3]
```diff
@@ -193,13 +208,66 @@ public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
...
+                 && hasEnoughLeaves(world, baseAndTOp[1]);
+    }
+
+    /**
+     * Adds a log and searches for further logs(Breadth first search)
+     *
+     * @param world The world the log is in
+     * @param log   the log to add
+     */
+    private static BlockPos[] getBottomAndTopLog(@NotNull IBlockAccess world, @NotNull BlockPos log, @NotNull LinkedList<BlockPos> woodenBlocks, BlockPos bottomLog,
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: MAJOR The Cyclomatic Complexity of this method "getBottomAndTopLog" is 13 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 4]
```diff
@@ -193,13 +208,66 @@ public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
...
+        BlockPos[] baseAndTOp = getBottomAndTopLog(world, pos, new LinkedList<>(), null, null);
+
+        if(baseAndTOp == null || baseAndTOp.length < 2)
+        {
+            return false;
+        }
+
         //Get base log, should already be base log
-        BlockPos basePos = getBaseLog(world, pos);
+        BlockPos basePos = baseAndTOp[0];
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: MINOR Local variable 'basePos' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 4 issues
* MAJOR 1 major
* MINOR 3 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 5]
```diff
@@ -193,13 +208,66 @@ public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
...
+                 && hasEnoughLeaves(world, baseAndTOp[1]);
+    }
+
+    /**
+     * Adds a log and searches for further logs(Breadth first search).
+     *
+     * @param world The world the log is in.
+     * @param log   the log to add.
+     */
+    private static BlockPos[] getBottomAndTopLog(@NotNull IBlockAccess world, @NotNull BlockPos log, @NotNull LinkedList<BlockPos> woodenBlocks, BlockPos bottomLog,
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: MAJOR The Cyclomatic Complexity of this method "getBottomAndTopLog" is 13 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 1 issue
* MAJOR 1 major

Watch the comments in this conversation to review them.

**Comment by Kostronor** [comment]
:+1: Waiting for @cltnschlosser review

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 6]
```diff
@@ -116,7 +116,7 @@
     /**
      * Vertical range in which the lumberjack picks up items
      */
-    private static final float RANGE_VERTICAL_PICKUP   = 15.0F;
+    private static final float RANGE_VERTICAL_PICKUP   = 3.0F;
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Why was this ever 15, geez.

File: src/main/java/com/minecolonies/entity/EntityCitizen.java [hunk 7]
```diff
@@ -625,7 +626,8 @@ public void onLivingUpdate()
             cleanupChatMessages();
             updateColonyServer();
         }
-        if (isEntityInsideOpaqueBlock())
+
+        if (isEntityInsideOpaqueBlock() || isInsideOfMaterial(Material.LEAVES))
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/EntityCitizen.java]: We don't want citizens standing in leaves, okay.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 8]
```diff
@@ -414,7 +414,7 @@ private void tryGettingUnstuckFromLeaves()
      */
     private boolean plantSapling(@NotNull BlockPos location)
     {
-        if (BlockPosUtil.getBlock(world, location) != Blocks.AIR)
+        if (BlockPosUtil.getBlock(world, location) != Blocks.AIR && !(world.getBlockState(location).getBlock() instanceof BlockSapling))
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: Lets save this block to a variable, so that we don't have to find it multiple times.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 9]
```diff
@@ -105,18 +115,23 @@ else if(block instanceof BlockNewLog)
             }
 
             location = getBaseLog(world, log);
+            topLog = getTopLog(world, log);
+
             woodBlocks = new LinkedList<>();
+            addAndSearch(world, location);
+
             checkTree(world, getTopLog(world, log));
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: Remove the method call and just use the topLog variable.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 10]
```diff
@@ -105,18 +115,23 @@ else if(block instanceof BlockNewLog)
...
             stumpLocations = new ArrayList<>();
+            woodBlocks = new LinkedList<>();
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: Why are we reseting woodBlocks, and if that was intended, would clear be better? (<- legitimate question it could be worse)

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 11]
```diff
@@ -193,13 +208,66 @@ public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
...
+
+        woodenBlocks.add(log);
+        for (int y = -1; y <= 1; y++)
+        {
+            for (int x = -1; x <= 1; x++)
+            {
+                for (int z = -1; z <= 1; z++)
+                {
+                    final BlockPos temp = log.add(x, y, z);
+                    if (world.getBlockState(temp).getBlock().isWood(null, new BlockPos(0, 0, 0)) && !woodenBlocks.contains(temp))
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: lets use temp instead of `new BlockPos(0, 0, 0);`

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 12]
```diff
@@ -290,21 +358,36 @@ public void fillTreeStumps(@NotNull World world, int yLevel)
...
+     * @param log   the log to add.
      */
     private void addAndSearch(@NotNull World world, @NotNull BlockPos log)
     {
+        if(woodBlocks.size() >= MAX_TREE_SIZE)
+        {
+            return;
+        }
+
+        if(log.getY() < location.getY())
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: Whats the point of even checking for getTopLog and getBaseLog if we are going to redo the check here. And why is this needed?

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 13]
```diff
@@ -193,13 +208,66 @@ public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
             return false;
         }
 
-        //Get base log, should already be base log
-        BlockPos basePos = getBaseLog(world, pos);
+        final BlockPos[] baseAndTOp = getBottomAndTopLog(world, pos, new LinkedList<>(), null, null);
+
+        if(baseAndTOp == null || baseAndTOp.length < 2)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: getBottomAndTop log never returns null or anything that isn't length 2. So we don't need to do this runtime check.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 14]
```diff
@@ -193,13 +208,66 @@ public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
             return false;
         }
 
-        //Get base log, should already be base log
-        BlockPos basePos = getBaseLog(world, pos);
+        final BlockPos[] baseAndTOp = getBottomAndTopLog(world, pos, new LinkedList<>(), null, null);
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: I think this should either return some sort of tuple object or set the value of this tree's top and base logs.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java (hunk 10 above)
Comment (Kostronor) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: clear is better from an encapsulation perspective. We have to ask us: "Do we want LinkedList or ArrayList?" And with clear we don't have to decide this every time anew.
Performance wise .clear is faster as we already have a decent sized list (cleared in O(n)). But always use .clear and not .removeAll

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java (hunk 13 above)
Comment (Kostronor) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: Agreed. Having an @NotNull would have helped there :P

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java (hunk 14 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: Yeah but it is static we have no tree in that given moment.

Comment (Kostronor) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: Then go for the Tuple object

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java (hunk 12 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: Yeah I removed the topLog and BaseLog call, no sense in calling it, haven't noticed them.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java (hunk 11 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: CopyPaste error.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java [hunk 15]
```diff
@@ -414,7 +414,8 @@ private void tryGettingUnstuckFromLeaves()
      */
     private boolean plantSapling(@NotNull BlockPos location)
     {
-        if (BlockPosUtil.getBlock(world, location) != Blocks.AIR)
+        Block worldBlock = world.getBlockState(location).getBlock();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java]: MINOR Local variable 'worldBlock' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/event/EventHandler.java [hunk 16]
```diff
@@ -23,11 +24,26 @@
 import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
+import java.util.ArrayList;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/event/EventHandler.java]: MINOR Remove this unused import 'java.util.ArrayList'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/event/EventHandler.java [hunk 17]
```diff
@@ -23,11 +24,26 @@
...
+    /**
+     * Event called when the debug screen is opened.
+     * Event gets cancelled when there no permission to break a hut
+     *
+     * @param event {@link net.minecraftforge.client.event.RenderGameOverlayEvent}
+     */
+    @SubscribeEvent
+    public void onDebugScreenObened(@NotNull RenderGameOverlayEvent.Text event)
+    {
+        System.out.println("workinnn");
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/event/EventHandler.java]: MAJOR Replace this usage of System.out or System.err by a logger. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS106)

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 18]
```diff
@@ -162,59 +164,88 @@ private void checkTree(@NotNull World world, @NotNull BlockPos topLog)
...
      *
-     * @param world the world
-     * @param pos   The coordinates
-     * @return true if the log is part of a tree
+     * @param world The world the log is in.
+     * @param log   the log to add.
      */
-    public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
+    @NotNull
+    private static Tuple<BlockPos, BlockPos> getBottomAndTopLog(@NotNull IBlockAccess world, @NotNull BlockPos log, @NotNull LinkedList<BlockPos> woodenBlocks, BlockPos bottomLog,
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: MAJOR The Cyclomatic Complexity of this method "getBottomAndTopLog" is 13 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 19]
```diff
@@ -275,7 +309,7 @@ public void findLogs(@NotNull World world)
      * Checks if the tree has been planted from more than 1 saplings.
      * Meaning that more than 1 log is on the lowest level.
      *
-     * @param world  The world where the tree is in
+     * @param world  The world where the tree is in.
      * @param yLevel The base y.
      */
     public void fillTreeStumps(@NotNull World world, int yLevel)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: MAJOR Remove this unused method parameter "world". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1172)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 5 issues
* MAJOR 3 major
* MINOR 2 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/event/EventHandler.java (hunk 17 above)
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/event/EventHandler.java]: Can just remove this, also typo in method named.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 20]
```diff
@@ -9,6 +9,7 @@
 import net.minecraft.init.Blocks;
 import net.minecraft.nbt.NBTTagCompound;
 import net.minecraft.nbt.NBTTagList;
+import net.minecraft.util.Tuple;
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: This is new, and cool.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 21]
```diff
@@ -259,30 +225,27 @@ public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
...
                     }
                 }
             }
         }
 
-        return new BlockPos[]{bottom, top};
+        return new Tuple<>(bottom, top);
     }
 
     private static boolean hasEnoughLeaves(@NotNull IBlockAccess world, BlockPos pos)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: pos is now required to be the top log pos, we should document that

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 22]
```diff
@@ -284,27 +318,34 @@ public void fillTreeStumps(@NotNull World world, int yLevel)
...
+        }
+
+        if(log.getY() > topLog.getY())
+        {
+            topLog = log;
+        }
+
         woodBlocks.add(log);
         for (int y = -1; y <= 1; y++)
         {
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: Line:357 replace new BlockPos(0,0,0) with temp

File: src/main/java/com/minecolonies/event/EventHandler.java (hunk 17 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/event/EventHandler.java]: Yeah wow I thought I discarded this.

File: src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java [hunk 23]
```diff
@@ -162,59 +164,90 @@ private void checkTree(@NotNull World world, @NotNull BlockPos topLog)
...
-     * @param pos   The coordinates
-     * @return true if the log is part of a tree
+     * @param world The world the log is in.
+     * @param log   the log to add.
+     *
+     * @return a tuple containing, first: bottom log and second: top log.
      */
-    public static boolean checkTree(@NotNull IBlockAccess world, BlockPos pos)
+    @NotNull
+    private static Tuple<BlockPos, BlockPos> getBottomAndTopLog(@NotNull IBlockAccess world, @NotNull BlockPos log, @NotNull LinkedList<BlockPos> woodenBlocks, BlockPos bottomLog,
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/lumberjack/Tree.java]: MAJOR The Cyclomatic Complexity of this method "getBottomAndTopLog" is 13 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 1 issue
* MAJOR 1 major

Watch the comments in this conversation to review them.

**Comment by Kostronor** [comment]
:shipit:
