### PR TITLE
Should fix the workOrder problems.

### LINKED ISSUE #55: Crash when terminating running workOrder
### Minecolonies version
The newest release
### Expected behavior
No crash
### Actual behaviour
Crash
### Steps to reproduce the problem
Terminate build workOrder which is running atm.

### PR DESCRIPTION
**Pull request by Raycoms**
Fixes Some bug where we don't have any issue yet

Closes #55 
# Changes proposed in this pull request:
- Crash when cancelling a workOrder the builder was working on.
-
-

Review please @Minecolonies/maintainers

### CODE REVIEW

File: src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 1]
```diff
@@ -103,7 +103,14 @@ private boolean checkIfExecute()
         }
 
         WorkOrderBuild wo = job.getWorkOrder();
-        if (wo == null || (job.getColony().getBuilding(wo.getBuildingLocation()) == null && !(wo instanceof WorkOrderBuildDecoration)))
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: I like this change a lot! more readable!

**Comment by Kostronor** [comment]
:shipit: I like the change!

File: src/main/java/com/minecolonies/util/SchematicWrapper.java [hunk 2]
```diff
@@ -548,7 +548,7 @@ public boolean findNextBlockToClear()
 
         }
         //Check for air blocks and if blocks below the hut are different from the schematicWorld
-        while((worldBlockAir() || (progressPos.getY() <= getOffset().getY() && doesSchematicBlockEqualWorldBlock())) && count < Configurations.maxBlocksCheckedByBuilder);
+        while((worldBlockAir() ||  doesSchematicBlockEqualWorldBlock()) && count < Configurations.maxBlocksCheckedByBuilder);
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/util/SchematicWrapper.java]: We don't want to do this, we kept this so that we don't create giant holes in the ground. In theory the placeholder block should fix this, but we haven't implemented it fully in all our schematics.

File: src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 3]
```diff
@@ -820,14 +834,20 @@ private AIState completeBuild()
...
 
-        job.complete();
         resetTask();
         worker.addExperience(XP_EACH_BUILDING);
         workFrom = null;
 
         return AIState.IDLE;
     }
 
+    private void cancelWork()
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: I think we should just override resetTask, call super and add the rest of this. Seems like what this method was created for.

File: src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 4]
```diff
@@ -523,6 +531,11 @@ private AIState structureStep()
 
     private AIState decorationStep()
     {
+        if(job.getWorkOrder() == null)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: Doesn't seem like we need this, this check is done in checkIfExecute, also you didn't add it to any of the other steps.

File: src/main/java/com/minecolonies/util/SchematicWrapper.java (hunk 2 above)
Comment (Raycoms) [inline src/main/java/com/minecolonies/util/SchematicWrapper.java]: Shouldn't he now compare all the blocks?
Previously he only compared the ones < y now he compares all of them?

Comment (cltnschlosser) [inline src/main/java/com/minecolonies/util/SchematicWrapper.java]: Yea, its fine.

File: src/main/java/com/minecolonies/entity/ai/basic/AbstractAISkeleton.java [hunk 5]
```diff
@@ -105,7 +105,7 @@ public final boolean shouldExecute()
      * Resets the task
      */
     @Override
-    public final void resetTask()
+    public void resetTask()
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/entity/ai/basic/AbstractAISkeleton.java]: you have to call super if you override

Comment (Kostronor) [inline src/main/java/com/minecolonies/entity/ai/basic/AbstractAISkeleton.java]: Well fail on me, ignore that

File: src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java [hunk 6]
```diff
@@ -93,6 +92,19 @@ public EntityAIStructureBuilder(JobBuilder job)
         worker.setCanPickUpLoot(true);
     }
 
+    private boolean checkIfCanceled()
+    {
+        WorkOrderBuild wo = job.getWorkOrder();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/entity/ai/citizen/builder/EntityAIStructureBuilder.java]: MINOR Local variable 'wo' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 1 issue
* MINOR 1 minor

Watch the comments in this conversation to review them.

**Comment by Kostronor** [comment]
:+1: this time for real :wink:

**Comment by Raycoms** [comment]
:shipit: Tested it a bit works quite fine now, @cltnschlosser

**Comment by cltnschlosser** [comment]
👍
