### PR TITLE
Fixing #160.  build tool crashes on building placement with a null/0 …

### LINKED ISSUE #160: Crash when placing buildings with buildTool in 1.10
### Minecolonies version
Newest 1.10 build.
### Expected behavior
Correctly place the building.
### Actual behaviour
Crash due to a missing colony id in the tileEntity.
### Steps to reproduce the problem
Place the building with the build tool.

### PR DESCRIPTION
**Pull request by DarVillous**
Closes #160 build tool crashes when placing buildings

# Changes proposed in this pull request:
- Minor changes to lgging around creation of colonies and buildings
- Removes server side exception we threw and replaced it with a server log
- Set the colony on the abstract building in the BuildToolPlaceMessage

Review please @Minecolonies/maintainers

…id colony.

### CODE REVIEW

File: src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java [hunk 1]
```diff
@@ -169,6 +169,18 @@ private static void handleHut(@NotNull World world, @NotNull EntityPlayer player
 
             if (building != null)
             {
+                if(building.getTileEntity()!= null)
+                {
+                    Colony colony=ColonyManager.getColony(world,buildPos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java [hunk 2]
```diff
@@ -169,6 +169,18 @@ private static void handleHut(@NotNull World world, @NotNull EntityPlayer player
...
+                    if(colony!=null)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java]: MAJOR Avoid if (x != y) ..; else ..; [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AConfusingTernary)

File: src/main/java/com/minecolonies/tileentities/TileEntityColonyBuilding.java [hunk 3]
```diff
@@ -6,6 +6,8 @@
 import com.minecolonies.colony.buildings.AbstractBuilding;
 import com.minecolonies.colony.materials.MaterialSystem;
 import com.minecolonies.colony.permissions.Permissions;
+import com.minecolonies.util.Log;
+import com.sun.javafx.binding.Logging;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/tileentities/TileEntityColonyBuilding.java]: MAJOR Replace this usage of Sun classes by ones from the Java API. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1191)
MINOR Remove this unused import 'com.sun.javafx.binding.Logging'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 4 issues
* MAJOR 2 major
* MINOR 2 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java [hunk 4]
```diff
@@ -169,6 +168,18 @@ private static void handleHut(@NotNull World world, @NotNull EntityPlayer player
 
             if (building != null)
             {
+                if (building.getTileEntity() != null)
+                {
+                    Colony colony = ColonyManager.getColony(world, buildPos);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java]: MINOR Local variable 'colony' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java [hunk 5]
```diff
@@ -169,6 +168,18 @@ private static void handleHut(@NotNull World world, @NotNull EntityPlayer player
...
+                    if (colony != null)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java]: MAJOR Avoid if (x != y) ..; else ..; [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3AConfusingTernary)

File: src/main/java/com/minecolonies/tileentities/TileEntityColonyBuilding.java (hunk 3 above)
Comment (DarVillous) [inline src/main/java/com/minecolonies/tileentities/TileEntityColonyBuilding.java]: It shall be done....

File: src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java (hunk 4 above)
Comment (DarVillous) [inline src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java]: Finally, I mean ok.

File: src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java (hunk 5 above)
Comment (DarVillous) [inline src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java]: it's called "happy path first".  but alright.

File: src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java [hunk 6]
```diff
@@ -167,14 +166,26 @@ private static void handleHut(@NotNull World world, @NotNull EntityPlayer player
 
             @Nullable AbstractBuilding building = ColonyManager.getBuilding(world, buildPos);
 
-            if (building != null)
+            if (building == null)
             {
-                building.setStyle(style);
-                building.setRotation(rotation);
+                Log.getLogger().error("BuildTool: building is null!");
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java]: we could do an early return here

```
if null
  log
  return

go on
```

File: src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java [hunk 7]
```diff
@@ -167,14 +166,26 @@ private static void handleHut(@NotNull World world, @NotNull EntityPlayer player
...
+                    else
+                    {
+                        building.getTileEntity().setColony(colony);
+                    }
+                }
+                building.setStyle(style);
+                building.setRotation(rotation);
             }
         }
         else
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/network/messages/BuildToolPlaceMessage.java]: We could do the same with this else. For me it would make the code much more readable.

**Comment by Kostronor** [comment]
:shipit:

**Comment by Raycoms** [comment]
:shipit:

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [TileEntityColonyBuilding.java#L113](https://github.com/Minecolonies/minecolonies/blob/f693841beb4ca1f9a9c2c86c5811acbb931feb94/src/main/java/com/minecolonies/tileentities/TileEntityColonyBuilding.java#L113): The Cyclomatic Complexity of this method "updateColonyReferences" is 11 which is greater than 10 authorized. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by Raycoms** [comment]
:shipit:

**Comment by Kostronor** [comment]
:+1:

**Comment by Raycoms** [comment]
:shipit:

**Comment by Raycoms** [comment]
:+1:

**Comment by Raycoms** [comment]
:+1:
