### PR TITLE
HOTFIXED

### LINKED ISSUE #79: Size Achievement trigger bug & enhancement
```
[20:11:42] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
        at com.minecolonies.colony.Colony.lambda$checkAchievements$12(Colony.java:728) ~[Colony.class:?]
        at com.minecolonies.colony.Colony.lambda$null$15(Colony.java:743) ~[Colony.class:?]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_101]
        at com.minecolonies.colony.Colony.lambda$checkAchievements$16(Colony.java:743) ~[Colony.class:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_101]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_101]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_101]
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_101]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_101]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_101]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_101]
        at com.minecolonies.colony.Colony.checkAchievements(Colony.java:743) ~[Colony.class:?]
        at com.minecolonies.colony.Colony.spawnCitizen(Colony.java:710) ~[Colony.class:?]
        at com.minecolonies.colony.Colony.spawnCitizen(Colony.java:665) ~[Colony.class:?]
        at com.minecolonies.colony.Colony.onWorldTick(Colony.java:411) ~[Colony.class:?]
        at com.minecolonies.colony.ColonyManager.lambda$onWorldTick$62(ColonyManager.java:419) ~[ColonyManager.class:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_101]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_101]
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_101]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_101]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_101]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_101]
        at com.minecolonies.colony.ColonyManager.onWorldTick(ColonyManager.java:419) ~[ColonyManager.class:?]
        at com.minecolonies.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:46) ~[FMLEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:274) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:686) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[20:11:42] [Server thread/ERROR]: This crash report has been saved to: /home/marvin/Minecraft/MineColonies/MinecolonyMain/./crash-reports/crash-2016-08-31_20.11.42-server.txt
```

Fixing this and enhancing the `MineColonies` Achievements as this:
- Colony achievements mainly trigger on the `owner`!
- Then each achievement taken by the owner will be triggered on each `player` in the permission list
- If a new `player` joins the colony, the achievements taken by the owner will be triggered on him to sync the colony state

### PR DESCRIPTION
**Pull request by Isfirs**
Closes #79 

# Changes proposed in this pull request:
- Added the behavior of MineColonies related achievements
- Achievements now fire to the colony and sync with players with at least `Permissions.Rank.OFFICER`
- Fixes server crash of @Kostronor lambda expression

Review please @Minecolonies/maintainers

Please test all achievements (creative playthrough will do it, maybe with multiple players)

### CODE REVIEW

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+/**
+ *
+ */
+public final class AchievementUtils {
+
+    public static void syncAchievements(final Colony colony) {
+        final List<Permissions.Player> players = PermissionUtils.getPlayersWithAtleastRank(colony, Permissions.Rank.OFFICER);
+
+        for (Permissions.Player player : players) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Local variable 'player' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+            for (Achievement achievement: colony.getAchievements()) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Local variable 'achievement' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+                ServerUtils.getPlayerFromUUID(player.getID()).triggerAchievement(achievement);
+            }
+        }
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+     * Private Constructor to deny instances
+     */
+    private AchievementUtils() {}
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Move this constructor to comply with Java Code Conventions. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1213)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+import com.minecolonies.colony.Colony;
+import com.minecolonies.colony.permissions.Permissions;
+import net.minecraft.stats.Achievement;
+
+import java.util.List;
+
+/**
+ *
+ */
+public final class AchievementUtils {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Document this public class. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+
+    public static void syncAchievements(final Colony colony) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 7]
```diff
@@ -1062,4 +1060,19 @@ public void onBuildingUpgradeComplete(AbstractBuilding building, int level)
...
+        if (this.colonyAchievements.contains(achievement)) {
+            return;
+        }
+
+        this.colonyAchievements.add(achievement);
+
+        AchievementUtils.syncAchievements(this);
+    }
+
+    public List<Achievement> getAchievements() {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 8]
```diff
@@ -1062,4 +1060,19 @@ public void onBuildingUpgradeComplete(AbstractBuilding building, int level)
     {
         return ServerUtils.getPlayersFromUUID(this.world, this.getPermissions().getMessagePlayers());
     }
+
+    public void triggerAchievement(Achievement achievement) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 9]
```diff
@@ -1062,4 +1060,19 @@ public void onBuildingUpgradeComplete(AbstractBuilding building, int level)
...
+        if (this.colonyAchievements.contains(achievement)) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 10]
```diff
@@ -105,6 +107,8 @@ protected Colony(int id, int dim)
     {
         this.id = id;
         this.dimensionId = dim;
+
+        this.colonyAchievements = new ArrayList<Achievement>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Replace the type specification in this constructor call with the diamond operator ("<>"). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2293)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 11]
```diff
@@ -0,0 +1,34 @@
...
+import java.util.List;
+import java.util.Map;
+import java.util.UUID;
+
+/**
+ *
+ */
+public final class PermissionUtils {
+
+    public static List<Permissions.Player> getPlayersWithAtleastRank(Colony colony, Permissions.Rank rank) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 12]
```diff
@@ -0,0 +1,34 @@
...
+        List<Permissions.Player> playersWithAtLeastRank = new ArrayList<Permissions.Player>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MAJOR Replace the type specification in this constructor call with the diamond operator ("<>"). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2293)
MINOR Local variable 'playersWithAtLeastRank' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 13]
```diff
@@ -0,0 +1,34 @@
...
+
+        final Permissions permissions = colony.getPermissions();
+        final Map<UUID, Permissions.Player> players = permissions.getPlayers();
+
+        for (Permissions.Player player: players.values()) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Local variable 'player' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 14]
```diff
@@ -0,0 +1,34 @@
...
+            if (player.getRank().ordinal() <= rank.ordinal()) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 15]
```diff
@@ -0,0 +1,34 @@
...
+
+import java.util.ArrayList;
+import java.util.List;
+import java.util.Map;
+import java.util.UUID;
+
+/**
+ *
+ */
+public final class PermissionUtils {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Document this public class. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 16]
```diff
@@ -0,0 +1,34 @@
...
+        for (Permissions.Player player: players.values()) {
+            if (player.getRank().ordinal() <= rank.ordinal()) {
+                playersWithAtLeastRank.add(player);
+            }
+        }
+
+        return playersWithAtLeastRank;
+    }
+
+    private PermissionUtils() {}
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Move this constructor to comply with Java Code Conventions. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1213)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 33 issues
* MAJOR 8 major
* MINOR 25 minor

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/4989d1f83e009e8ecebdedd949e09adedad98aa3/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/4989d1f83e009e8ecebdedd949e09adedad98aa3/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/4989d1f83e009e8ecebdedd949e09adedad98aa3/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/4989d1f83e009e8ecebdedd949e09adedad98aa3/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/4989d1f83e009e8ecebdedd949e09adedad98aa3/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/4989d1f83e009e8ecebdedd949e09adedad98aa3/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

**Comment by Kostronor** [comment]
Can we merge this directly into master?  @Minecolonies/maintainers

**Comment by Isfirs** [comment]
I would agree on it once tested and confirmed.!!

**Comment by Isfirs** [comment]
Note: When online, the `Settlement` Achievement gets synced on the next sync

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 17]
```diff
@@ -0,0 +1,35 @@
...
+        final List<Permissions.Player> players = PermissionUtils.getPlayersWithAtleastRank(colony, Permissions.Rank.OFFICER);
+
+        final List<EntityPlayer> lPlayer = ServerUtils.getPlayersFromPermPlayer(players);
+
+        for (EntityPlayer player : lPlayer) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Local variable 'player' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 18]
```diff
@@ -0,0 +1,35 @@
...
+            for (Achievement achievement: colony.getAchievements()) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Local variable 'achievement' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 19]
```diff
@@ -0,0 +1,35 @@
...
+                if (player == null)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MAJOR Missing curly brace. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00121)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 20]
```diff
@@ -105,4 +106,18 @@ public static EntityPlayer getPlayerFromUUID(@Nullable UUID uuid)
         return null;
     }
 
+    public static EntityPlayer getPlayerFromPermPlayer(Permissions.Player player) {
+        return ServerUtils.getPlayerFromUUID(player.getID());
+    }
+
+    public static List<EntityPlayer> getPlayersFromPermPlayer(List<Permissions.Player> players) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 21]
```diff
@@ -105,4 +106,18 @@ public static EntityPlayer getPlayerFromUUID(@Nullable UUID uuid)
         return null;
     }
 
+    public static EntityPlayer getPlayerFromPermPlayer(Permissions.Player player) {
+        return ServerUtils.getPlayerFromUUID(player.getID());
+    }
+
+    public static List<EntityPlayer> getPlayersFromPermPlayer(List<Permissions.Player> players) {
+        List<EntityPlayer> lPlayers = new ArrayList<>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: MINOR Local variable 'lPlayers' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 22]
```diff
@@ -105,4 +106,18 @@ public static EntityPlayer getPlayerFromUUID(@Nullable UUID uuid)
...
     }
 
+    public static EntityPlayer getPlayerFromPermPlayer(Permissions.Player player) {
+        return ServerUtils.getPlayerFromUUID(player.getID());
+    }
+
+    public static List<EntityPlayer> getPlayersFromPermPlayer(List<Permissions.Player> players) {
+        List<EntityPlayer> lPlayers = new ArrayList<>();
+
+        for (Permissions.Player player : players) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Local variable 'player' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 23]
```diff
@@ -105,4 +106,18 @@ public static EntityPlayer getPlayerFromUUID(@Nullable UUID uuid)
         return null;
     }
 
+    public static EntityPlayer getPlayerFromPermPlayer(Permissions.Player player) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)
MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 41 issues
* MAJOR 9 major
* MINOR 32 minor

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/55d51f29b06591a1c1f98ee8b1e88cd5f11980d7/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/55d51f29b06591a1c1f98ee8b1e88cd5f11980d7/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/55d51f29b06591a1c1f98ee8b1e88cd5f11980d7/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/55d51f29b06591a1c1f98ee8b1e88cd5f11980d7/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/55d51f29b06591a1c1f98ee8b1e88cd5f11980d7/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/55d51f29b06591a1c1f98ee8b1e88cd5f11980d7/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 24]
```diff
@@ -0,0 +1,43 @@
...
+    //todo document
+    public static void syncAchievements(@NotNull final Colony colony)
+    {
+        final List<Permissions.Player> players = PermissionUtils.getPlayersWithAtleastRank(colony, Permissions.Rank.OFFICER);
+
+        @NotNull final List<EntityPlayer> lPlayer = ServerUtils.getPlayersFromPermPlayer(players);
+
+        for (@Nullable EntityPlayer player : lPlayer)
+        {
+            for (Achievement achievement : colony.getAchievements())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Local variable 'achievement' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 25]
```diff
@@ -0,0 +1,43 @@
...
+
+import java.util.List;
+
+/**
+ * todo: explain this class
+ */
+public final class AchievementUtils
+{
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 26]
```diff
@@ -0,0 +1,43 @@
...
+     * Private Constructor to deny instances
+     */
+    private AchievementUtils() {}
+
+    //todo document
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 27]
```diff
@@ -0,0 +1,43 @@
+package com.minecolonies.util;
+
+import com.minecolonies.colony.Colony;
+import com.minecolonies.colony.permissions.Permissions;
+import net.minecraft.entity.player.EntityPlayer;
+import net.minecraft.stats.Achievement;
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Remove this unused import 'org.jetbrains.annotations.Nullable'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 28]
```diff
@@ -0,0 +1,43 @@
...
+public final class AchievementUtils
+{
+
+    /**
+     * Private Constructor to deny instances
+     */
+    private AchievementUtils() {}
+
+    //todo document
+    public static void syncAchievements(@NotNull final Colony colony)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 29]
```diff
@@ -0,0 +1,43 @@
...
+import com.minecolonies.colony.Colony;
+import com.minecolonies.colony.permissions.Permissions;
+import net.minecraft.entity.player.EntityPlayer;
+import net.minecraft.stats.Achievement;
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
+
+import java.util.List;
+
+/**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 30]
```diff
@@ -0,0 +1,43 @@
...
+ * todo: explain this class
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 31]
```diff
@@ -0,0 +1,43 @@
...
+    private AchievementUtils() {}
+
+    //todo document
+    public static void syncAchievements(@NotNull final Colony colony)
+    {
+        final List<Permissions.Player> players = PermissionUtils.getPlayersWithAtleastRank(colony, Permissions.Rank.OFFICER);
+
+        @NotNull final List<EntityPlayer> lPlayer = ServerUtils.getPlayersFromPermPlayer(players);
+
+        for (@Nullable EntityPlayer player : lPlayer)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Local variable 'player' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 32]
```diff
@@ -160,6 +166,18 @@ private void readFromNBT(NBTTagCompound compound)
...
         }
 
+        // Restore colony achievements
+        NBTTagList achievementTagList = compound.getTagList(TAG_ACHIEVEMENT_LIST, NBT.TAG_COMPOUND);
+        this.colonyAchievements = new ArrayList<>();
+        for (int i = 0; i < achievementTagList.tagCount(); ++i)
+        {
+            NBTTagCompound achievementCompound = achievementTagList.getCompoundTagAt(i);
+            final String achievementKey = achievementCompound.getString(TAG_ACHIEVEMENT);
+            // todo: retrieve this
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 33]
```diff
@@ -160,6 +166,18 @@ private void readFromNBT(NBTTagCompound compound)
...
+            Achievement a = null;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'a' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 34]
```diff
@@ -1062,4 +1086,22 @@ public void onBuildingUpgradeComplete(AbstractBuilding building, int level)
     {
         return ServerUtils.getPlayersFromUUID(this.world, this.getPermissions().getMessagePlayers());
     }
+
+    public void triggerAchievement(Achievement achievement)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 35]
```diff
@@ -205,6 +223,18 @@ protected void writeToNBT(NBTTagCompound compound)
         }
         compound.setTag(TAG_CITIZENS, citizenTagList);
 
+        //  Achievements
+        NBTTagList achievementsTagList = new NBTTagList();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'achievementsTagList' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 36]
```diff
@@ -205,6 +223,18 @@ protected void writeToNBT(NBTTagCompound compound)
...
+        for (Achievement achievement : this.colonyAchievements)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Remove this unused "achievement" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
MINOR Local variable 'achievement' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 37]
```diff
@@ -205,6 +223,18 @@ protected void writeToNBT(NBTTagCompound compound)
...
+        {
+            //todo: get the key from the achievement
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 38]
```diff
@@ -205,6 +223,18 @@ protected void writeToNBT(NBTTagCompound compound)
...
+            String achievementKey = "";
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'achievementKey' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 39]
```diff
@@ -205,6 +223,18 @@ protected void writeToNBT(NBTTagCompound compound)
...
+            NBTTagCompound achievementCompound = new NBTTagCompound();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'achievementCompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 40]
```diff
@@ -160,6 +166,18 @@ private void readFromNBT(NBTTagCompound compound)
             }
         }
 
+        // Restore colony achievements
+        NBTTagList achievementTagList = compound.getTagList(TAG_ACHIEVEMENT_LIST, NBT.TAG_COMPOUND);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'achievementTagList' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 41]
```diff
@@ -160,6 +166,18 @@ private void readFromNBT(NBTTagCompound compound)
...
+        this.colonyAchievements = new ArrayList<>();
+        for (int i = 0; i < achievementTagList.tagCount(); ++i)
+        {
+            NBTTagCompound achievementCompound = achievementTagList.getCompoundTagAt(i);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'achievementCompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 42]
```diff
@@ -160,6 +166,18 @@ private void readFromNBT(NBTTagCompound compound)
...
+            final String achievementKey = achievementCompound.getString(TAG_ACHIEVEMENT);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Remove this unused "achievementKey" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
MAJOR Remove this useless assignment to local variable "achievementKey". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 43]
```diff
@@ -79,6 +80,27 @@ public static EntityPlayer getPlayerFromUUID(@NotNull World world, @NotNull UUID
...
+
+        for (@NotNull Permissions.Player player : players)
+        {
+            playerList.add(ServerUtils.getPlayerFromPermPlayer(player));
+        }
+
+        return playerList;
+    }
+
+    //todo: document!
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 44]
```diff
@@ -79,6 +80,27 @@ public static EntityPlayer getPlayerFromUUID(@NotNull World world, @NotNull UUID
...
+    @Nullable
+    public static EntityPlayer getPlayerFromPermPlayer(@NotNull Permissions.Player player)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 45]
```diff
@@ -79,6 +80,27 @@ public static EntityPlayer getPlayerFromUUID(@NotNull World world, @NotNull UUID
         return players;
     }
 
+    //todo: document
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 46]
```diff
@@ -79,6 +80,27 @@ public static EntityPlayer getPlayerFromUUID(@NotNull World world, @NotNull UUID
         return players;
     }
 
+    //todo: document
+    @NotNull
+    public static List<EntityPlayer> getPlayersFromPermPlayer(@NotNull List<Permissions.Player> players)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 47]
```diff
@@ -79,6 +80,27 @@ public static EntityPlayer getPlayerFromUUID(@NotNull World world, @NotNull UUID
         return players;
     }
 
+    //todo: document
+    @NotNull
+    public static List<EntityPlayer> getPlayersFromPermPlayer(@NotNull List<Permissions.Player> players)
+    {
+        @NotNull final List<EntityPlayer> playerList = new ArrayList<>();
+
+        for (@NotNull Permissions.Player player : players)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: MINOR Local variable 'player' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 45 issues
* MAJOR 11 major
* MINOR 28 minor
* INFO 6 info

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/974a6d33e5977a1f0c6beac1057b7ae1bd868097/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/974a6d33e5977a1f0c6beac1057b7ae1bd868097/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/974a6d33e5977a1f0c6beac1057b7ae1bd868097/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/974a6d33e5977a1f0c6beac1057b7ae1bd868097/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/974a6d33e5977a1f0c6beac1057b7ae1bd868097/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/974a6d33e5977a1f0c6beac1057b7ae1bd868097/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 48]
```diff
@@ -0,0 +1,45 @@
...
+{
+
+    /**
+     * Private Constructor to deny instances
+     */
+    private AchievementUtils()
+    {
+    }
+
+    //todo document
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 49]
```diff
@@ -0,0 +1,45 @@
...
+    public static void syncAchievements(@NotNull final Colony colony)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 50]
```diff
@@ -0,0 +1,40 @@
...
+ */
+public final class PermissionUtils
+{
+
+    private PermissionUtils()
+    {
+    }
+
+    @NotNull
+    public static List<Permissions.Player> getPlayersWithAtleastRank(@NotNull Colony colony, @NotNull Permissions.Rank rank)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 51]
```diff
@@ -0,0 +1,40 @@
...
+    {
+        @NotNull List<Permissions.Player> playersWithAtLeastRank = new ArrayList<Permissions.Player>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MAJOR Replace the type specification in this constructor call with the diamond operator ("<>"). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2293)
MINOR Local variable 'playersWithAtLeastRank' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 52]
```diff
@@ -0,0 +1,40 @@
...
+import com.minecolonies.colony.Colony;
+import com.minecolonies.colony.permissions.Permissions;
+import org.jetbrains.annotations.NotNull;
+
+import java.util.ArrayList;
+import java.util.List;
+import java.util.Map;
+import java.util.UUID;
+
+/**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 53]
```diff
@@ -0,0 +1,40 @@
...
+ * todo: explain this class
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 54]
```diff
@@ -0,0 +1,40 @@
...
+
+    @NotNull
+    public static List<Permissions.Player> getPlayersWithAtleastRank(@NotNull Colony colony, @NotNull Permissions.Rank rank)
+    {
+        @NotNull List<Permissions.Player> playersWithAtLeastRank = new ArrayList<Permissions.Player>();
+
+        final Permissions permissions = colony.getPermissions();
+        final Map<UUID, Permissions.Player> players = permissions.getPlayers();
+
+        for (@NotNull Permissions.Player player : players.values())
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR Local variable 'player' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 39 issues
* MAJOR 11 major
* MINOR 21 minor
* INFO 7 info

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/d478a2e87b1aefadd092aaa67aa5361e05c41328/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/d478a2e87b1aefadd092aaa67aa5361e05c41328/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/d478a2e87b1aefadd092aaa67aa5361e05c41328/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/d478a2e87b1aefadd092aaa67aa5361e05c41328/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/d478a2e87b1aefadd092aaa67aa5361e05c41328/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/d478a2e87b1aefadd092aaa67aa5361e05c41328/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 55]
```diff
@@ -0,0 +1,45 @@
...
+import com.minecolonies.colony.permissions.Permissions;
+import net.minecraft.entity.player.EntityPlayer;
+import net.minecraft.stats.Achievement;
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
+
+import java.util.List;
+
+/**
+ * todo: explain this class.
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 56]
```diff
@@ -160,6 +167,18 @@ private void readFromNBT(NBTTagCompound compound)
             }
         }
 
+        // Restore colony achievements
+        final NBTTagList achievementTagList = compound.getTagList(TAG_ACHIEVEMENT_LIST, NBT.TAG_COMPOUND);
+        this.colonyAchievements = new ArrayList<>();
+        for (int i = 0; i < achievementTagList.tagCount(); ++i)
+        {
+            final NBTTagCompound achievementCompound = achievementTagList.getCompoundTagAt(i);
+            final String achievementKey = achievementCompound.getString(TAG_ACHIEVEMENT);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Remove this unused "achievementKey" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
MAJOR Remove this useless assignment to local variable "achievementKey". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 57]
```diff
@@ -160,6 +167,18 @@ private void readFromNBT(NBTTagCompound compound)
...
+            // todo: retrieve this
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 58]
```diff
@@ -1062,4 +1087,24 @@ public void onBuildingUpgradeComplete(AbstractBuilding building, int level)
     {
         return ServerUtils.getPlayersFromUUID(this.world, this.getPermissions().getMessagePlayers());
     }
+
+    // todo: document!
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 59]
```diff
@@ -1062,4 +1087,24 @@ public void onBuildingUpgradeComplete(AbstractBuilding building, int level)
...
+    public void triggerAchievement(@NotNull Achievement achievement)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 60]
```diff
@@ -205,6 +224,18 @@ protected void writeToNBT(NBTTagCompound compound)
         }
         compound.setTag(TAG_CITIZENS, citizenTagList);
 
+        //  Achievements
+        final NBTTagList achievementsTagList = new NBTTagList();
+        for (final Achievement achievement : this.colonyAchievements)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Remove this unused "achievement" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 61]
```diff
@@ -205,6 +224,18 @@ protected void writeToNBT(NBTTagCompound compound)
...
+        {
+            //todo: get the key from the achievement
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 62]
```diff
@@ -0,0 +1,44 @@
...
+{
+
+    /**
+     * Private constructor to hide the implicit public one.
+     */
+    private PermissionUtils()
+    {
+    }
+
+    // todo: document!
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 63]
```diff
@@ -0,0 +1,44 @@
...
+    @NotNull
+    public static List<Permissions.Player> getPlayersWithAtleastRank(@NotNull Colony colony, @NotNull Permissions.Rank rank)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR Document this public method. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 64]
```diff
@@ -0,0 +1,44 @@
...
+    {
+        @NotNull List<Permissions.Player> playersWithAtLeastRank = new ArrayList<Permissions.Player>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MAJOR Replace the type specification in this constructor call with the diamond operator ("<>"). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2293)
MINOR Local variable 'playersWithAtLeastRank' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 65]
```diff
@@ -0,0 +1,44 @@
...
+import com.minecolonies.colony.permissions.Permissions;
+import org.jetbrains.annotations.NotNull;
+
+import java.util.ArrayList;
+import java.util.List;
+import java.util.Map;
+import java.util.UUID;
+
+/**
+ * todo: explain this class.
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 27 issues
* MAJOR 10 major
* MINOR 8 minor
* INFO 9 info

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/f484a0447dc21d5538dfa779bddf249ac846a8d8/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/f484a0447dc21d5538dfa779bddf249ac846a8d8/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/f484a0447dc21d5538dfa779bddf249ac846a8d8/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/f484a0447dc21d5538dfa779bddf249ac846a8d8/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/f484a0447dc21d5538dfa779bddf249ac846a8d8/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/f484a0447dc21d5538dfa779bddf249ac846a8d8/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 66]
```diff
@@ -0,0 +1,45 @@
+package com.minecolonies.util;
+
+import com.minecolonies.colony.Colony;
+import com.minecolonies.colony.permissions.Permissions;
+import net.minecraft.entity.player.EntityPlayer;
+import net.minecraft.stats.Achievement;
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Remove this unused import 'org.jetbrains.annotations.Nullable'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 67]
```diff
@@ -105,6 +112,8 @@ protected Colony(int id, int dim)
     {
         this.id = id;
         this.dimensionId = dim;
+
+        this.colonyAchievements = new ArrayList<Achievement>();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Replace the type specification in this constructor call with the diamond operator ("<>"). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS2293)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 68]
```diff
@@ -160,6 +169,20 @@ private void readFromNBT(NBTTagCompound compound)
...
+        // Restore colony achievements
+        final NBTTagList achievementTagList = compound.getTagList(TAG_ACHIEVEMENT_LIST, NBT.TAG_COMPOUND);
+        this.colonyAchievements = new ArrayList<>();
+        for (int i = 0; i < achievementTagList.tagCount(); ++i)
+        {
+            final NBTTagCompound achievementCompound = achievementTagList.getCompoundTagAt(i);
+            final String achievementKey = achievementCompound.getString(TAG_ACHIEVEMENT);
+            // todo: retrieve this
+            final StatBase statBase = StatList.getOneShotStat(achievementKey);
+            if (statBase instanceof Achievement) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 69]
```diff
@@ -205,6 +228,18 @@ protected void writeToNBT(NBTTagCompound compound)
         }
         compound.setTag(TAG_CITIZENS, citizenTagList);
 
+        //  Achievements
+        final NBTTagList achievementsTagList = new NBTTagList();
+        for (final Achievement achievement : this.colonyAchievements)
+        {
+            // TODO: Validate this
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: INFO Complete the task associated to this TODO comment. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1135)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 70]
```diff
@@ -205,6 +228,18 @@ protected void writeToNBT(NBTTagCompound compound)
...
+            String achievementKey = achievement.statId;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'achievementKey' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 71]
```diff
@@ -205,6 +228,18 @@ protected void writeToNBT(NBTTagCompound compound)
...
+            NBTTagCompound achievementCompound = new NBTTagCompound();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'achievementCompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 28 issues
* MAJOR 8 major
* MINOR 11 minor
* INFO 9 info

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/ba3f8256ffab51b8ff1f3554b03c945155721df7/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/ba3f8256ffab51b8ff1f3554b03c945155721df7/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/ba3f8256ffab51b8ff1f3554b03c945155721df7/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/ba3f8256ffab51b8ff1f3554b03c945155721df7/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/ba3f8256ffab51b8ff1f3554b03c945155721df7/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/ba3f8256ffab51b8ff1f3554b03c945155721df7/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java [hunk 72]
```diff
@@ -93,11 +93,11 @@ public void onUpgradeComplete(final int newLevel)
```
Comment (cltnschlosser) [inline src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java]: Lets get rid of the owner variable

Comment (Kostronor) [inline src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java]: agreed

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 28 issues
* MAJOR 8 major
* MINOR 11 minor
* INFO 9 info

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/04edc7fa6abb5122936c21e6aabd6735e79e9cdb/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/04edc7fa6abb5122936c21e6aabd6735e79e9cdb/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/04edc7fa6abb5122936c21e6aabd6735e79e9cdb/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/04edc7fa6abb5122936c21e6aabd6735e79e9cdb/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/04edc7fa6abb5122936c21e6aabd6735e79e9cdb/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/04edc7fa6abb5122936c21e6aabd6735e79e9cdb/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

File: src/main/java/com/minecolonies/items/AbstractItemMinecolonies.java [hunk 73]
```diff
@@ -26,5 +30,7 @@ public AbstractItemMinecolonies()
      *
      * @return      Name of the item
      */
-    public abstract String getName();
+    public String getName() {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/items/AbstractItemMinecolonies.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/items/AbstractItemMinecolonies.java [hunk 74]
```diff
@@ -10,14 +10,18 @@
  */
 public abstract class AbstractItemMinecolonies extends Item
 {
+    private final String name;
+
     /**
      * Sets the name, creative tab, and registers the item.
      */
-    public AbstractItemMinecolonies()
+    public AbstractItemMinecolonies(String name)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/items/AbstractItemMinecolonies.java]: MINOR Document the parameter(s): name [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/items/ItemProxyColonySize.java [hunk 75]
```diff
@@ -0,0 +1,24 @@
...
+ * This is a multi used proxy class for the size related achievements.
+ * 
+ * @since 0.3
+ */
+public class ItemProxyColonySize extends AbstractItemMinecolonies
+{
+
+    private String name;
+
+    public ItemProxyColonySize(String name)
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/items/ItemProxyColonySize.java]: MINOR Document this public constructor. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

File: src/main/java/com/minecolonies/achievements/ModAchievements.java [hunk 76]
```diff
@@ -105,16 +110,21 @@
     /**
      * Reach {@link ModAchievements#ACHIEVEMENT_SIZE_SETTLEMENT} citizens.
      */
-    public static final Achievement achievementSizeSettlement = new MineColoniesAchievement("size.pioneer", "size.settlement", 2, -2, Items.iron_ingot, null).registerStat();
+    public static final Achievement achievementSizeSettlement = new MineColoniesAchievement("size.pioneer", "size.settlement", 2, -2, ModItems.itemProxySizeSettlement, null).registerStat();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/achievements/ModAchievements.java]: MINOR Split this 189 characters long line (which is greater than 180 authorized). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/achievements/ModAchievements.java [hunk 77]
```diff
@@ -105,16 +110,21 @@
...
      * Reach {@link ModAchievements#ACHIEVEMENT_SIZE_TOWN} citizens.
      */
-    public static final Achievement achievementSizeTown       = new MineColoniesAchievement("size.town", "size.town", 4, -2, Items.gold_ingot, achievementSizeSettlement)
+    public static final Achievement achievementSizeTown       = new MineColoniesAchievement("size.town", "size.town", 4, -2, ModItems.itemProxySizeTown, achievementSizeSettlement)
             .registerStat();
     /**
      * Reach {@link ModAchievements#ACHIEVEMENT_SIZE_CITY} citizens.
      */
-    public static final Achievement achievementSizeCity       = new MineColoniesAchievement("size.city", "size.city", 6, -2, Items.diamond, achievementSizeTown).registerStat();
+    public static final Achievement achievementSizeCity       = new MineColoniesAchievement("size.city", "size.city", 6, -2, ModItems.itemProxySizeCity, achievementSizeTown).registerStat();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/achievements/ModAchievements.java]: MINOR Split this 189 characters long line (which is greater than 180 authorized). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00103)

File: src/main/java/com/minecolonies/achievements/ModAchievements.java [hunk 78]
```diff
@@ -105,16 +110,21 @@
...
+    
+    /**
+     * Reach {@link ModAchievements#ACHIEVEMENT_SIZE_CITY} citizens.
+     */
+    public static final Achievement achievementSizeMetropolis       = new MineColoniesAchievement("size.metropolis", "size.metropolis", 8, -2, ModItems.itemProxySizeMetropolis, achievementSizeCity).registerStat();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/achievements/ModAchievements.java]: MINOR Split this 213 characters long line (which is greater than 180 authorized). [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00103)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 34 issues
* MAJOR 8 major
* MINOR 17 minor
* INFO 9 info

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/7997d498e665152c56cef495b1d4c47e7e3c2d6c/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/7997d498e665152c56cef495b1d4c47e7e3c2d6c/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/7997d498e665152c56cef495b1d4c47e7e3c2d6c/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/7997d498e665152c56cef495b1d4c47e7e3c2d6c/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/7997d498e665152c56cef495b1d4c47e7e3c2d6c/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/7997d498e665152c56cef495b1d4c47e7e3c2d6c/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

**Comment by Raycoms** [comment]
I think @Isfirs only has to remove the owner stuff and we're good for a new release.

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 79]
```diff
@@ -0,0 +1,48 @@
...
+{
+
+    /**
+     * Private constructor to hide the implicit public one.
+     */
+    private AchievementUtils()
+    {
+    }
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 80]
```diff
@@ -160,6 +169,21 @@ private void readFromNBT(NBTTagCompound compound)
...
 
+        // Restore colony achievements
+        final NBTTagList achievementTagList = compound.getTagList(TAG_ACHIEVEMENT_LIST, NBT.TAG_COMPOUND);
+        this.colonyAchievements = new ArrayList<>();
+        for (int i = 0; i < achievementTagList.tagCount(); ++i)
+        {
+            final NBTTagCompound achievementCompound = achievementTagList.getCompoundTagAt(i);
+            final String achievementKey = achievementCompound.getString(TAG_ACHIEVEMENT);
+            final StatBase statBase = StatList.getOneShotStat(achievementKey);
+            System.out.println("Checking stat: "+achievementKey+":"+statBase.statId);
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Replace this usage of System.out or System.err by a logger. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS106)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 81]
```diff
@@ -160,6 +169,21 @@ private void readFromNBT(NBTTagCompound compound)
...
+            if (statBase instanceof Achievement) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 82]
```diff
@@ -160,6 +169,21 @@ private void readFromNBT(NBTTagCompound compound)
...
+                System.out.println("Found an achievement");
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MAJOR Replace this usage of System.out or System.err by a logger. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS106)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 83]
```diff
@@ -205,6 +229,17 @@ protected void writeToNBT(NBTTagCompound compound)
         }
         compound.setTag(TAG_CITIZENS, citizenTagList);
 
+        //  Achievements
+        final NBTTagList achievementsTagList = new NBTTagList();
+        for (final Achievement achievement : this.colonyAchievements)
+        {
+            String achievementKey = achievement.statId;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'achievementKey' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 84]
```diff
@@ -205,6 +229,17 @@ protected void writeToNBT(NBTTagCompound compound)
...
+            NBTTagCompound achievementCompound = new NBTTagCompound();
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Local variable 'achievementCompound' could be declared final [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=pmd%3ALocalVariableCouldBeFinal)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 21 issues
* MAJOR 10 major
* MINOR 9 minor
* INFO 2 info

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/7e6a4f437e399fdc84ca9aa259fa8b7067a2d32e/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingBuilder.java#L92](https://github.com/Minecolonies/minecolonies/blob/7e6a4f437e399fdc84ca9aa259fa8b7067a2d32e/src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/7e6a4f437e399fdc84ca9aa259fa8b7067a2d32e/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingFisherman.java#L92](https://github.com/Minecolonies/minecolonies/blob/7e6a4f437e399fdc84ca9aa259fa8b7067a2d32e/src/main/java/com/minecolonies/colony/buildings/BuildingFisherman.java#L92): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/7e6a4f437e399fdc84ca9aa259fa8b7067a2d32e/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this unused "owner" local variable. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1481)
1. MAJOR [BuildingLumberjack.java#L96](https://github.com/Minecolonies/minecolonies/blob/7e6a4f437e399fdc84ca9aa259fa8b7067a2d32e/src/main/java/com/minecolonies/colony/buildings/BuildingLumberjack.java#L96): Remove this useless assignment to local variable "owner". [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1854)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 15 issues
* MAJOR 4 major
* MINOR 9 minor
* INFO 2 info

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java (hunk 72 above)
Comment (Isfirs) [inline src/main/java/com/minecolonies/colony/buildings/BuildingBuilder.java]: Removed?

File: src/main/java/com/minecolonies/items/AbstractItemMinecolonies.java (hunk 73 above)
Comment (Kostronor) [inline src/main/java/com/minecolonies/items/AbstractItemMinecolonies.java]: can you make this final?

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 85]
```diff
@@ -0,0 +1,49 @@
...
+
+import java.util.List;
+
+/**
+ * Some utiility methods all around achievements.
+ */
+public final class AchievementUtils
+{
+
+    /**
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR First sentence should end with a period. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AJavadoc_Style)

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 86]
```diff
@@ -0,0 +1,49 @@
...
+
+                player.triggerAchievement(achievement);
+            }
+        }
+    }
+
+    /**
+     * Private constructor to hide the implicit public one.
+     */
+    private AchievementUtils()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Move this constructor to comply with Java Code Conventions. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1213)

File: src/main/java/com/minecolonies/util/ServerUtils.java [hunk 87]
```diff
@@ -105,4 +139,11 @@ public static EntityPlayer getPlayerFromUUID(@Nullable UUID uuid)
         return null;
     }
 
+    /**
+     * Private constructor to hide the implicit public one.
+     */
+    private ServerUtils()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/ServerUtils.java]: MINOR Move this constructor to comply with Java Code Conventions. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1213)

File: src/main/java/com/minecolonies/util/PermissionUtils.java [hunk 88]
```diff
@@ -0,0 +1,53 @@
...
+            }
+        }
+
+        return playersWithAtLeastRank;
+    }
+
+    /**
+     * Private constructor to hide the implicit public one.
+     */
+    private PermissionUtils()
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/PermissionUtils.java]: MINOR Move this constructor to comply with Java Code Conventions. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1213)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 10 issues
* MAJOR 2 major
* MINOR 8 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 89]
```diff
@@ -160,6 +169,19 @@ private void readFromNBT(NBTTagCompound compound)
...
 
+        // Restore colony achievements
+        final NBTTagList achievementTagList = compound.getTagList(TAG_ACHIEVEMENT_LIST, NBT.TAG_COMPOUND);
+        this.colonyAchievements = new ArrayList<>();
+        for (int i = 0; i < achievementTagList.tagCount(); ++i)
+        {
+            final NBTTagCompound achievementCompound = achievementTagList.getCompoundTagAt(i);
+            final String achievementKey = achievementCompound.getString(TAG_ACHIEVEMENT);
+            final StatBase statBase = StatList.getOneShotStat(achievementKey);
+            if (statBase instanceof Achievement) {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/colony/Colony.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 2 issues
* MINOR 2 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 90]
```diff
@@ -1062,4 +1090,30 @@ public void onBuildingUpgradeComplete(AbstractBuilding building, int level)
...
+            return;
+        }
+
+        this.colonyAchievements.add(achievement);
+
+        AchievementUtils.syncAchievements(this);
+    }
+
+    @NotNull
+    public List<Achievement> getAchievements()
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/colony/Colony.java]: final please

File: src/main/java/com/minecolonies/colony/Colony.java [hunk 91]
```diff
@@ -1062,4 +1090,30 @@ public void onBuildingUpgradeComplete(AbstractBuilding building, int level)
...
     }
+
+    /**
+     * Triggers an achievement on this colony.
+     *
+     * Will automatically sync to all players.
+     *
+     * @param achievement The achievement to trigger
+     */
+    public void triggerAchievement(@NotNull Achievement achievement)
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/colony/Colony.java]: final too

File: src/main/java/com/minecolonies/items/AbstractItemMinecolonies.java [hunk 92]
```diff
@@ -26,5 +32,7 @@ public AbstractItemMinecolonies()
      *
      * @return      Name of the item
      */
-    public abstract String getName();
+    public final String getName() {
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/items/AbstractItemMinecolonies.java]: MINOR Move this left curly brace to the beginning of next line of code. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 1 issue
* MINOR 1 minor

Watch the comments in this conversation to review them.

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 93]
```diff
@@ -0,0 +1,49 @@
...
+     *
+     * @param colony The colony to sync
+     */
+    public static void syncAchievements(@NotNull final Colony colony)
+    {
+        final List<Permissions.Player> players = PermissionUtils.getPlayersWithAtLeastRank(colony, Permissions.Rank.OFFICER);
+
+        @NotNull final List<EntityPlayer> lPlayer = ServerUtils.getPlayersFromPermPlayer(players);
+
+        for (@NotNull final EntityPlayer player : lPlayer)
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: Wrong, because the players inserted can be null.
See: https://github.com/Minecolonies/minecolonies/pull/82/files#diff-587e20803d1c1e27c37cd5378d755425R118

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 94]
```diff
@@ -0,0 +1,49 @@
...
+        {
+            for (final Achievement achievement : colony.getAchievements())
+            {
+                if (player == null)
```
Comment (Kostronor) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: The nullcheck would not be needed if the annotation would be correct...
But the annotation is wrong

File: src/main/java/com/minecolonies/util/AchievementUtils.java [hunk 95]
```diff
@@ -0,0 +1,50 @@
+package com.minecolonies.util;
+
+import com.minecolonies.colony.Colony;
+import com.minecolonies.colony.permissions.Permissions;
+import net.minecraft.entity.player.EntityPlayer;
+import net.minecraft.stats.Achievement;
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
```
Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Remove this unused import 'org.jetbrains.annotations.Nullable'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

Comment (MinecoloniesSonar) [inline src/main/java/com/minecolonies/util/AchievementUtils.java]: MINOR Remove this unused import 'org.jetbrains.annotations.Nullable'. [rule](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AUselessImportCheck)

**Comment by Raycoms** [comment]
:shipit: good to go for me

**Comment by Kostronor** [comment]
:shipit:
